//! Property round trips over every serializer (spec §35.2, AGENTS.md §11).
//!
//! The corpus is generated by [`ono_testkit::Rng`] from a fixed seed, so a failure is
//! reproducible from the message alone. Each format is asserted at exactly the strength it can
//! honestly claim: JSON, YAML and the raw byte form are lossless for what they carry; CSV is a
//! lossy export, and the property it does satisfy is written down here rather than assumed.

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    reason = "a failed precondition in a test should abort the test loudly"
)]

use std::path::Path;
use std::sync::Arc;

use bytes::Bytes;
use ono_core::ErrorCode;
use ono_testkit::Rng;
use ono_value::{
    ByteSize, Decimal, Duration, ErrorValue, FieldDef, FieldType, IpNetwork, MapValue, Percent,
    Provenance, RecordValue, RegexValue, Schema, SchemaId, SchemaRegistry, Uuid, Value, from_bytes,
    from_csv, from_json_str, from_yaml, to_bytes, to_csv, to_json_string, to_yaml,
};

const SEED: u64 = 0x0005_E11D;

fn corpus_schema() -> Schema {
    Schema::builder(SchemaId::new("ono.corpus", 1), "Corpus")
        .field(FieldDef::new("name", FieldType::String).required())
        .field(FieldDef::new("count", FieldType::Int).nullable())
        .field(FieldDef::new("size", FieldType::ByteSize).nullable())
        .identity(["name"])
        .build()
        .unwrap()
}

fn registry() -> SchemaRegistry {
    let mut schemas = SchemaRegistry::new();
    schemas.register(corpus_schema()).unwrap();
    schemas
}

fn scalar(rng: &mut Rng) -> Value {
    match rng.below(20) {
        0 => Value::Null,
        1 => Value::Bool(rng.below(2) == 1),
        2 => Value::Int(i128::from(rng.next_u64() as i64)),
        3 => Value::Int(i128::from(i64::MAX) * 5 + rng.below(13) as i128),
        4 => Value::Float(f64::from(rng.next_u64() as i32) / 32.0),
        5 => Value::Float(f64::INFINITY),
        6 => Value::Decimal(Decimal::new(i128::from(rng.next_u64() as i64), 3).unwrap()),
        7 => Value::String(format!("value {} \u{1b}[31m", rng.next_u64()).into()),
        8 => Value::Bytes(Bytes::from(vec![
            0xff,
            0x00,
            0xfe,
            0x80,
            rng.below(256) as u8,
        ])),
        9 => Value::Path(Arc::from(Path::new("/proc/1/status"))),
        10 => Value::Timestamp(
            jiff::Timestamp::from_nanosecond(i128::from(rng.next_u64() as u32) * 1_000).unwrap(),
        ),
        11 => Value::Duration(Duration::from_nanoseconds(
            i128::from(rng.next_u64() as i32),
        )),
        12 => Value::ByteSize(ByteSize::from_bytes(u128::from(rng.next_u64()))),
        13 => Value::Percent(Percent::new(f64::from(rng.below(10_000) as u32) / 100.0)),
        14 => Value::Regex(Arc::new(RegexValue::new("^ono-[0-9]+$").unwrap())),
        15 => Value::Uuid(Uuid::from_bytes(
            rng.next_u64().to_be_bytes().repeat(2).try_into().unwrap(),
        )),
        16 => Value::Ip(std::net::IpAddr::from([192, 0, 2, rng.below(256) as u8])),
        17 => Value::IpNetwork(IpNetwork::new(std::net::IpAddr::from([192, 0, 2, 0]), 24).unwrap()),
        18 => Value::Port(rng.below(65_536) as u16),
        _ => ErrorValue::new(ErrorCode::IoPermissionDenied, "access denied")
            .with_help("requires root or read capability")
            .with_source(ErrorValue::new(
                ErrorCode::ProviderUnavailable,
                "procfs is not mounted",
            ))
            .into_value(),
    }
}

fn value(rng: &mut Rng, depth: u32) -> Value {
    if depth == 0 || rng.below(3) > 0 {
        return scalar(rng);
    }
    match rng.below(3) {
        0 => Value::list(
            (0..rng.below(4))
                .map(|_| value(rng, depth - 1))
                .collect::<Vec<_>>(),
        ),
        1 => {
            let mut map = MapValue::new();
            for index in 0..rng.below(4) {
                map.insert(format!("key{index}").into(), value(rng, depth - 1));
            }
            Value::Map(Arc::new(map))
        }
        _ => {
            let schema = Arc::new(corpus_schema());
            RecordValue::builder(
                schema,
                Provenance::local("corpus", SchemaId::new("ono.corpus", 1)),
            )
            .set("name", Value::string("corpus"))
            .unwrap()
            .set("count", scalar(rng))
            .unwrap()
            .set("size", scalar(rng))
            .unwrap()
            .build()
            .into_value()
        }
    }
}

fn corpus(count: usize) -> Vec<Value> {
    let mut rng = Rng::seeded(SEED);
    (0..count).map(|_| value(&mut rng, 3)).collect()
}

#[test]
fn should_round_trip_every_generated_value_through_json() {
    let schemas = registry();
    for (index, original) in corpus(400).into_iter().enumerate() {
        let text = to_json_string(&original).unwrap();
        let back = from_json_str(&text, &schemas)
            .unwrap_or_else(|error| panic!("seed {SEED:#x} value {index}: {error}\n{text}"));
        assert_eq!(back, original, "seed {SEED:#x} value {index}: {text}");
    }
}

#[test]
fn should_round_trip_every_generated_value_through_yaml() {
    let schemas = registry();
    for (index, original) in corpus(400).into_iter().enumerate() {
        let text = to_yaml(&original).unwrap();
        let back = from_yaml(&text, &schemas)
            .unwrap_or_else(|error| panic!("seed {SEED:#x} value {index}: {error}\n{text}"));
        assert_eq!(back, original, "seed {SEED:#x} value {index}: {text}");
    }
}

#[test]
fn should_round_trip_every_generated_byte_string_through_the_raw_form() {
    let mut rng = Rng::seeded(SEED);
    for index in 0..200 {
        let raw: Vec<u8> = (0..rng.below(64)).map(|_| rng.below(256) as u8).collect();
        let original = Value::Bytes(Bytes::from(raw));
        let back = from_bytes(to_bytes(&original).unwrap());
        assert_eq!(back, original, "seed {SEED:#x} value {index}");
    }
}

#[test]
fn should_write_the_same_csv_document_on_every_later_pass() {
    // CSV carries no types, so `from_csv(to_csv(v)) == v` cannot hold and claiming it would be a
    // lie. What does hold is that the text is stable: the document is a fixed point from the
    // second pass onwards, so an export can be re-imported and re-exported without drift.
    let mut rng = Rng::seeded(SEED);
    let schema = Arc::new(corpus_schema());
    let records: Vec<Value> = (0..64)
        .map(|index| {
            RecordValue::builder(
                Arc::clone(&schema),
                Provenance::local("corpus", SchemaId::new("ono.corpus", 1)),
            )
            .set("name", Value::string(&format!("row-{index}")))
            .unwrap()
            .set(
                "count",
                if rng.chance(4) {
                    Value::Null
                } else {
                    Value::Int(i128::from(rng.next_u64() as i32))
                },
            )
            .unwrap()
            .set(
                "size",
                Value::ByteSize(ByteSize::from_bytes(u128::from(rng.next_u64()))),
            )
            .unwrap()
            .build()
            .into_value()
        })
        .collect();

    let first = to_csv(&records).unwrap();
    let second = to_csv(from_csv(&first).unwrap().as_list().unwrap()).unwrap();
    let third = to_csv(from_csv(&second).unwrap().as_list().unwrap()).unwrap();
    assert_eq!(second, first, "seed {SEED:#x}");
    assert_eq!(third, second, "seed {SEED:#x}");
}
