//! Compiled components (ADR-0870): the shell carries the WebAssembly runtime and no compiler.
//!
//! A `wasm-component` package ships `runtime/component.wasm` (spec §31.36), and that stays the
//! package format. What runs is the engine's own compiled form of it, written once by
//! `kuang-compile` — the SDK's tool, which `install plugin` runs — into an artifact store, and
//! loaded here by mapping it. The shell links no code generator, so a component nobody compiled
//! is refused with the command that compiles it rather than compiled on the spot.
//!
//! An artifact is named by the SHA-256 of the component it was compiled from, so it belongs to
//! exactly those bytes: a package upgrade that changes the component finds no artifact, and a
//! shell upgrade that changes the engine finds one the engine refuses. Artifacts never live in
//! the package directory. A package is somebody else's bytes; a compiled artifact is native code
//! the shell maps into itself, and one that could arrive inside a package would be a way around
//! every confinement the runtime gives.

use std::io::ErrorKind;
use std::path::{Path, PathBuf};

use ono_kuang_protocol::{KuangError, KuangErrorCode};
use serde_json::json;
use wasmtime::component::Component;

/// The tool that writes an artifact, as the refusal names it.
pub const COMPILE_TOOL: &str = "kuang-compile";

/// The store whoever administers the machine writes: an image build, or a distribution package.
pub const SYSTEM_STORE: &str = "/usr/lib/ono-sendai/kuang-compiled";

/// The operator's own store: `$XDG_CACHE_HOME/ono/kuang/compiled`, or `~/.cache/ono/...`.
///
/// A cache in the XDG sense: everything in it is derived from a component and regenerated by one
/// command. `None` when the environment names no absolute home at all.
#[must_use]
pub fn user_store() -> Option<PathBuf> {
    let absolute = |name: &str| {
        std::env::var_os(name)
            .map(PathBuf::from)
            .filter(|path| path.is_absolute())
    };
    let cache =
        absolute("XDG_CACHE_HOME").or_else(|| absolute("HOME").map(|home| home.join(".cache")))?;
    Some(cache.join("ono").join("kuang").join("compiled"))
}

/// Where a component's artifact is looked for, in order: the operator's store, then the system's.
#[must_use]
pub fn stores() -> Vec<PathBuf> {
    user_store()
        .into_iter()
        .chain(std::iter::once(PathBuf::from(SYSTEM_STORE)))
        .collect()
}

/// The file name of the artifact compiled from `component`: its SHA-256, and `.cwasm`.
#[must_use]
pub fn artifact_name(component: &[u8]) -> String {
    use sha2::Digest as _;
    let digest = sha2::Sha256::digest(component);
    let mut name = String::with_capacity(70);
    for byte in digest {
        name.push_str(&format!("{byte:02x}"));
    }
    name.push_str(".cwasm");
    name
}

/// The engine the artifact has to come from, as the refusal names it: the version wasmtime
/// stamps into every artifact it writes, and the architecture it compiles for.
#[must_use]
pub fn engine_identity() -> String {
    format!(
        "wasmtime {} on {}",
        wasmtime::ModuleVersionStrategy::default().as_str(),
        std::env::consts::ARCH
    )
}

/// Why no artifact could be loaded, as `load.component_not_compiled`'s `reason` spells it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Reason {
    /// No store holds an artifact for these bytes.
    Missing,
    /// An artifact is there and the engine refuses it: another engine version, another
    /// architecture, or bytes that are not an artifact at all.
    Incompatible,
    /// An artifact is there and someone other than its owner or root could have written it.
    Untrusted,
}

impl Reason {
    /// The word the error metadata carries.
    #[must_use]
    pub const fn word(self) -> &'static str {
        match self {
            Self::Missing => "missing",
            Self::Incompatible => "incompatible",
            Self::Untrusted => "untrusted",
        }
    }
}

/// What the lookup found instead of a loadable artifact.
#[derive(Debug, Clone)]
pub struct NotCompiled {
    reason: Reason,
    artifact: PathBuf,
    detail: String,
}

impl NotCompiled {
    /// Why.
    #[must_use]
    pub const fn reason(&self) -> Reason {
        self.reason
    }

    /// The structured refusal for `package`, whose component is `component`.
    #[must_use]
    pub fn into_error(self, package: &str, component: &Path) -> KuangError {
        let command = format!("{COMPILE_TOOL} {}", component.display());
        let what = match self.reason {
            Reason::Missing => "has not been compiled for this shell".to_owned(),
            Reason::Incompatible => format!(
                "has a compiled artifact this shell's engine ({}) refuses: {}",
                engine_identity(),
                self.detail
            ),
            Reason::Untrusted => format!(
                "has a compiled artifact the shell will not map: {}",
                self.detail
            ),
        };
        let remedy = match self.reason {
            Reason::Untrusted => format!(
                "remove `{}` or make it writable by its owner only, then run `{command}`",
                self.artifact.display()
            ),
            Reason::Missing | Reason::Incompatible => format!("run `{command}`"),
        };
        KuangError::new(
            KuangErrorCode::LoadComponentNotCompiled,
            format!(
                "the component of `{package}` ({}) {what}; {remedy}",
                component.display()
            ),
        )
        .with_help(format!(
            "`{COMPILE_TOOL}` compiles a component once, for this engine and this machine; \
             `install plugin` runs it, and a shell upgrade or a changed component needs it again"
        ))
        .with_metadata("reason", json!(self.reason.word()))
        .with_metadata("component", json!(component.display().to_string()))
        .with_metadata("artifact", json!(self.artifact.display().to_string()))
        .with_metadata("engine", json!(engine_identity()))
        .with_metadata("command", json!(command))
    }
}

/// Why a component could not be loaded at all.
#[derive(Debug)]
pub enum LoadFailure {
    /// No artifact this engine may load: the refusal that names the compile step.
    NotCompiled(NotCompiled),
    /// The component itself could not be read.
    Unreadable(String),
}

/// The component at `component`, from the first store in `stores` holding a loadable artifact
/// for its bytes.
///
/// A store whose artifact is refused does not end the search: a stale artifact in the operator's
/// store must not hide a current one the system provides. When none loads, the first refusal is
/// the answer, and `missing` only when no store had an artifact at all.
pub(crate) fn load(
    engine: &wasmtime::Engine,
    component: &Path,
    stores: &[PathBuf],
) -> Result<Component, LoadFailure> {
    let bytes = std::fs::read(component).map_err(|error| {
        LoadFailure::Unreadable(format!(
            "`{}` could not be read: {error}",
            component.display()
        ))
    })?;
    let name = artifact_name(&bytes);
    let mut first_refusal = None;
    for store in stores {
        let artifact = store.join(&name);
        let refusal = match std::fs::metadata(&artifact) {
            Err(error)
                if matches!(error.kind(), ErrorKind::NotFound | ErrorKind::NotADirectory) =>
            {
                continue;
            }
            Err(error) => NotCompiled {
                reason: Reason::Incompatible,
                artifact: artifact.clone(),
                detail: error.to_string(),
            },
            Ok(_) => match trusted(&artifact) {
                Err(detail) => NotCompiled {
                    reason: Reason::Untrusted,
                    artifact: artifact.clone(),
                    detail,
                },
                Ok(()) => match map(engine, &artifact) {
                    Ok(component) => return Ok(component),
                    Err(error) => NotCompiled {
                        reason: Reason::Incompatible,
                        artifact: artifact.clone(),
                        detail: format!("{error:#}"),
                    },
                },
            },
        };
        first_refusal.get_or_insert(refusal);
    }
    Err(LoadFailure::NotCompiled(first_refusal.unwrap_or_else(
        || {
            NotCompiled {
                reason: Reason::Missing,
                artifact: stores
                    .first()
                    .map_or_else(|| PathBuf::from(&name), |store| store.join(&name)),
                detail: String::new(),
            }
        },
    )))
}

/// Whether the artifact and the store holding it could only have been written by the user this
/// shell runs as, or by root — the condition ADR-0870's safety argument rests on, checked rather
/// than assumed.
fn trusted(artifact: &Path) -> Result<(), String> {
    only_its_owner_writes("the artifact", artifact)?;
    only_its_owner_writes("its store", artifact.parent().unwrap_or(Path::new("/")))
}

/// Whether `path` belongs to this user or root and nobody else may write it.
fn only_its_owner_writes(what: &str, path: &Path) -> Result<(), String> {
    use std::os::unix::fs::MetadataExt as _;
    let metadata = std::fs::metadata(path)
        .map_err(|error| format!("{what} `{}` cannot be examined: {error}", path.display()))?;
    if metadata.uid() != 0 && metadata.uid() != nix::unistd::geteuid().as_raw() {
        return Err(format!(
            "{what} `{}` belongs to uid {}, neither this user nor root",
            path.display(),
            metadata.uid()
        ));
    }
    if metadata.mode() & 0o022 != 0 {
        return Err(format!(
            "{what} `{}` is writable by users other than its owner (mode {:o})",
            path.display(),
            metadata.mode() & 0o7777
        ));
    }
    Ok(())
}

/// Maps a compiled artifact into the engine.
#[allow(
    unsafe_code,
    reason = "wasmtime's only way to load a precompiled component is `unsafe` (ADR-0870)"
)]
fn map(engine: &wasmtime::Engine, artifact: &Path) -> wasmtime::Result<Component> {
    // SAFETY: `deserialize_file` trusts the file to be an artifact wasmtime itself wrote, because
    // what it maps is executed as native code. That holds here by construction and by check:
    // the only writer of a store is `kuang-compile`, which runs this crate's own engine
    // configuration; `trusted` has just refused any artifact or store that anyone but this user
    // or root could have written, and artifacts never come from a package (ADR-0870). Before it
    // maps a byte, wasmtime itself refuses a file that is not an ELF artifact of its own, or was
    // written by another engine version, for another architecture or operating system, or under
    // other compilation settings — which is how a stale, foreign or damaged artifact ends as a
    // refusal rather than as a crash. The file is not modified while mapped: the tool replaces an
    // artifact by renaming a new file over it, which leaves an existing mapping intact.
    unsafe { Component::deserialize_file(engine, artifact) }
}

/// Compiles the component at `component` into `store`, and returns the artifact's path.
///
/// The store is created owner-writable only, and the artifact is written beside its final name
/// and renamed into place, so a reader sees the previous artifact or the new one and never a
/// partial file. Compiling the same bytes again replaces the artifact, which is what makes the
/// step idempotent after a shell upgrade.
///
/// # Errors
///
/// The reason, in words, when the component cannot be read or compiled or the store written.
#[cfg(feature = "compiler")]
pub fn compile(component: &Path, store: &Path) -> Result<PathBuf, String> {
    use std::io::Write as _;
    use std::os::unix::fs::{DirBuilderExt as _, OpenOptionsExt as _};

    let bytes = std::fs::read(component)
        .map_err(|error| format!("`{}` could not be read: {error}", component.display()))?;
    let engine = crate::wasm::engine()?;
    let compiled = engine.precompile_component(&bytes).map_err(|error| {
        format!(
            "`{}` is not a component this engine can compile: {error:#}",
            component.display()
        )
    })?;
    std::fs::DirBuilder::new()
        .recursive(true)
        .mode(0o755)
        .create(store)
        .map_err(|error| format!("the store `{}` could not be made: {error}", store.display()))?;
    // An artifact in a store others can write is one the shell refuses to map, so writing it
    // would only move the refusal from here to the first load.
    only_its_owner_writes("the store", store)
        .map_err(|why| format!("{why}; the shell does not map artifacts from it"))?;
    let name = artifact_name(&bytes);
    let artifact = store.join(&name);
    let partial = store.join(format!(".{name}.{}.partial", std::process::id()));
    let written = std::fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .mode(0o644)
        .open(&partial)
        .and_then(|mut file| {
            file.write_all(&compiled)?;
            file.sync_all()
        })
        .and_then(|()| std::fs::rename(&partial, &artifact));
    if let Err(error) = written {
        let _ = std::fs::remove_file(&partial);
        return Err(format!(
            "the artifact `{}` could not be written: {error}",
            artifact.display()
        ));
    }
    Ok(artifact)
}

#[cfg(all(test, feature = "compiler"))]
mod portable {
    #![allow(
        clippy::expect_used,
        reason = "AGENTS.md §16: a test states its preconditions directly"
    )]

    /// The smallest component the engine accepts: a preamble and nothing else.
    const EMPTY_COMPONENT: &[u8] = b"\0asm\x0d\x00\x01\x00";

    #[test]
    fn should_write_an_artifact_that_loads_on_a_machine_of_the_same_architecture_without_optional_cpu_features()
     {
        // An artifact is written where the package is installed, and an image, a fleet or a
        // system store carries it to other machines of the same architecture. One compiled for
        // the CPU that happened to run the compiler (AVX-512 on a CI runner) is refused on every
        // older one, so the compile step targets the architecture, not the machine.
        let home = ono_testkit::scratch();
        let component = home.path().join("empty.wasm");
        std::fs::write(&component, EMPTY_COMPONENT).expect("the component");
        let store = home.path().join("store");
        let artifact = super::compile(&component, &store).expect("the tool compiles it");

        let mut config = wasmtime::Config::new();
        config.wasm_component_model(true).epoch_interruption(true);
        // This engine's own compiler must not infer the machine it runs on either, or it would
        // refuse itself on the simulated host before it is asked about the artifact.
        config
            .target(&target_lexicon::Triple::host().to_string())
            .expect("the host triple");
        #[allow(
            unsafe_code,
            reason = "the host a portable artifact has to load on is simulated"
        )]
        // SAFETY: the detector answers from no state; it claims a CPU with no optional feature,
        // which only makes the engine refuse more, never map code the host cannot run.
        unsafe {
            config.detect_host_feature(|_| Some(false));
        }
        let baseline = wasmtime::Engine::new(&config).expect("a baseline engine");
        #[allow(unsafe_code, reason = "the load under test is the shell's own mapping")]
        // SAFETY: the artifact was written by `compile` above into a scratch store only this
        // test writes (ADR-0870).
        let loaded =
            unsafe { wasmtime::component::Component::deserialize_file(&baseline, &artifact) };
        assert!(
            loaded.is_ok(),
            "a machine of this architecture without optional CPU features loads the artifact: {:#}",
            loaded
                .err()
                .map(|error| format!("{error:#}"))
                .unwrap_or_default()
        );
    }
}
