//! Compiled components (ADR-0870): the shell carries the WebAssembly runtime and no compiler.
//!
//! A `wasm-component` package ships `runtime/component.wasm` (spec §31.36), and that stays the
//! package format. What runs is the engine's own compiled form of it, written once by
//! `kuang-compile` — the SDK's tool, which `install plugin` runs — into an artifact store, and
//! loaded here by mapping it. The shell links no code generator, so a component nobody compiled
//! is refused with the command that compiles it rather than compiled on the spot.
//!
//! An artifact is named by the SHA-256 of the component it was compiled from, so it belongs to
//! exactly those bytes: a package upgrade that changes the component finds no artifact, and a
//! shell upgrade that changes the engine finds one the engine refuses. Artifacts never live in
//! the package directory. A package is somebody else's bytes; a compiled artifact is native code
//! the shell maps into itself, and one that could arrive inside a package would be a way around
//! every confinement the runtime gives.

use std::ffi::OsStr;
use std::io::{ErrorKind, Read as _};
use std::os::fd::OwnedFd;
use std::path::{Path, PathBuf};

use ono_kuang_protocol::{KuangError, KuangErrorCode};
use rustix::fs::{AtFlags, FileType, Mode, OFlags};
use rustix::io::Errno;
use serde_json::json;
use wasmtime::component::Component;

/// The tool that writes an artifact, as the refusal names it.
pub const COMPILE_TOOL: &str = "kuang-compile";

/// The store whoever administers the system writes: an image build, or a distribution package.
pub const SYSTEM_STORE: &str = "/usr/lib/ono-sendai/kuang-compiled";

/// The operator's own store: `$XDG_CACHE_HOME/ono/kuang/compiled`, or `~/.cache/ono/...`.
///
/// A cache in the XDG sense: everything in it is derived from a component and regenerated by one
/// command. `None` when the environment names no absolute home at all.
#[must_use]
pub fn user_store() -> Option<PathBuf> {
    let absolute = |name: &str| {
        std::env::var_os(name)
            .map(PathBuf::from)
            .filter(|path| path.is_absolute())
    };
    let cache =
        absolute("XDG_CACHE_HOME").or_else(|| absolute("HOME").map(|home| home.join(".cache")))?;
    Some(cache.join("ono").join("kuang").join("compiled"))
}

/// Where a component's artifact is looked for, in order: the operator's store, then the system's.
#[must_use]
pub fn stores() -> Vec<PathBuf> {
    user_store()
        .into_iter()
        .chain(std::iter::once(PathBuf::from(SYSTEM_STORE)))
        .collect()
}

/// The file name of the artifact compiled from `component`: its SHA-256, and `.cwasm`.
#[must_use]
pub fn artifact_name(component: &[u8]) -> String {
    use sha2::Digest as _;
    let digest = sha2::Sha256::digest(component);
    let mut name = String::with_capacity(70);
    for byte in digest {
        name.push_str(&format!("{byte:02x}"));
    }
    name.push_str(".cwasm");
    name
}

/// The engine the artifact has to come from, as the refusal names it: the exact wasmtime release
/// whose version is stamped into every artifact and checked on every load (ADR-0916), and the
/// architecture it compiles for.
#[must_use]
pub fn engine_identity() -> String {
    format!(
        "wasmtime {} on {}",
        crate::wasm::WASMTIME_VERSION,
        std::env::consts::ARCH
    )
}

/// Why no artifact could be loaded, as `load.component_not_compiled`'s `reason` spells it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Reason {
    /// No store holds an artifact for these bytes.
    Missing,
    /// An artifact is there and the engine refuses it: another engine version, another
    /// architecture, or bytes that are not an artifact at all.
    Incompatible,
    /// An artifact is there and someone other than its owner or root could have written it.
    Untrusted,
    /// The artifact, its store or a directory above them could not be examined or read:
    /// permission denied, or another error of the system's own. Nothing is mapped, and the
    /// compile step alone does not fix it.
    Unreadable,
}

impl Reason {
    /// The word the error metadata carries.
    #[must_use]
    pub const fn word(self) -> &'static str {
        match self {
            Self::Missing => "missing",
            Self::Incompatible => "incompatible",
            Self::Untrusted => "untrusted",
            Self::Unreadable => "unreadable",
        }
    }
}

/// What the lookup found instead of a loadable artifact.
#[derive(Debug, Clone)]
pub struct NotCompiled {
    reason: Reason,
    artifact: PathBuf,
    detail: String,
}

impl NotCompiled {
    /// Why.
    #[must_use]
    pub const fn reason(&self) -> Reason {
        self.reason
    }

    /// The structured refusal for `package`, whose component is `component`.
    #[must_use]
    pub fn into_error(self, package: &str, component: &Path) -> KuangError {
        let command = format!("{COMPILE_TOOL} {}", component.display());
        let what = match self.reason {
            Reason::Missing => "has not been compiled for this shell".to_owned(),
            Reason::Incompatible => format!(
                "has a compiled artifact this shell's engine ({}) refuses: {}",
                engine_identity(),
                self.detail
            ),
            Reason::Untrusted => format!(
                "has a compiled artifact the shell will not map: {}",
                self.detail
            ),
            Reason::Unreadable => format!(
                "may have a compiled artifact the shell cannot read: {}",
                self.detail
            ),
        };
        let remedy = match self.reason {
            Reason::Untrusted => format!(
                "the artifact `{}`, its store and every directory above them must be real \
                 directories and files that only this user or root can change; correct what this \
                 names or remove the artifact, then run `{command}`",
                self.artifact.display()
            ),
            Reason::Unreadable => format!(
                "make the artifact `{}`, its store and the directories above them readable by \
                 this user, or remove the artifact, then run `{command}`",
                self.artifact.display()
            ),
            Reason::Missing | Reason::Incompatible => format!("run `{command}`"),
        };
        KuangError::new(
            KuangErrorCode::LoadComponentNotCompiled,
            format!(
                "the component of `{package}` ({}) {what}; {remedy}",
                component.display()
            ),
        )
        .with_help(format!(
            "`{COMPILE_TOOL}` compiles a component once, for this engine release and this \
             architecture (ADR-0914, ADR-0916); `install plugin` runs it, and an engine upgrade \
             or a changed component needs it again"
        ))
        .with_metadata("reason", json!(self.reason.word()))
        .with_metadata("component", json!(component.display().to_string()))
        .with_metadata("artifact", json!(self.artifact.display().to_string()))
        .with_metadata("engine", json!(engine_identity()))
        .with_metadata("command", json!(command))
    }
}

/// Why a component could not be loaded at all.
#[derive(Debug)]
pub enum LoadFailure {
    /// No artifact this engine may load: the refusal that names the compile step.
    NotCompiled(NotCompiled),
    /// The component itself could not be read.
    Unreadable(String),
}

/// The component at `component`, from the first store in `stores` holding a loadable artifact
/// for its bytes.
///
/// A store whose artifact is refused does not end the search: a stale artifact in the operator's
/// store must not hide a current one the system provides. When none loads, the first refusal is
/// the answer, and `missing` only when no store had an artifact at all.
pub(crate) fn load(
    engine: &wasmtime::Engine,
    component: &Path,
    stores: &[PathBuf],
) -> Result<Component, LoadFailure> {
    let bytes = std::fs::read(component).map_err(|error| {
        LoadFailure::Unreadable(format!(
            "`{}` could not be read: {error}",
            component.display()
        ))
    })?;
    let name = artifact_name(&bytes);
    let mut first_refusal = None;
    for store in stores {
        let artifact = store.join(&name);
        let opened = open_store(store, false)
            .and_then(|directory| open_artifact(&directory, &name, &artifact));
        let refusal = match opened {
            Err(Refusal::Absent) => continue,
            Err(Refusal::Refused(reason, detail)) => NotCompiled {
                reason,
                artifact: artifact.clone(),
                detail,
            },
            Ok(file) => match read_and_map(engine, file, &artifact) {
                Ok(component) => return Ok(component),
                Err(Refusal::Absent) => continue,
                Err(Refusal::Refused(reason, detail)) => NotCompiled {
                    reason,
                    artifact: artifact.clone(),
                    detail,
                },
            },
        };
        first_refusal.get_or_insert(refusal);
    }
    Err(LoadFailure::NotCompiled(first_refusal.unwrap_or_else(
        || {
            NotCompiled {
                reason: Reason::Missing,
                artifact: stores
                    .first()
                    .map_or_else(|| PathBuf::from(&name), |store| store.join(&name)),
                detail: String::new(),
            }
        },
    )))
}

/// Why the way to an artifact ended before a file was open.
#[derive(Debug)]
enum Refusal {
    /// Nothing is there: the store, or the artifact in it, does not exist.
    Absent,
    /// Something is there and is refused, for the reason given and in the words given.
    Refused(Reason, String),
}

/// The store at `store`, opened by a walk from `/` that follows no symbolic link and examines
/// every directory it passes (ADR-0915); with `create`, the directories that do not exist yet are
/// made on the way, `0755`.
///
/// Whoever may write a directory above the store may rename the store away and put their own in
/// its place, owner, mode and all, so the rule of ADR-0870 §4 holds for every one of them: it
/// belongs to this user or to root, and nobody else may write it — except a root-owned sticky
/// directory like `/tmp`, where nobody may rename or remove what is not theirs, and a directory
/// whose group is the private group of this user, which is this user. The directories above the
/// store are the operator's layout and may be reached through links (`/home` → `/var/home`):
/// they are resolved first, and the walk then examines the directories they resolve to. The
/// store itself is the tool's own directory and is never a link.
///
/// Each step opens the next directory relative to the descriptor of the one before, which is the
/// one that was examined: a directory swapped for another after its parent was examined is
/// either the one examined next, or a link the walk refuses.
fn open_store(store: &Path, create: bool) -> Result<OwnedFd, Refusal> {
    let euid = nix::unistd::geteuid().as_raw();
    let store = std::path::absolute(store).map_err(|error| unexpected(store, &error))?;
    let (Some(parent), Some(leaf)) = (store.parent(), store.file_name()) else {
        return Err(Refusal::Refused(
            Reason::Untrusted,
            format!("`{}` names no directory a store can be", store.display()),
        ));
    };
    let (existing, missing) = resolve_existing(parent)?;
    if !missing.is_empty() && !create {
        return Err(Refusal::Absent);
    }
    let mut directory = rustix::fs::openat(
        rustix::fs::CWD,
        "/",
        OFlags::RDONLY | OFlags::DIRECTORY | OFlags::CLOEXEC,
        Mode::empty(),
    )
    .map_err(|error| unexpected(Path::new("/"), &error.into()))?;
    let mut path = PathBuf::from("/");
    examine_ancestor(&directory, &path, euid)?;
    for name in existing.components().filter_map(|part| match part {
        std::path::Component::Normal(name) => Some(name),
        _ => None,
    }) {
        path.push(name);
        directory = open_directory(&directory, name, &path)?;
        examine_ancestor(&directory, &path, euid)?;
    }
    for name in &missing {
        path.push(name);
        make_directory(&directory, name, &path)?;
        directory = open_directory(&directory, name, &path)?;
        examine_ancestor(&directory, &path, euid)?;
    }
    if create {
        make_directory(&directory, leaf, &store)?;
    }
    let opened = open_directory(&directory, leaf, &store)?;
    let stat = rustix::fs::fstat(&opened).map_err(|error| unexpected(&store, &error.into()))?;
    ownership("its store", &store, Examined::of(&stat), euid)
        .map_err(|detail| Refusal::Refused(Reason::Untrusted, detail))?;
    Ok(opened)
}

/// The deepest existing directory at or above `parent`, with its links resolved, and the names
/// below it that do not exist yet.
fn resolve_existing(parent: &Path) -> Result<(PathBuf, Vec<std::ffi::OsString>), Refusal> {
    for candidate in parent.ancestors() {
        match std::fs::canonicalize(candidate) {
            Ok(resolved) => {
                let mut missing = Vec::new();
                for part in parent
                    .strip_prefix(candidate)
                    .unwrap_or(Path::new(""))
                    .components()
                {
                    match part {
                        std::path::Component::Normal(name) => missing.push(name.to_owned()),
                        _ => {
                            return Err(Refusal::Refused(
                                Reason::Untrusted,
                                format!(
                                    "`{}` climbs out of a directory that does not exist",
                                    parent.display()
                                ),
                            ));
                        }
                    }
                }
                return Ok((resolved, missing));
            }
            Err(error)
                if matches!(error.kind(), ErrorKind::NotFound | ErrorKind::NotADirectory) => {}
            Err(error) => return Err(unexpected(candidate, &error)),
        }
    }
    Err(Refusal::Absent)
}

/// `name` below `parent`, a directory, opened without following a link. A directory this user
/// may search but not read is opened as a path, which is all the walk needs of it.
fn open_directory(parent: &OwnedFd, name: &OsStr, path: &Path) -> Result<OwnedFd, Refusal> {
    let flags = OFlags::DIRECTORY | OFlags::NOFOLLOW | OFlags::CLOEXEC;
    let opened = match rustix::fs::openat(parent, name, flags | OFlags::RDONLY, Mode::empty()) {
        Err(Errno::ACCESS) => rustix::fs::openat(parent, name, flags | OFlags::PATH, Mode::empty()),
        other => other,
    };
    opened.map_err(|error| match error {
        Errno::LOOP => symbolic_link(path),
        Errno::NOENT => Refusal::Absent,
        Errno::NOTDIR => match rustix::fs::statat(parent, name, AtFlags::SYMLINK_NOFOLLOW) {
            Ok(stat) if FileType::from_raw_mode(stat.st_mode) == FileType::Symlink => {
                symbolic_link(path)
            }
            _ => Refusal::Absent,
        },
        other => unexpected(path, &other.into()),
    })
}

/// Makes `name` below `parent`, unless it is there already.
fn make_directory(parent: &OwnedFd, name: &OsStr, path: &Path) -> Result<(), Refusal> {
    match rustix::fs::mkdirat(parent, name, Mode::from_raw_mode(0o755)) {
        Ok(()) | Err(Errno::EXIST) => Ok(()),
        Err(error) => Err(Refusal::Refused(
            Reason::Unreadable,
            format!(
                "the store `{}` could not be made: {}",
                path.display(),
                std::io::Error::from(error)
            ),
        )),
    }
}

/// The refusal of a link on the way to an artifact.
fn symbolic_link(path: &Path) -> Refusal {
    Refusal::Refused(
        Reason::Untrusted,
        format!(
            "`{}` is a symbolic link, and the way to an artifact follows none",
            path.display()
        ),
    )
}

/// An error on the way to an artifact that is neither absence nor a refusal of its own: the
/// system would not let this user examine or read it.
fn unexpected(path: &Path, error: &std::io::Error) -> Refusal {
    Refusal::Refused(
        Reason::Unreadable,
        format!("`{}` cannot be examined: {error}", path.display()),
    )
}

/// The ownership rule for a directory above the store, on the directory `directory` is open on.
fn examine_ancestor(directory: &OwnedFd, path: &Path, euid: u32) -> Result<(), Refusal> {
    let stat = rustix::fs::fstat(directory).map_err(|error| unexpected(path, &error.into()))?;
    ancestor_ownership(path, Examined::of(&stat), euid, || {
        private_group(directory, stat.st_uid, stat.st_gid)
    })
    .map_err(|detail| Refusal::Refused(Reason::Untrusted, detail))
}

/// Whether `gid` is the private group of the user `uid`: named like that user, that user's
/// primary group, and listing no other member — the group a `USERGROUPS` system (umask `002`)
/// gives every user, and so that user. An access ACL on the directory could grant others write
/// behind the group bits, so a directory carrying one is not treated this way.
fn private_group(directory: &OwnedFd, uid: u32, gid: u32) -> bool {
    use nix::unistd::{Gid, Group, Uid, User};
    let (Ok(Some(user)), Ok(Some(group))) = (
        User::from_uid(Uid::from_raw(uid)),
        Group::from_gid(Gid::from_raw(gid)),
    ) else {
        return false;
    };
    if group.name != user.name
        || user.gid.as_raw() != gid
        || group.mem.iter().any(|member| *member != user.name)
    {
        return false;
    }
    let mut nothing: [u8; 0] = [];
    matches!(
        rustix::fs::fgetxattr(directory, "system.posix_acl_access", &mut nothing[..]),
        Err(Errno::NODATA | Errno::NOTSUP)
    )
}

/// The artifact `name` in the store `store` is open on, opened without following a link and
/// examined through the descriptor that will be read.
fn open_artifact(store: &OwnedFd, name: &str, artifact: &Path) -> Result<std::fs::File, Refusal> {
    let opened = rustix::fs::openat(
        store,
        name,
        OFlags::RDONLY | OFlags::NOFOLLOW | OFlags::CLOEXEC | OFlags::NONBLOCK,
        Mode::empty(),
    )
    .map_err(|error| match error {
        Errno::LOOP => symbolic_link(artifact),
        Errno::NOENT => Refusal::Absent,
        other => unexpected(artifact, &other.into()),
    })?;
    let stat = rustix::fs::fstat(&opened).map_err(|error| unexpected(artifact, &error.into()))?;
    if FileType::from_raw_mode(stat.st_mode) != FileType::RegularFile {
        return Err(Refusal::Refused(
            Reason::Incompatible,
            format!("`{}` is not a regular file", artifact.display()),
        ));
    }
    ownership(
        "the artifact",
        artifact,
        Examined::of(&stat),
        nix::unistd::geteuid().as_raw(),
    )
    .map_err(|detail| Refusal::Refused(Reason::Untrusted, detail))?;
    Ok(std::fs::File::from(opened))
}

/// Reads the artifact from the descriptor that was examined, and hands the bytes to the engine.
fn read_and_map(
    engine: &wasmtime::Engine,
    mut file: std::fs::File,
    artifact: &Path,
) -> Result<Component, Refusal> {
    let mut bytes = Vec::new();
    file.read_to_end(&mut bytes)
        .map_err(|error| unexpected(artifact, &error))?;
    map(engine, &bytes)
        .map_err(|error| Refusal::Refused(Reason::Incompatible, format!("{error:#}")))
}

/// What the ownership rule reads of a file: who owns it, and its mode.
#[derive(Debug, Clone, Copy)]
struct Examined {
    uid: u32,
    mode: u32,
}

impl Examined {
    fn of(stat: &rustix::fs::Stat) -> Self {
        Self {
            uid: stat.st_uid,
            mode: stat.st_mode,
        }
    }
}

/// The ownership rule for the artifact and its store, apart from the system it reads: `examined`
/// belongs to `euid` or to root, and nobody else may write it (ADR-0870 §4).
fn ownership(what: &str, path: &Path, examined: Examined, euid: u32) -> Result<(), String> {
    if examined.uid != 0 && examined.uid != euid {
        return Err(format!(
            "{what} `{}` belongs to uid {}, neither this user nor root",
            path.display(),
            examined.uid
        ));
    }
    if examined.mode & 0o022 != 0 {
        return Err(format!(
            "{what} `{}` is writable by users other than its owner (mode {:o})",
            path.display(),
            examined.mode & 0o7777
        ));
    }
    Ok(())
}

/// The ownership rule for a directory above the store (ADR-0915): what [`ownership`] asks, except
/// that a root-owned sticky directory may be writable by all, and a directory of this user's may
/// be writable by its group when `private_group` says the group is this user's own.
fn ancestor_ownership(
    path: &Path,
    examined: Examined,
    euid: u32,
    private_group: impl FnOnce() -> bool,
) -> Result<(), String> {
    let refused = ownership("the directory", path, examined, euid);
    if refused.is_ok() || (examined.uid != 0 && examined.uid != euid) {
        return refused;
    }
    // Everybody may add to `/tmp`, and nobody may rename or remove what is not theirs.
    let sticky_of_root = examined.uid == 0 && examined.mode & 0o1000 != 0;
    let group_is_the_owner = examined.mode & 0o002 == 0 && examined.uid == euid && private_group();
    if sticky_of_root || group_is_the_owner {
        Ok(())
    } else {
        refused
    }
}

/// Loads compiled artifact bytes into the engine.
#[allow(
    unsafe_code,
    reason = "wasmtime's only way to load a precompiled component is `unsafe` (ADR-0870)"
)]
fn map(engine: &wasmtime::Engine, artifact: &[u8]) -> wasmtime::Result<Component> {
    // SAFETY: `deserialize` trusts the bytes to be an artifact wasmtime itself wrote, because
    // what it loads is executed as native code. That holds here by construction and by check
    // (ADR-0870, ADR-0915): the only writer of a store is `kuang-compile`, which runs this
    // crate's own engine configuration, and artifacts never come from a package. The bytes were
    // read from the one descriptor `open_artifact` opened without following a link and examined
    // with `fstat` — a regular file owned by this user or root that nobody else may write — in a
    // store and below directories `open_store` reached the same way and held to the same rule,
    // so no path is looked up again between the check and the read. They are a private copy:
    // what is on disk may change afterwards without changing what runs. Before it loads a byte,
    // wasmtime itself refuses bytes that are not an ELF artifact of its own, or were written by
    // another engine version, for another architecture or operating system, or under other
    // compilation settings — which is how a stale, foreign or damaged artifact ends as a refusal
    // rather than as a crash.
    unsafe { Component::deserialize(engine, artifact) }
}

/// Compiles the component at `component` into `store`, and returns the artifact's path.
///
/// The store is reached the way the shell reaches it, made `0755` where it is missing, and
/// refused where the shell would refuse it (ADR-0915): a link on the way, or a directory someone
/// other than this user or root could write. The artifact is written beside its final name in
/// that directory and renamed into place, so a reader sees the previous artifact or the new one
/// and never a partial file. Compiling the same bytes again replaces the artifact, which is what
/// makes the step idempotent after a shell upgrade.
///
/// # Errors
///
/// The reason, in words, when the component cannot be read or compiled or the store written.
#[cfg(feature = "compiler")]
pub fn compile(component: &Path, store: &Path) -> Result<PathBuf, String> {
    use std::io::Write as _;

    let bytes = std::fs::read(component)
        .map_err(|error| format!("`{}` could not be read: {error}", component.display()))?;
    let engine = crate::wasm::engine()?;
    let compiled = engine.precompile_component(&bytes).map_err(|error| {
        format!(
            "`{}` is not a component this engine can compile: {error:#}",
            component.display()
        )
    })?;
    // An artifact in a store the shell refuses is one it will not map, so writing it would only
    // move the refusal from here to the first load.
    let directory = open_store(store, true).map_err(|refusal| match refusal {
        Refusal::Absent => format!("the store `{}` could not be made", store.display()),
        Refusal::Refused(_, why) => format!("{why}; the shell does not map artifacts from it"),
    })?;
    let name = artifact_name(&bytes);
    let artifact = store.join(&name);
    let partial = format!(".{name}.{}.partial", std::process::id());
    let written = (|| -> std::io::Result<()> {
        let opened = rustix::fs::openat(
            &directory,
            partial.as_str(),
            OFlags::WRONLY | OFlags::CREATE | OFlags::EXCL | OFlags::NOFOLLOW | OFlags::CLOEXEC,
            Mode::from_raw_mode(0o644),
        )?;
        let mut file = std::fs::File::from(opened);
        file.write_all(&compiled)?;
        file.sync_all()?;
        rustix::fs::renameat(&directory, partial.as_str(), &directory, name.as_str())?;
        Ok(())
    })();
    if let Err(error) = written {
        let _ = rustix::fs::unlinkat(&directory, partial.as_str(), AtFlags::empty());
        return Err(format!(
            "the artifact `{}` could not be written: {error}",
            artifact.display()
        ));
    }
    Ok(artifact)
}

#[cfg(test)]
mod ownership_rule {
    use std::path::Path;

    use super::{Examined, ancestor_ownership, ownership};

    const ME: u32 = 1000;

    fn verdict(uid: u32, mode: u32) -> Result<(), String> {
        ownership(
            "the artifact",
            Path::new("/s/a.cwasm"),
            Examined { uid, mode },
            ME,
        )
    }

    #[test]
    fn should_accept_what_this_user_or_root_owns_and_only_its_owner_writes() {
        assert_eq!(verdict(ME, 0o100_644), Ok(()));
        assert_eq!(verdict(0, 0o100_644), Ok(()));
        assert_eq!(verdict(ME, 0o040_755), Ok(()));
    }

    #[test]
    fn should_refuse_what_another_user_owns_whatever_its_mode() {
        // A file another user owns is one that user can rewrite, and chmod back, at will: its
        // mode says nothing about who wrote the bytes.
        let refused = verdict(1001, 0o100_644).expect_err("another user's artifact");
        assert!(
            refused.contains("belongs to uid 1001, neither this user nor root")
                && refused.contains("/s/a.cwasm"),
            "{refused:?}"
        );
    }

    #[test]
    fn should_refuse_what_others_may_write_though_this_user_owns_it() {
        for mode in [0o100_664, 0o100_646, 0o100_666] {
            let refused = verdict(ME, mode).expect_err("a writable artifact");
            assert!(
                refused.contains("writable by users other than its owner"),
                "{mode:o}: {refused:?}"
            );
        }
    }

    fn above(uid: u32, mode: u32, private: bool) -> Result<(), String> {
        ancestor_ownership(Path::new("/s"), Examined { uid, mode }, ME, || private)
    }

    #[test]
    fn should_accept_a_directory_above_the_store_only_this_user_or_root_can_change() {
        assert_eq!(above(0, 0o040_755, false), Ok(()));
        assert_eq!(above(ME, 0o040_700, false), Ok(()));
        // `/tmp`: everybody may add, nobody may rename or remove what is not theirs.
        assert_eq!(above(0, 0o041_777, false), Ok(()));
        // A group only its owner belongs to is the owner: a USERGROUPS system's umask 002.
        assert_eq!(above(ME, 0o040_775, true), Ok(()));
    }

    #[test]
    fn should_refuse_a_directory_above_the_store_others_can_change() {
        for (uid, mode, private, why) in [
            (
                ME,
                0o040_775,
                false,
                "writable by users other than its owner",
            ),
            (
                ME,
                0o040_777,
                true,
                "writable by users other than its owner",
            ),
            // Sticky protects entries from other users only when its owner is trusted anyway,
            // and it is not this user's own `/tmp` the rule exempts.
            (
                ME,
                0o041_777,
                false,
                "writable by users other than its owner",
            ),
            (
                0,
                0o040_777,
                false,
                "writable by users other than its owner",
            ),
            (0, 0o040_775, true, "writable by users other than its owner"),
            (
                1001,
                0o040_755,
                false,
                "belongs to uid 1001, neither this user nor root",
            ),
            (
                1001,
                0o041_777,
                false,
                "belongs to uid 1001, neither this user nor root",
            ),
        ] {
            let refused = above(uid, mode, private).expect_err(why);
            assert!(
                refused.contains(why) && refused.contains("`/s`"),
                "uid {uid}, mode {mode:o}: {refused:?}"
            );
        }
    }

    #[test]
    fn should_refuse_a_users_tree_to_root() {
        // `sudo -E ono`: root with a user's HOME. The user's directories are not root's, and
        // root must not map, or write, what that user could have put there.
        let refused = ancestor_ownership(
            Path::new("/home/someone"),
            Examined {
                uid: ME,
                mode: 0o040_755,
            },
            0,
            || true,
        )
        .expect_err("the user's home, to root");
        assert!(refused.contains("belongs to uid 1000"), "{refused:?}");
    }
}

#[cfg(all(test, feature = "compiler"))]
mod descriptor {
    #![allow(
        clippy::expect_used,
        reason = "AGENTS.md §16: a test states its preconditions directly"
    )]

    /// The smallest component the engine accepts: a preamble and nothing else.
    const EMPTY_COMPONENT: &[u8] = b"\0asm\x0d\x00\x01\x00";

    #[test]
    fn should_load_the_file_it_examined_though_its_name_is_replaced_before_the_read() {
        // The window a check by path leaves open: the file examined and the file loaded are
        // looked up separately. The loader examines and reads one descriptor, so replacing the
        // name between the two changes nothing that runs; that a lookup by name now finds the
        // replacement shows what would have been loaded otherwise.
        let home = ono_testkit::scratch();
        let component = home.path().join("empty.wasm");
        std::fs::write(&component, EMPTY_COMPONENT).expect("the component");
        let store = home.path().join("store");
        let artifact = super::compile(&component, &store).expect("the tool compiles it");
        let name = super::artifact_name(EMPTY_COMPONENT);

        let directory = super::open_store(&store, false).expect("the store is trusted");
        let file = super::open_artifact(&directory, &name, &artifact).expect("the artifact is");
        let impostor = store.join("impostor");
        std::fs::write(&impostor, b"not an artifact").expect("another file");
        std::fs::rename(&impostor, &artifact).expect("swapped in under the name");

        let engine = crate::wasm::engine().expect("the engine");
        assert!(
            super::read_and_map(engine, file, &artifact).is_ok(),
            "what was examined is what is loaded"
        );
        assert!(
            super::load(engine, &component, std::slice::from_ref(&store)).is_err(),
            "and a lookup by name meets the impostor"
        );
    }
}

#[cfg(test)]
mod engine_version {
    #![allow(
        clippy::expect_used,
        reason = "AGENTS.md §16: a test states its preconditions directly"
    )]

    /// The version of wasmtime `Cargo.lock` resolves.
    fn locked_wasmtime() -> String {
        let lock = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../Cargo.lock"),
        )
        .expect("the workspace's lock file");
        let at = lock
            .find("\nname = \"wasmtime\"\nversion = \"")
            .expect("wasmtime is locked");
        let rest = &lock[at + "\nname = \"wasmtime\"\nversion = \"".len()..];
        rest[..rest.find('"').expect("a quoted version")].to_owned()
    }

    #[test]
    fn should_name_the_exact_wasmtime_release_the_lock_file_resolves() {
        // An artifact is keyed on the exact release (ADR-0916); a bump of wasmtime that forgot
        // the key would let the new engine map what the old one's compiler wrote.
        let locked = locked_wasmtime();
        assert_eq!(crate::wasm::WASMTIME_VERSION, locked);
        assert_eq!(
            super::engine_identity(),
            format!("wasmtime {locked} on {}", std::env::consts::ARCH)
        );
    }
}

#[cfg(all(test, feature = "compiler"))]
mod patch_release {
    #![allow(
        clippy::expect_used,
        reason = "AGENTS.md §16: a test states its preconditions directly"
    )]

    const EMPTY_COMPONENT: &[u8] = b"\0asm\x0d\x00\x01\x00";

    #[test]
    fn should_refuse_an_artifact_stamped_with_the_major_version_alone() {
        // wasmtime's default stamps an artifact with its major version only, so what another
        // 47.x release compiled — before or after a Cranelift fix — would pass for this one's.
        // Such an artifact is what this engine is configured to refuse.
        let mut config = wasmtime::Config::new();
        config.wasm_component_model(true).epoch_interruption(true);
        config
            .target(&target_lexicon::Triple::host().to_string())
            .expect("the host triple");
        config
            .module_version(wasmtime::ModuleVersionStrategy::WasmtimeVersion)
            .expect("the default strategy");
        let other_patch = wasmtime::Engine::new(&config).expect("an engine of the same major");
        let bytes = other_patch
            .precompile_component(EMPTY_COMPONENT)
            .expect("compiled");

        let home = ono_testkit::scratch();
        let component = home.path().join("empty.wasm");
        std::fs::write(&component, EMPTY_COMPONENT).expect("the component");
        let store = home.path().join("store");
        std::fs::create_dir(&store).expect("the store");
        let artifact = store.join(super::artifact_name(EMPTY_COMPONENT));
        std::fs::write(&artifact, &bytes).expect("the artifact");
        // Owned and moded as `kuang-compile` leaves them, whatever this run's umask.
        for (path, mode) in [(&store, 0o755), (&artifact, 0o644)] {
            std::fs::set_permissions(path, std::os::unix::fs::PermissionsExt::from_mode(mode))
                .expect("owner-only");
        }

        let engine = crate::wasm::engine().expect("the engine");
        match super::load(engine, &component, std::slice::from_ref(&store)) {
            Ok(_) => panic!("an artifact carrying only the major version was mapped"),
            Err(super::LoadFailure::NotCompiled(refusal)) => {
                assert_eq!(refusal.reason(), super::Reason::Incompatible);
            }
            Err(super::LoadFailure::Unreadable(why)) => panic!("{why}"),
        }
    }
}

#[cfg(all(test, feature = "compiler"))]
mod portable {
    #![allow(
        clippy::expect_used,
        reason = "AGENTS.md §16: a test states its preconditions directly"
    )]

    /// The smallest component the engine accepts: a preamble and nothing else.
    const EMPTY_COMPONENT: &[u8] = b"\0asm\x0d\x00\x01\x00";

    #[test]
    fn should_write_an_artifact_that_loads_on_a_machine_of_the_same_architecture_without_optional_cpu_features()
     {
        // An artifact is written where the package is installed, and an image, a fleet or a
        // system store carries it to other machines of the same architecture. One compiled for
        // the CPU that happened to run the compiler (AVX-512 on a CI runner) is refused on every
        // older one, so the compile step targets the architecture, not the machine.
        let home = ono_testkit::scratch();
        let component = home.path().join("empty.wasm");
        std::fs::write(&component, EMPTY_COMPONENT).expect("the component");
        let store = home.path().join("store");
        let artifact = super::compile(&component, &store).expect("the tool compiles it");

        // The shell's own configuration, whose compiler does not infer the machine it runs on
        // either, or it would refuse itself on the simulated host before it is asked about the
        // artifact.
        let mut config = crate::wasm::config().expect("the engine's configuration");
        #[allow(
            unsafe_code,
            reason = "the host a portable artifact has to load on is simulated"
        )]
        // SAFETY: the detector answers from no state; it claims a CPU with no optional feature,
        // which only makes the engine refuse more, never map code the host cannot run.
        unsafe {
            config.detect_host_feature(|_| Some(false));
        }
        let baseline = wasmtime::Engine::new(&config).expect("a baseline engine");
        #[allow(unsafe_code, reason = "the load under test is the shell's own mapping")]
        // SAFETY: the artifact was written by `compile` above into a scratch store only this
        // test writes (ADR-0870).
        let loaded =
            unsafe { wasmtime::component::Component::deserialize_file(&baseline, &artifact) };
        assert!(
            loaded.is_ok(),
            "a machine of this architecture without optional CPU features loads the artifact: {:#}",
            loaded
                .err()
                .map(|error| format!("{error:#}"))
                .unwrap_or_default()
        );
    }
}
