[package]
name = "ono-cli"
description = "The ono shell binary."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "ono"
path = "src/main.rs"

[dependencies]
ono-core.workspace = true
ono-editor.workspace = true
ono-history.workspace = true
ono-parser.workspace = true
ono-process.workspace = true
ono-render.workspace = true
ono-value.workspace = true

[dev-dependencies]
ono-testkit.workspace = true

[lints]
workspace = true
