//! The volatile counts are measured, and the README cannot disagree with them (issue #111,
//! v0.4.1 §50).
//!
//! §50.1 forbids duplicating counts across README and docs "without automated verification", and
//! §50.3 says what the verification is: the README may keep the numbers, and the gate fails when
//! they disagree with generated truth. The exit test for the issue is the last one here — edit a
//! count in the README to a wrong value and the gate goes red.

#![allow(
    clippy::expect_used,
    clippy::unwrap_used,
    clippy::panic,
    reason = "AGENTS.md §16: a test states its preconditions directly"
)]

use ono_testkit::scratch;
use xtask::metrics::{check_readme, measure, write_readme};

mod support;
use support::repo;

#[test]
fn should_compute_every_metric_the_readme_states() {
    // §50.1's five counts, and the two §50.4 adds beside the test figure. Each is asserted as a
    // property of the tree rather than as a number, because the number is what changes daily and
    // the property is what §50 is about.
    let measured = measure(&repo());
    assert!(
        measured.crates >= 20,
        "the workspace has crates under `crates/`, got {}",
        measured.crates
    );
    assert_eq!(
        measured.workspace_members,
        measured.crates + 2,
        "§50.2's `crates` is the library count; the members are those plus `xtask` and `fuzz`, \
         and saying which is which is the difference between a metric and a number"
    );
    assert!(
        measured.tests > 1000,
        "test functions are counted, got {}",
        measured.tests
    );
    assert!(
        measured.acceptance_cases > 100,
        "acceptance cases are counted, got {}",
        measured.acceptance_cases
    );
    assert!(
        measured.adrs > 300,
        "decision records are counted, got {}",
        measured.adrs
    );
    assert!(
        measured.commands > measured.command_contract_files,
        "each contract file declares several commands, got {} in {} files",
        measured.commands,
        measured.command_contract_files
    );

    let rendered = measured.render();
    for key in [
        "crates=",
        "tests=",
        "acceptance_cases=",
        "adrs=",
        "commands=",
    ] {
        assert!(
            rendered.contains(key),
            "§50.2's example output names `{key}`: {rendered}"
        );
    }
}

#[test]
fn should_count_executed_tests_apart_from_skipped_ones() {
    // §50.4: "A README statement such as 'N tests pass' MUST not count skipped cases as proof of
    // execution." A static reading cannot know what a run executed, so the figure is named
    // `tests` for *declared* and two figures beside it carry the skip story — the count that can
    // skip, and the count the canonical CI environment expects to.
    let measured = measure(&repo());
    let rendered = measured.render();
    assert!(
        rendered.contains("tests_that_can_skip=") && rendered.contains("expected_ci_skips="),
        "the skip figures stand beside the test count rather than being folded into it: {rendered}"
    );
    assert!(
        measured.expected_ci_skips <= measured.tests_that_can_skip,
        "a test the canonical environment expects to skip is one that can skip: {} of {}",
        measured.expected_ci_skips,
        measured.tests_that_can_skip
    );
    assert!(
        measured.tests_that_can_skip < measured.tests,
        "most tests cannot skip at all; if every one could, §38.2's preferred count of zero would \
         be meaningless: {} of {}",
        measured.tests_that_can_skip,
        measured.tests
    );
}

#[test]
fn should_find_this_repositorys_readme_in_agreement_with_the_tree() {
    let problems = check_readme(&repo());
    assert!(
        problems.is_empty(),
        "v0.4.1 §50.3: the README's metrics block and the tree disagree:\n{}",
        problems
            .iter()
            .map(|p| format!("  {} — {}", p.location, p.detail))
            .collect::<Vec<_>>()
            .join("\n")
    );
}

#[test]
fn should_fail_when_the_readme_disagrees_with_the_computed_metrics() {
    // The exit test of issue #111, and the whole of §50.3: "the gate MUST fail if the numbers do
    // not match generated truth". A repository with two crates, a README that claims three.
    let repo = scratch();
    repo.write("crates/ono-core/src/lib.rs", "//! one\n");
    repo.write("crates/ono-value/src/lib.rs", "//! two\n");
    repo.write(
        "README.md",
        "# Ono-Sendai\n\n<!-- generated by `cargo xtask metrics`. -->\n\n```text\ncrates=3\n```\n\n<!-- end generated -->\n",
    );
    let problems = check_readme(repo.path());
    assert_eq!(problems.len(), 1, "got {problems:?}");
    assert!(
        problems[0].detail.contains("crates=2"),
        "the problem shows what the tree says, so the correction is a reading rather than an \
         investigation: {}",
        problems[0].detail
    );
    assert!(
        problems[0].detail.contains("cargo xtask metrics --write"),
        "and names the command that fixes it: {}",
        problems[0].detail
    );
}

#[test]
fn should_report_a_readme_that_carries_no_generated_block_at_all() {
    // §50.1 forbids the counts existing without verification. Deleting the block is the easy way
    // to make the check pass, so it is the case the check has to report.
    let repo = scratch();
    repo.write("crates/ono-core/src/lib.rs", "//! one\n");
    repo.write(
        "README.md",
        "# Ono-Sendai\n\nThirty crates, give or take.\n",
    );
    let problems = check_readme(repo.path());
    assert!(
        problems
            .iter()
            .any(|problem| problem.detail.contains("no generated metrics block")),
        "got {problems:?}"
    );
}

#[test]
fn should_rewrite_the_block_and_leave_the_prose_around_it_alone() {
    // §50.3: "The original narrative text around it remains human-owned." A generator that
    // rewrote the paragraph would make the sentence somebody wrote a build artifact.
    let repo = scratch();
    repo.write("crates/ono-core/src/lib.rs", "//! one\n");
    repo.write(
        "README.md",
        "# Ono-Sendai\n\nThe deck is real this time.\n\n<!-- generated by `cargo xtask metrics`. -->\n\n```text\ncrates=99\n```\n\n<!-- end generated -->\n\nAnd the narrative continues.\n",
    );
    assert!(write_readme(repo.path()).expect("the README is rewritten"));
    let text = std::fs::read_to_string(repo.path().join("README.md")).expect("README.md");
    assert!(
        text.contains("The deck is real this time.")
            && text.contains("And the narrative continues."),
        "the human-owned prose survives: {text}"
    );
    assert!(text.contains("crates=1") && !text.contains("crates=99"));
    assert!(
        !write_readme(repo.path()).expect("the second run is a no-op"),
        "a second run changes nothing, so the generator is not a source of diff noise"
    );
    assert_eq!(check_readme(repo.path()), Vec::new());
}

#[test]
fn should_not_count_a_test_written_inside_a_string_literal() {
    // `xtask/tests/scan.rs` holds Rust fixtures inside raw strings, at the left margin, because
    // the scanners it tests read Rust. Counted naively they are about fifteen tests that do not
    // exist, and a count nobody can reproduce is a count nobody believes.
    let repo = scratch();
    repo.write(
        "crates/ono-core/src/lib.rs",
        "#[test]\nfn should_be_counted() {}\n\nconst FIXTURE: &str = r#\"\n#[test]\nfn should_not_be_counted() {}\n\"#;\n",
    );
    assert_eq!(
        measure(repo.path()).tests,
        1,
        "only the real test is counted"
    );
}
