//! The volatile counts are measured, and the README cannot disagree with them (issue #111,
//! v0.4.1 §50).
//!
//! §50.1 forbids duplicating counts across README and docs "without automated verification", and
//! §50.3 says what the verification is: the README may keep the numbers, and the gate fails when
//! they disagree with generated truth. The exit test for the issue is the last one here — edit a
//! count in the README to a wrong value and the gate goes red.

#![allow(
    clippy::expect_used,
    clippy::unwrap_used,
    clippy::panic,
    reason = "AGENTS.md §16: a test states its preconditions directly"
)]

use ono_testkit::scratch;
use xtask::metrics::{check_readme, measure, write_readme};

mod support;
use support::repo;

#[test]
fn should_compute_every_metric_the_readme_states() {
    // §50.1's five counts, and the two §50.4 adds beside the test figure. Each is asserted as a
    // property of the tree rather than as a number, because the number is what changes daily and
    // the property is what §50 is about.
    let measured = measure(&repo());
    assert!(
        measured.crates >= 20,
        "the workspace has crates under `crates/`, got {}",
        measured.crates
    );
    assert_eq!(
        measured.workspace_members,
        measured.crates + 2,
        "§50.2's `crates` is the library count; the members are those plus `xtask` and `fuzz`, \
         and saying which is which is the difference between a metric and a number"
    );
    assert!(
        measured.tests > 1000,
        "test functions are counted, got {}",
        measured.tests
    );
    assert!(
        measured.acceptance_cases > 100,
        "acceptance cases are counted, got {}",
        measured.acceptance_cases
    );
    assert!(
        measured.adrs > 300,
        "decision records are counted, got {}",
        measured.adrs
    );
    assert!(
        measured.commands > measured.command_contract_files,
        "each contract file declares several commands, got {} in {} files",
        measured.commands,
        measured.command_contract_files
    );

    let rendered = measured.render();
    for key in [
        "crates=",
        "tests=",
        "acceptance_cases=",
        "adrs=",
        "commands=",
    ] {
        assert!(
            rendered.contains(key),
            "§50.2's example output names `{key}`: {rendered}"
        );
    }
}

#[test]
fn should_count_executed_tests_apart_from_skipped_ones() {
    // §50.4: "A README statement such as 'N tests pass' MUST not count skipped cases as proof of
    // execution." A static reading cannot know what a run executed, so the figure is named
    // `tests` for *declared* and two figures beside it carry the skip story — the count that can
    // skip, and the count the canonical CI environment expects to.
    let measured = measure(&repo());
    let rendered = measured.render();
    assert!(
        rendered.contains("tests_that_can_skip=") && rendered.contains("expected_ci_skips="),
        "the skip figures stand beside the test count rather than being folded into it: {rendered}"
    );
    assert!(
        measured.expected_ci_skips <= measured.tests_that_can_skip,
        "a test the canonical environment expects to skip is one that can skip: {} of {}",
        measured.expected_ci_skips,
        measured.tests_that_can_skip
    );
    assert!(
        measured.tests_that_can_skip < measured.tests,
        "most tests cannot skip at all; if every one could, §38.2's preferred count of zero would \
         be meaningless: {} of {}",
        measured.tests_that_can_skip,
        measured.tests
    );
}

#[test]
fn should_find_this_repositorys_readme_in_agreement_with_the_tree() {
    let problems = check_readme(&repo());
    assert!(
        problems.is_empty(),
        "v0.4.1 §50.3: the README's metrics block and the tree disagree:\n{}",
        problems
            .iter()
            .map(|p| format!("  {} — {}", p.location, p.detail))
            .collect::<Vec<_>>()
            .join("\n")
    );
}

#[test]
fn should_fail_when_the_readme_disagrees_with_the_computed_metrics() {
    // The exit test of issue #111, and the whole of §50.3: "the gate MUST fail if the numbers do
    // not match generated truth". A repository with two crates, a README that claims three.
    let repo = scratch();
    repo.write("crates/ono-core/src/lib.rs", "//! one\n");
    repo.write("crates/ono-value/src/lib.rs", "//! two\n");
    repo.write(
        "README.md",
        "# Ono-Sendai\n\n<!-- generated by `cargo xtask metrics`. -->\n\n```text\ncrates=3\n```\n\n<!-- end generated -->\n",
    );
    let problems = check_readme(repo.path());
    assert_eq!(problems.len(), 1, "got {problems:?}");
    assert!(
        problems[0].detail.contains("crates=2"),
        "the problem shows what the tree says, so the correction is a reading rather than an \
         investigation: {}",
        problems[0].detail
    );
    assert!(
        problems[0].detail.contains("cargo xtask metrics --write"),
        "and names the command that fixes it: {}",
        problems[0].detail
    );
}

#[test]
fn should_report_a_readme_that_carries_no_generated_block_at_all() {
    // §50.1 forbids the counts existing without verification. Deleting the block is the easy way
    // to make the check pass, so it is the case the check has to report.
    let repo = scratch();
    repo.write("crates/ono-core/src/lib.rs", "//! one\n");
    repo.write(
        "README.md",
        "# Ono-Sendai\n\nThirty crates, give or take.\n",
    );
    let problems = check_readme(repo.path());
    assert!(
        problems
            .iter()
            .any(|problem| problem.detail.contains("no generated metrics block")),
        "got {problems:?}"
    );
}

#[test]
fn should_rewrite_the_block_and_leave_the_prose_around_it_alone() {
    // §50.3: "The original narrative text around it remains human-owned." A generator that
    // rewrote the paragraph would make the sentence somebody wrote a build artifact.
    let repo = scratch();
    repo.write("crates/ono-core/src/lib.rs", "//! one\n");
    repo.write(
        "README.md",
        "# Ono-Sendai\n\nThe deck is real this time.\n\n<!-- generated by `cargo xtask metrics`. -->\n\n```text\ncrates=99\n```\n\n<!-- end generated -->\n\nAnd the narrative continues.\n",
    );
    assert!(write_readme(repo.path()).expect("the README is rewritten"));
    let text = std::fs::read_to_string(repo.path().join("README.md")).expect("README.md");
    assert!(
        text.contains("The deck is real this time.")
            && text.contains("And the narrative continues."),
        "the human-owned prose survives: {text}"
    );
    assert!(text.contains("crates=1") && !text.contains("crates=99"));
    assert!(
        !write_readme(repo.path()).expect("the second run is a no-op"),
        "a second run changes nothing, so the generator is not a source of diff noise"
    );
    assert_eq!(check_readme(repo.path()), Vec::new());
}

#[test]
fn should_not_count_a_test_written_inside_a_string_literal() {
    // `xtask/tests/scan.rs` holds Rust fixtures inside raw strings, at the left margin, because
    // the scanners it tests read Rust. Counted naively they are about fifteen tests that do not
    // exist, and a count nobody can reproduce is a count nobody believes.
    let repo = scratch();
    repo.write(
        "crates/ono-core/src/lib.rs",
        "#[test]\nfn should_be_counted() {}\n\nconst FIXTURE: &str = r#\"\n#[test]\nfn should_not_be_counted() {}\n\"#;\n",
    );
    assert_eq!(
        measure(repo.path()).tests,
        1,
        "only the real test is counted"
    );
}

// --- the stripped size of the shipped binary (issue #125, ADR-0863, ADR-0864) -----------------
//
// A 15 MB increase in the shipped binary passed the gate, the acceptance suite and the package
// build without a word, because none of them measured it. These tests hold the three halves of
// the fix: the figure is recorded per target triple, it has a budget beside the other limits, and
// a binary over the budget — or a binary nobody measured, where a measurement is required — fails.

use std::time::{Duration, SystemTime};

use xtask::binary_size::{self, Found};

const HOST: &str = "x86_64-unknown-linux-gnu";

/// A scratch repository whose limits registry budgets the binary at `budget` bytes.
fn repository_with_budget(budget: u64) -> ono_testkit::Scratch {
    let repo = scratch();
    repo.write(
        "docs/contracts/hardening/limits.yaml",
        format!(
            "version: 1\nlimits: []\nbuild_budgets:\n  - key: build.ono_stripped_bytes\n    \
             binary: ono\n    type: bytesize\n    budget: {budget}\n    unit: bytes\n    \
             enforced_by: xtask\n"
        ),
    );
    repo
}

/// Writes a release binary of `bytes` bytes at `relative`, with the dep-info file cargo writes
/// beside it naming one source, and dates the source ten minutes before or after the binary.
///
/// An `ono` is the build its triple ships (ADR-0868): the full shell names a crate only the full
/// build links — the KUANG/11 supervisor — and the core build on the musl triple names none.
fn built_binary(repo: &ono_testkit::Scratch, relative: &str, bytes: u64, source_is_newer: bool) {
    let source = repo.write("crates/ono-cli/src/main.rs", "fn main() {}\n");
    let binary = repo.path().join(relative);
    std::fs::create_dir_all(binary.parent().expect("a directory")).expect("the directory");
    let file = std::fs::File::create(&binary).expect("the binary");
    file.set_len(bytes).expect("the binary's size");
    let mut inputs = source.display().to_string();
    if relative.ends_with("/ono") && !relative.contains("musl") {
        let full_only = repo.write("crates/ono-kuang-supervisor/src/lib.rs", "//! full\n");
        std::fs::File::options()
            .write(true)
            .open(&full_only)
            .and_then(|file| file.set_modified(SystemTime::now() - Duration::from_secs(3600)))
            .expect("the full-only source's mtime");
        inputs = format!("{inputs} {}", full_only.display());
    }
    repo.write(
        format!("{relative}.d"),
        format!("{}: {inputs}\n", binary.display()),
    );
    let now = SystemTime::now();
    let (binary_time, source_time) = if source_is_newer {
        (now - Duration::from_secs(600), now)
    } else {
        (now, now - Duration::from_secs(600))
    };
    file.set_modified(binary_time).expect("the binary's mtime");
    std::fs::File::options()
        .write(true)
        .open(&source)
        .expect("the source")
        .set_modified(source_time)
        .expect("the source's mtime");
}

#[test]
fn should_record_the_stripped_size_per_target_triple_when_the_release_binary_is_current() {
    let repo = repository_with_budget(30_000_000);
    built_binary(&repo, "target/release/ono", 22_000_000, false);

    let found = binary_size::find(repo.path(), &repo.path().join("target"), HOST);
    binary_size::record(repo.path(), &found).expect("the record is written");

    assert_eq!(
        binary_size::recorded(repo.path(), "ono").get(HOST),
        Some(&22_000_000),
        "the figure is recorded under the triple it was built for: {}",
        repo.read(binary_size::RECORD)
    );
    let rendered = measure(repo.path()).render();
    assert!(
        rendered.contains(&format!("stripped_bytes.ono.{HOST}=22000000")),
        "the README block carries the recorded figure beside the other counts: {rendered}"
    );
}

#[test]
fn should_record_a_cross_built_binary_under_its_own_triple() {
    // `scripts/package.sh` builds into `target/<triple>/release/ono`, which is the binary that
    // ships, and a foreign triple only ever appears there.
    let repo = repository_with_budget(30_000_000);
    built_binary(
        &repo,
        "target/aarch64-unknown-linux-gnu/release/ono",
        21_000_000,
        false,
    );
    let found = binary_size::find(repo.path(), &repo.path().join("target"), HOST);
    binary_size::record(repo.path(), &found).expect("the record is written");
    let recorded = binary_size::recorded(repo.path(), "ono");
    assert_eq!(recorded.get("aarch64-unknown-linux-gnu"), Some(&21_000_000));
    assert_eq!(recorded.get(HOST), None, "nothing was built for the host");
}

#[test]
fn should_not_record_a_binary_older_than_the_sources_it_was_built_from() {
    // A stale binary is yesterday's figure. Recording it would make the record lie about the tree
    // it sits in, so it is left alone and the reason is said.
    let repo = repository_with_budget(30_000_000);
    built_binary(&repo, "target/release/ono", 22_000_000, true);

    let found = binary_size::find(repo.path(), &repo.path().join("target"), HOST);
    assert!(
        matches!(found.as_slice(), [Found::Unmeasured { .. }]),
        "a binary older than a source it names is stale: {found:?}"
    );
    binary_size::record(repo.path(), &found).expect("nothing to write is not an error");
    assert!(binary_size::recorded(repo.path(), "ono").is_empty());
}

#[test]
fn should_date_a_binary_built_in_a_container_against_the_sources_under_this_checkout() {
    // `scripts/package.sh` builds with the checkout mounted at `/project`, so cargo's dep-info
    // names `/project/crates/…`. Those are this checkout's files under another root, and the
    // binary is dated against them rather than declared stale because `/project` is not here.
    let repo = repository_with_budget(30_000_000);
    let relative = "target/x86_64-unknown-linux-gnu/release/ono";
    for source_is_newer in [false, true] {
        built_binary(&repo, relative, 22_000_000, source_is_newer);
        repo.write(
            format!("{relative}.d"),
            "/project/target/x86_64-unknown-linux-gnu/release/ono: \
             /project/crates/ono-cli/src/main.rs \
             /project/crates/ono-kuang-supervisor/src/lib.rs\n",
        );
        let found = binary_size::find(repo.path(), &repo.path().join("target"), HOST);
        assert_eq!(
            matches!(
                found.as_slice(),
                [Found::Current {
                    bytes: 22_000_000,
                    ..
                }]
            ),
            !source_is_newer,
            "a source edited after the container build makes the binary stale, and one edited \
             before does not: {found:?}"
        );
    }
}

#[test]
fn should_record_kuang_compile_beside_ono_and_hold_only_ono_to_the_shells_budget() {
    // #126 moved wasmtime's compiler out of the shell into `kuang-compile`, a second shipped
    // binary (ADR-0870). Its size is recorded so it is seen; the budget is the shell's.
    let repo = repository_with_budget(30_000_000);
    built_binary(&repo, "target/release/ono", 22_000_000, false);
    built_binary(&repo, "target/release/kuang-compile", 40_000_000, false);

    let found = binary_size::find(repo.path(), &repo.path().join("target"), HOST);
    binary_size::record(repo.path(), &found).expect("the record is written");
    assert_eq!(
        binary_size::recorded(repo.path(), "kuang-compile").get(HOST),
        Some(&40_000_000)
    );
    assert!(
        measure(repo.path())
            .render()
            .contains(&format!("stripped_bytes.kuang-compile.{HOST}=40000000")),
        "the README block carries the compiler's figure too"
    );
    let verdict = binary_size::check(repo.path(), &found, true);
    assert!(
        verdict.passed,
        "a binary with no budget of its own is not held to the shell's: {verdict:?}"
    );
}

#[test]
fn should_not_measure_an_ono_that_links_the_compiler() {
    // `cargo build --release` over the whole workspace unifies features with `kuang-compile`, and
    // the `ono` it links carries Cranelift, which the shipped one never does (ADR-0870). Its size
    // is not the shipped size: neither recorded nor held to the budget, and the reason is said.
    let repo = repository_with_budget(30_000_000);
    built_binary(&repo, "target/release/ono", 29_000_000, false);
    let compiler = repo.write(
        "target/registry/cranelift-codegen-0.134.4/src/lib.rs",
        "// the compiler\n",
    );
    std::fs::File::options()
        .write(true)
        .open(&compiler)
        .and_then(|file| file.set_modified(SystemTime::now() - Duration::from_secs(3600)))
        .expect("the compiler source's mtime");
    let dependency = repo.path().join("target/release/ono.d");
    let listing = std::fs::read_to_string(&dependency).expect("the dep-info");
    std::fs::write(
        &dependency,
        format!("{} {}\n", listing.trim_end(), compiler.display()),
    )
    .expect("the dep-info");

    let found = binary_size::find(repo.path(), &repo.path().join("target"), HOST);
    assert!(
        matches!(found.as_slice(), [Found::Unmeasured { reason, .. }] if reason.contains("compiler")),
        "an `ono` that links the compiler is not the shipped one: {found:?}"
    );
    binary_size::record(repo.path(), &found).expect("nothing to record");
    assert!(binary_size::recorded(repo.path(), "ono").is_empty());
}

#[test]
fn should_hold_the_core_build_to_its_own_budget_beside_the_full_one() {
    // #127's core build is the same `ono` for `x86_64-unknown-linux-musl` without the
    // enhancements (ADR-0912), with a budget of its own. One registry holds both: a row that names
    // a triple is that triple's budget, and the row without one covers the rest.
    let repo = scratch();
    repo.write(
        "docs/contracts/hardening/limits.yaml",
        "version: 1\nlimits: []\nbuild_budgets:\n  - key: build.ono_stripped_bytes\n    \
         binary: ono\n    budget: 30000000\n  - key: build.ono_core_stripped_bytes\n    \
         binary: ono\n    triple: x86_64-unknown-linux-musl\n    budget: 7999999\n",
    );
    built_binary(&repo, "target/release/ono", 22_000_000, false);
    built_binary(
        &repo,
        "target/x86_64-unknown-linux-musl/release/ono",
        8_000_000,
        false,
    );
    let found = binary_size::find(repo.path(), &repo.path().join("target"), HOST);
    let verdict = binary_size::check(repo.path(), &found, true);
    assert!(
        !verdict.passed
            && verdict
                .lines
                .iter()
                .any(|line| line.contains("x86_64-unknown-linux-musl")
                    && line.contains("8000000")
                    && line.contains("7999999")),
        "the core binary is held to the core budget, not the full one: {verdict:?}"
    );

    built_binary(
        &repo,
        "target/x86_64-unknown-linux-musl/release/ono",
        7_063_744,
        false,
    );
    let found = binary_size::find(repo.path(), &repo.path().join("target"), HOST);
    assert!(binary_size::check(repo.path(), &found, true).passed);
    binary_size::record(repo.path(), &found).expect("the record is written");
    assert_eq!(
        binary_size::recorded(repo.path(), "ono").get("x86_64-unknown-linux-musl"),
        Some(&7_063_744),
        "the core figure is recorded under its triple"
    );
}

#[test]
fn should_not_measure_a_core_build_left_where_the_full_shell_goes() {
    // `cargo build --release -p ono-cli --no-default-features --features core` without
    // `--target` writes `target/release/ono`, where the full shell of the host lands. Its size is
    // the core build's; recorded as the full shell's it would halve the figure the budget holds.
    let repo = repository_with_budget(30_000_000);
    built_binary(&repo, "target/release/ono", 7_000_000, false);
    let dependency = repo.path().join("target/release/ono.d");
    let listing = std::fs::read_to_string(&dependency).expect("the dep-info");
    let core_only: String = listing
        .split_whitespace()
        .filter(|input| !input.contains("ono-kuang-supervisor"))
        .collect::<Vec<_>>()
        .join(" ");
    std::fs::write(&dependency, format!("{core_only}\n")).expect("the dep-info");

    let found = binary_size::find(repo.path(), &repo.path().join("target"), HOST);
    assert!(
        matches!(found.as_slice(), [Found::Unmeasured { reason, .. }] if reason.contains("core")),
        "a core build on a full triple is not the shipped shell: {found:?}"
    );
    binary_size::record(repo.path(), &found).expect("nothing to record");
    assert!(binary_size::recorded(repo.path(), "ono").is_empty());
}

#[test]
fn should_not_measure_a_full_build_on_the_core_triple() {
    let repo = repository_with_budget(30_000_000);
    let relative = "target/x86_64-unknown-linux-musl/release/ono";
    built_binary(&repo, relative, 7_000_000, false);
    let full_only = repo.path().join("crates/ono-kuang-supervisor/src/lib.rs");
    std::fs::create_dir_all(full_only.parent().expect("a directory")).expect("the directory");
    std::fs::write(&full_only, "//! full\n").expect("the source");
    std::fs::File::options()
        .write(true)
        .open(&full_only)
        .and_then(|file| file.set_modified(SystemTime::now() - Duration::from_secs(3600)))
        .expect("the mtime");
    let dependency = repo.path().join(format!("{relative}.d"));
    let listing = std::fs::read_to_string(&dependency).expect("the dep-info");
    std::fs::write(
        &dependency,
        format!("{} {}\n", listing.trim_end(), full_only.display()),
    )
    .expect("the dep-info");

    let found = binary_size::find(repo.path(), &repo.path().join("target"), HOST);
    assert!(
        matches!(found.as_slice(), [Found::Unmeasured { reason, .. }] if reason.contains("core")),
        "the musl triple is the core build's, and a full build there is not it: {found:?}"
    );
}

#[test]
fn should_not_measure_a_binary_older_than_a_member_manifest() {
    // A feature list lives in a member's Cargo.toml, and editing it rebuilds the binary without
    // touching a source the dep-info names.
    let repo = repository_with_budget(30_000_000);
    built_binary(&repo, "target/release/ono", 22_000_000, false);
    let manifest = repo.write(
        "crates/ono-cli/Cargo.toml",
        "[package]\nname = \"ono-cli\"\n",
    );
    // Dated explicitly: the filesystem's clock is coarser than `SystemTime::now`, so a file
    // written a moment after the binary can carry an earlier mtime.
    std::fs::File::options()
        .write(true)
        .open(&manifest)
        .and_then(|file| file.set_modified(SystemTime::now() + Duration::from_secs(60)))
        .expect("the manifest's mtime");

    let found = binary_size::find(repo.path(), &repo.path().join("target"), HOST);
    assert!(
        matches!(found.as_slice(), [Found::Unmeasured { reason, .. }] if reason.contains("Cargo.toml")),
        "a manifest edited after the build makes the binary stale: {found:?}"
    );
}

#[test]
fn should_fail_the_budget_when_the_release_binary_exceeds_it() {
    let repo = repository_with_budget(20_000_000);
    built_binary(&repo, "target/release/ono", 20_000_001, false);
    let found = binary_size::find(repo.path(), &repo.path().join("target"), HOST);
    let verdict = binary_size::check(repo.path(), &found, false);
    assert!(
        !verdict.passed,
        "one byte over the budget is over the budget: {verdict:?}"
    );
    assert!(
        verdict
            .lines
            .iter()
            .any(|line| line.contains("20000001") && line.contains("20000000")),
        "the failure names the figure and the budget: {verdict:?}"
    );
}

#[test]
fn should_pass_the_budget_when_the_release_binary_is_within_it() {
    let repo = repository_with_budget(20_000_000);
    built_binary(&repo, "target/release/ono", 20_000_000, false);
    let found = binary_size::find(repo.path(), &repo.path().join("target"), HOST);
    let verdict = binary_size::check(repo.path(), &found, true);
    assert!(verdict.passed, "{verdict:?}");
}

#[test]
fn should_announce_an_unmeasured_binary_and_fail_only_where_a_measurement_is_required() {
    // ADR-0864: a developer gate without a release build says it measured nothing rather than
    // building for seven minutes; the acceptance image, which has just built the release binary,
    // requires the measurement. A missing measurement never passes silently.
    let repo = repository_with_budget(20_000_000);
    let missing = binary_size::find(repo.path(), &repo.path().join("target"), HOST);
    built_binary(&repo, "target/release/ono", 1_000, true);
    let stale = binary_size::find(repo.path(), &repo.path().join("target"), HOST);
    for found in [missing, stale] {
        let optional = binary_size::check(repo.path(), &found, false);
        assert!(optional.passed, "{optional:?}");
        assert!(
            optional
                .lines
                .iter()
                .any(|line| line.contains("not measured")),
            "an unmeasured binary is announced, not passed over: {optional:?}"
        );
        let required = binary_size::check(repo.path(), &found, true);
        assert!(
            !required.passed,
            "where a measurement is required its absence fails: {required:?}"
        );
    }
}

#[test]
fn should_fail_when_the_limits_registry_declares_no_budget() {
    let repo = scratch();
    repo.write(
        "docs/contracts/hardening/limits.yaml",
        "version: 1\nlimits: []\n",
    );
    built_binary(&repo, "target/release/ono", 1_000, false);
    let found = binary_size::find(repo.path(), &repo.path().join("target"), HOST);
    let verdict = binary_size::check(repo.path(), &found, false);
    assert!(
        !verdict.passed,
        "a budget nobody declared is not a budget the binary met: {verdict:?}"
    );
}

#[test]
fn should_report_a_recorded_figure_above_the_budget_and_a_missing_record() {
    let repo = repository_with_budget(20_000_000);
    let problems = binary_size::check_record(repo.path());
    assert!(
        problems
            .iter()
            .any(|problem| problem.detail.contains("records no stripped size")),
        "a budget with no recorded figure is a measurement nobody made: {problems:?}"
    );

    built_binary(&repo, "target/release/ono", 25_000_000, false);
    let found = binary_size::find(repo.path(), &repo.path().join("target"), HOST);
    binary_size::record(repo.path(), &found).expect("the record is written");
    let problems = binary_size::check_record(repo.path());
    assert!(
        problems
            .iter()
            .any(|problem| problem.detail.contains("25000000")),
        "a recorded figure over the budget is reported: {problems:?}"
    );
}

#[test]
fn should_hold_this_repositorys_recorded_binary_size_within_its_budget() {
    let root = repo();
    assert!(
        binary_size::budget(&root, "ono", HOST).is_ok(),
        "docs/contracts/hardening/limits.yaml budgets the stripped binary (issue #125)"
    );
    assert!(
        binary_size::recorded(&root, "ono").contains_key(HOST),
        "{} records the stripped size of the x86_64 release binary",
        binary_size::RECORD
    );
    assert_eq!(binary_size::check_record(&root), Vec::new());
}

#[test]
fn should_refuse_an_oversized_binary_through_the_command_the_image_build_runs() {
    // The exit test of #125, through the command `docker/Dockerfile` and `scripts/gate.sh` run:
    // a binary one byte over this repository's budget fails, one at the budget passes.
    let budget = binary_size::budget(&repo(), "ono", HOST).expect("the budget");
    let directory = scratch();
    for (bytes, passes) in [(budget + 1, false), (budget, true)] {
        let binary = directory.path().join("ono");
        std::fs::File::create(&binary)
            .and_then(|file| file.set_len(bytes))
            .expect("a binary of that size");
        let output = std::process::Command::new(env!("CARGO_BIN_EXE_xtask"))
            .args(["binary-size", "--require", "--binary"])
            .arg(&binary)
            .output()
            .expect("xtask runs");
        assert_eq!(
            output.status.success(),
            passes,
            "{bytes} bytes against a budget of {budget}:\n{}{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
    }
}
