[package]
name = "ono-spatial-render"
description = "Text rendering for the Ono-Sendai spatial interface."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
ono-value.workspace = true

[lints]
workspace = true
