//! What the listening agent knows about the peer it is answering (v0.4.1 spec §2.1, §2.2, §7,
//! §13; issue #35).
//!
//! `tests/tls.rs` proves the *client's* half of the trust model: the connecting side learns which
//! key the agent proved it holds, and refuses a key it did not pin. This suite is the other half.
//! Until issue #35 the other half did not exist — a `TlsListener` presented a certificate and
//! asked for none, so a stranger who dialled the port completed the TLS handshake, spoke the Ono
//! protocol and read back the agent's provider inventory, having said nothing about itself that
//! was not a string it chose.
//!
//! v0.4.1 §2.1 fixes what the word may mean — "Ono MUST possess cryptographic evidence that the
//! peer holds the private key corresponding to the identity accepted by policy" — and §13.1 fixes
//! when: "mutual TLS MUST complete before an Ono `Hello` frame is accepted."
//!
//! The first test below is the failure proof v0.4.1 §57 phase H0 required before that fix could
//! land (ADR-0430); it went green when the listener began demanding a client certificate, and its
//! assertion has not been touched since it was written. The three beside it are the remaining
//! negative cases §58.1 names: a malformed certificate, a certificate the peer cannot prove it
//! holds, and the wrong application protocol.
//!
//! Everything runs on the loopback interface with keys generated by the test, so the suite needs
//! no network, no certificate authority and no fixture host.
#![allow(
    clippy::expect_used,
    clippy::unwrap_used,
    clippy::panic,
    reason = "a test states its preconditions directly (AGENTS.md section 16)"
)]

mod common;

use std::sync::Arc;

use common::{client_config, listening, within};
use ono_protocol::{ProviderDescriptor, Transport, UnauthenticatedTransport};
use ono_remote::{PeerIdentity, RemoteLink, TlsListener, tls_connect};
use rustls::pki_types::{CertificateDer, ServerName, UnixTime};
use tokio::net::TcpStream;

/// A client that checks nothing about the certificate the server sends.
///
/// The subject of this suite is what the *server* demands, so the client end deliberately makes
/// no demand of its own: whatever the agent presents is accepted, and the only question left is
/// whether the agent accepts a peer that presented nothing.
#[derive(Debug)]
struct AcceptAnyServer {
    provider: Arc<rustls::crypto::CryptoProvider>,
}

impl rustls::client::danger::ServerCertVerifier for AcceptAnyServer {
    fn verify_server_cert(
        &self,
        _end_entity: &CertificateDer<'_>,
        _intermediates: &[CertificateDer<'_>],
        _server_name: &ServerName<'_>,
        _ocsp_response: &[u8],
        _now: UnixTime,
    ) -> Result<rustls::client::danger::ServerCertVerified, rustls::Error> {
        Ok(rustls::client::danger::ServerCertVerified::assertion())
    }

    fn verify_tls12_signature(
        &self,
        message: &[u8],
        cert: &CertificateDer<'_>,
        dss: &rustls::DigitallySignedStruct,
    ) -> Result<rustls::client::danger::HandshakeSignatureValid, rustls::Error> {
        rustls::crypto::verify_tls12_signature(
            message,
            cert,
            dss,
            &self.provider.signature_verification_algorithms,
        )
    }

    fn verify_tls13_signature(
        &self,
        message: &[u8],
        cert: &CertificateDer<'_>,
        dss: &rustls::DigitallySignedStruct,
    ) -> Result<rustls::client::danger::HandshakeSignatureValid, rustls::Error> {
        rustls::crypto::verify_tls13_signature(
            message,
            cert,
            dss,
            &self.provider.signature_verification_algorithms,
        )
    }

    fn supported_verify_schemes(&self) -> Vec<rustls::SignatureScheme> {
        self.provider
            .signature_verification_algorithms
            .supported_schemes()
    }
}

/// Dials `address` with **no client certificate** and reports the provider ids the agent
/// disclosed, or how far the attempt got before it was refused.
///
/// The two ALPN tokens are offered together on purpose. v0.4.1 §13.4 lets the fix advance the
/// token to `ono/2` alongside the mutual-authentication contract, and a client that offered only
/// `ono/1` would then be refused for speaking the wrong protocol rather than for proving nothing
/// — a green test for the wrong reason. Offering both leaves exactly one thing this client
/// lacks: a certificate.
async fn negotiate_without_a_client_certificate(address: &str) -> Result<Vec<String>, String> {
    let provider = Arc::new(rustls::crypto::ring::default_provider());
    let mut config = rustls::ClientConfig::builder_with_provider(Arc::clone(&provider))
        .with_protocol_versions(&[&rustls::version::TLS13])
        .map_err(|error| format!("TLS 1.3 is unavailable: {error}"))?
        .dangerous()
        .with_custom_certificate_verifier(Arc::new(AcceptAnyServer { provider }))
        // The subject of the proof: this client holds no key and offers no certificate.
        .with_no_client_auth();
    config.alpn_protocols = vec![b"ono/2".to_vec(), b"ono/1".to_vec()];

    let stream = TcpStream::connect(address)
        .await
        .map_err(|error| format!("the port did not answer: {error}"))?;
    let name = ServerName::try_from("ono.invalid").map_err(|error| format!("{error}"))?;
    let stream = tokio_rustls::TlsConnector::from(Arc::new(config))
        .connect(name, stream)
        .await
        .map_err(|error| format!("the TLS handshake was refused: {error}"))?;

    let link = RemoteLink::connect(UnauthenticatedTransport::new(stream), client_config())
        .await
        .map_err(|error| format!("the Ono handshake was refused: {error:?}"))?;
    let providers = link
        .negotiated()
        .providers()
        .iter()
        .map(|provider| ProviderDescriptor::id(provider).to_owned())
        .collect();
    link.hangup();
    Ok(providers)
}

#[tokio::test]
async fn should_refuse_a_tls_client_that_presents_no_certificate() {
    let identity = PeerIdentity::generate().expect("a host identity is generated");
    let address = listening(identity).await;

    let reached = within(negotiate_without_a_client_certificate(&address)).await;

    assert!(
        reached.is_err(),
        "v0.4.1 §2.2 orders the link `cryptographic peer proof -> peer trust decision -> \
         authorization -> negotiation`, and §13.1 requires mutual TLS to complete before an Ono \
         `Hello` frame is accepted. A peer holding no key must therefore be refused by the TLS \
         handshake, before a single Ono frame crosses. It was not: the handshake completed, the \
         agent answered the Ono handshake, and the anonymous peer read back the provider \
         inventory §59.1 says it may not see — {reached:?}"
    );
}

/// A fresh self-signed certificate and the key that goes with it, the way any Ono peer's
/// identity is made — but built here so the test can take the two apart.
fn generated_pair() -> (
    CertificateDer<'static>,
    rustls::pki_types::PrivateKeyDer<'static>,
) {
    let generated = rcgen::generate_simple_self_signed(vec!["ono.invalid".to_owned()])
        .expect("a key pair is generated");
    let certificate = CertificateDer::from(generated.cert.der().to_vec());
    let key = rustls::pki_types::PrivateKeyDer::from(rustls::pki_types::PrivatePkcs8KeyDer::from(
        generated.key_pair.serialize_der(),
    ));
    (certificate, key)
}

/// A client that presents exactly what the test handed it, however wrong that is.
///
/// `ClientConfig::with_client_auth_cert` refuses a malformed certificate and a key that does not
/// match its certificate *in the client*, which would make each negative case below green
/// because rustls is careful rather than because the Ono listener demands anything. Resolving the
/// certificate by hand puts the adversary on the wire, where the server has to answer it.
#[derive(Debug)]
struct PresentsWhateverItWasGiven(Arc<rustls::sign::CertifiedKey>);

impl rustls::client::ResolvesClientCert for PresentsWhateverItWasGiven {
    fn resolve(
        &self,
        _root_hint_subjects: &[&[u8]],
        _schemes: &[rustls::SignatureScheme],
    ) -> Option<Arc<rustls::sign::CertifiedKey>> {
        Some(Arc::clone(&self.0))
    }

    fn has_certs(&self) -> bool {
        true
    }
}

/// Dials `address` presenting `certificate`, signing with `key`, offering `alpn`, and reports the
/// provider ids the agent disclosed or how far the attempt got.
///
/// Every negative case below differs from a legitimate client in exactly one of those three
/// things, so a refusal is attributable to the thing the case is named for.
async fn negotiate_presenting(
    address: &str,
    certificate: CertificateDer<'static>,
    key: rustls::pki_types::PrivateKeyDer<'static>,
    alpn: &[&[u8]],
) -> Result<Vec<String>, String> {
    let provider = Arc::new(rustls::crypto::ring::default_provider());
    let signing_key = provider
        .key_provider
        .load_private_key(key)
        .map_err(|error| format!("the private key was not usable: {error}"))?;
    let presenting = Arc::new(PresentsWhateverItWasGiven(Arc::new(
        rustls::sign::CertifiedKey::new(vec![certificate], signing_key),
    )));
    let mut config = rustls::ClientConfig::builder_with_provider(Arc::clone(&provider))
        .with_protocol_versions(&[&rustls::version::TLS13])
        .map_err(|error| format!("TLS 1.3 is unavailable: {error}"))?
        .dangerous()
        .with_custom_certificate_verifier(Arc::new(AcceptAnyServer { provider }))
        .with_client_cert_resolver(presenting);
    config.alpn_protocols = alpn.iter().map(|token| token.to_vec()).collect();

    let stream = TcpStream::connect(address)
        .await
        .map_err(|error| format!("the port did not answer: {error}"))?;
    let name = ServerName::try_from("ono.invalid").map_err(|error| format!("{error}"))?;
    let stream = tokio_rustls::TlsConnector::from(Arc::new(config))
        .connect(name, stream)
        .await
        .map_err(|error| format!("the TLS handshake was refused: {error}"))?;

    let link = RemoteLink::connect(UnauthenticatedTransport::new(stream), client_config())
        .await
        .map_err(|error| format!("the Ono handshake was refused: {error:?}"))?;
    let providers = link
        .negotiated()
        .providers()
        .iter()
        .map(|provider| ProviderDescriptor::id(provider).to_owned())
        .collect();
    link.hangup();
    Ok(providers)
}

/// v0.4.1 §58.1 negative test 2: a certificate that is not a certificate.
#[tokio::test]
async fn should_refuse_a_tls_client_whose_certificate_is_malformed() {
    let identity = PeerIdentity::generate().expect("a peer identity is generated");
    let address = listening(identity).await;
    let (_, key) = generated_pair();
    let garbage = CertificateDer::from(vec![0x30, 0x82, 0xde, 0xad, 0xbe, 0xef]);

    let reached = within(negotiate_presenting(
        &address,
        garbage,
        key,
        &[b"ono/2", b"ono/1"],
    ))
    .await;

    assert!(
        reached.is_err(),
        "§2.1 requires cryptographic evidence that the peer holds the private key corresponding \
         to the identity it presents. Bytes that are not a certificate carry no public key, so \
         no such evidence can exist and the handshake must fail — {reached:?}"
    );
}

/// v0.4.1 §58.1 negative test 3: a real certificate, and a peer that cannot prove it holds the
/// key inside it. This is the case a stolen or copied certificate produces, and the one the
/// whole trust model rests on: the certificate is public, and only the signature is proof.
#[tokio::test]
async fn should_refuse_a_tls_client_that_cannot_prove_it_holds_the_key_it_presents() {
    let identity = PeerIdentity::generate().expect("a peer identity is generated");
    let address = listening(identity).await;
    let (certificate, _) = generated_pair();
    let (_, someone_elses_key) = generated_pair();

    let reached = within(negotiate_presenting(
        &address,
        certificate,
        someone_elses_key,
        &[b"ono/2", b"ono/1"],
    ))
    .await;

    assert!(
        reached.is_err(),
        "§7.1: both endpoints MUST `prove possession of the corresponding private key`. A peer \
         presenting a certificate it did not sign with proved nothing — {reached:?}"
    );
}

/// v0.4.1 §58.1 negative test 4, and §13.4: the application both ends agree they are speaking is
/// settled inside the TLS handshake, so a peer speaking something else is refused before a frame
/// crosses rather than confusing this protocol's own version negotiation with another protocol.
#[tokio::test]
async fn should_refuse_a_tls_client_that_asks_for_another_application_protocol() {
    let identity = PeerIdentity::generate().expect("a peer identity is generated");
    let address = listening(identity).await;
    let (certificate, key) = generated_pair();

    let reached = within(negotiate_presenting(
        &address,
        certificate,
        key,
        &[b"ono/legacy-0"],
    ))
    .await;

    assert!(
        reached.is_err(),
        "§13.4 makes the ALPN token the name of the contract the two ends are keeping. A peer \
         that asked for a different one is not owed this one — {reached:?}"
    );
}

/// v0.4.1 §58.1's second Done criterion: "`TlsTransport::peer_key()` is `Some` for accepted
/// network clients". This is the half of §2.2 that makes the *next* phase possible — an
/// authorization store can only decide about a client the transport can name, and before this
/// increment the listening side had nothing to hand it (ADR-0274, ADR-0437).
#[tokio::test]
async fn should_report_the_key_the_accepted_client_proved_it_holds() {
    let listener = TlsListener::bind(
        "127.0.0.1:0",
        &PeerIdentity::generate().expect("an agent identity is generated"),
    )
    .await
    .expect("a loopback listener binds");
    let address = listener
        .local_addr()
        .expect("the system reports the port it chose")
        .to_string();
    let client = PeerIdentity::generate().expect("a client identity is generated");
    let expected = client.peer_key();

    let accepted = tokio::spawn(async move { listener.accept().await });
    let dialled = within(tls_connect(&address, &client))
        .await
        .expect("a client presenting an identity is accepted");
    let accepted = within(accepted)
        .await
        .expect("the accept task finished")
        .expect("the listener accepted the authenticated client");

    assert_eq!(
        accepted.peer_key(),
        Some(&expected),
        "§2.1: the agent must possess cryptographic evidence of who it is answering, and here it \
         has it — the certificate whose key signed this handshake's transcript"
    );
    assert!(
        dialled.peer_key().is_some(),
        "§7.1 makes the transport symmetric, so the client learned the agent's key too"
    );
}
