//! What the listening agent knows about the peer it is answering (v0.4.1 spec §2.1, §2.2, §7,
//! §13; issue #35).
//!
//! `tests/tls.rs` proves the *client's* half of the trust model: the connecting side learns which
//! key the agent proved it holds, and refuses a key it did not pin. This suite is the other half,
//! and at the time it was written the other half did not exist. A `TlsListener` presents a
//! certificate and asks for none, so a stranger who dialled the port completed the TLS handshake,
//! spoke the Ono protocol and read back the agent's provider inventory. The protocol-level
//! `Identity` it sent along the way is a string it chose about itself.
//!
//! v0.4.1 §2.1 fixes what the word may mean — "Ono MUST possess cryptographic evidence that the
//! peer holds the private key corresponding to the identity accepted by policy" — and §13.1 fixes
//! when: "mutual TLS MUST complete before an Ono `Hello` frame is accepted."
//!
//! The test below is the failure proof required by v0.4.1 §57 phase H0 before the fix in issue
//! #35 may land. It is `#[ignore]`d because it fails at HEAD, and the increment that requires an
//! authenticated client certificate on the listener removes the attribute rather than the test.
//!
//! Everything runs on the loopback interface with keys generated by the test, so the suite needs
//! no network, no certificate authority and no fixture host.
#![allow(
    clippy::expect_used,
    clippy::unwrap_used,
    clippy::panic,
    reason = "a test states its preconditions directly (AGENTS.md section 16)"
)]

mod common;

use std::sync::Arc;

use common::fixture::{FixtureObserved, fixture_registry};
use common::{client_config, within};
use ono_protocol::{Identity, PlainTransport, ProviderDescriptor};
use ono_remote::{AgentConfig, HostIdentity, RemoteLink, TlsListener, serve_registry};
use rustls::pki_types::{CertificateDer, ServerName, UnixTime};
use tokio::net::TcpStream;

/// An agent listening on a loopback port the system chooses, serving the fixture registry.
async fn listening(identity: HostIdentity) -> String {
    let listener = TlsListener::bind("127.0.0.1:0", &identity)
        .await
        .expect("a loopback listener binds");
    let address = listener
        .local_addr()
        .expect("the system reports the port it chose")
        .to_string();
    tokio::spawn(async move {
        while let Ok(transport) = listener.accept().await {
            let registry = fixture_registry(Arc::new(FixtureObserved::default()));
            let config = AgentConfig::new(registry).with_identity(Identity::new("remote-user"));
            tokio::spawn(async move {
                let _ = serve_registry(transport, config).await;
            });
        }
    });
    address
}

/// A client that checks nothing about the certificate the server sends.
///
/// The subject of this suite is what the *server* demands, so the client end deliberately makes
/// no demand of its own: whatever the agent presents is accepted, and the only question left is
/// whether the agent accepts a peer that presented nothing.
#[derive(Debug)]
struct AcceptAnyServer {
    provider: Arc<rustls::crypto::CryptoProvider>,
}

impl rustls::client::danger::ServerCertVerifier for AcceptAnyServer {
    fn verify_server_cert(
        &self,
        _end_entity: &CertificateDer<'_>,
        _intermediates: &[CertificateDer<'_>],
        _server_name: &ServerName<'_>,
        _ocsp_response: &[u8],
        _now: UnixTime,
    ) -> Result<rustls::client::danger::ServerCertVerified, rustls::Error> {
        Ok(rustls::client::danger::ServerCertVerified::assertion())
    }

    fn verify_tls12_signature(
        &self,
        message: &[u8],
        cert: &CertificateDer<'_>,
        dss: &rustls::DigitallySignedStruct,
    ) -> Result<rustls::client::danger::HandshakeSignatureValid, rustls::Error> {
        rustls::crypto::verify_tls12_signature(
            message,
            cert,
            dss,
            &self.provider.signature_verification_algorithms,
        )
    }

    fn verify_tls13_signature(
        &self,
        message: &[u8],
        cert: &CertificateDer<'_>,
        dss: &rustls::DigitallySignedStruct,
    ) -> Result<rustls::client::danger::HandshakeSignatureValid, rustls::Error> {
        rustls::crypto::verify_tls13_signature(
            message,
            cert,
            dss,
            &self.provider.signature_verification_algorithms,
        )
    }

    fn supported_verify_schemes(&self) -> Vec<rustls::SignatureScheme> {
        self.provider
            .signature_verification_algorithms
            .supported_schemes()
    }
}

/// Dials `address` with **no client certificate** and reports the provider ids the agent
/// disclosed, or how far the attempt got before it was refused.
///
/// The two ALPN tokens are offered together on purpose. v0.4.1 §13.4 lets the fix advance the
/// token to `ono/2` alongside the mutual-authentication contract, and a client that offered only
/// `ono/1` would then be refused for speaking the wrong protocol rather than for proving nothing
/// — a green test for the wrong reason. Offering both leaves exactly one thing this client
/// lacks: a certificate.
async fn negotiate_without_a_client_certificate(address: &str) -> Result<Vec<String>, String> {
    let provider = Arc::new(rustls::crypto::ring::default_provider());
    let mut config = rustls::ClientConfig::builder_with_provider(Arc::clone(&provider))
        .with_protocol_versions(&[&rustls::version::TLS13])
        .map_err(|error| format!("TLS 1.3 is unavailable: {error}"))?
        .dangerous()
        .with_custom_certificate_verifier(Arc::new(AcceptAnyServer { provider }))
        // The subject of the proof: this client holds no key and offers no certificate.
        .with_no_client_auth();
    config.alpn_protocols = vec![b"ono/2".to_vec(), b"ono/1".to_vec()];

    let stream = TcpStream::connect(address)
        .await
        .map_err(|error| format!("the port did not answer: {error}"))?;
    let name = ServerName::try_from("ono.invalid").map_err(|error| format!("{error}"))?;
    let stream = tokio_rustls::TlsConnector::from(Arc::new(config))
        .connect(name, stream)
        .await
        .map_err(|error| format!("the TLS handshake was refused: {error}"))?;

    let link = RemoteLink::connect(PlainTransport::new(stream), client_config())
        .await
        .map_err(|error| format!("the Ono handshake was refused: {error:?}"))?;
    let providers = link
        .negotiated()
        .providers()
        .iter()
        .map(|provider| ProviderDescriptor::id(provider).to_owned())
        .collect();
    link.hangup();
    Ok(providers)
}

// REASON: the failure proof of v0.4.1 §57 phase H0 for §0.5.1 — an anonymous TLS client reaches
// and completes the Ono handshake, because `TlsListener` is built `with_no_client_auth()`. Issue
// #35 makes the listener demand and verify a client certificate, and un-ignores this. ADR-0430.
#[tokio::test]
#[ignore = "RED proof for issue #35: the listener accepts a client that presents no certificate"]
async fn should_refuse_a_tls_client_that_presents_no_certificate() {
    let identity = HostIdentity::generate().expect("a host identity is generated");
    let address = listening(identity).await;

    let reached = within(negotiate_without_a_client_certificate(&address)).await;

    assert!(
        reached.is_err(),
        "v0.4.1 §2.2 orders the link `cryptographic peer proof -> peer trust decision -> \
         authorization -> negotiation`, and §13.1 requires mutual TLS to complete before an Ono \
         `Hello` frame is accepted. A peer holding no key must therefore be refused by the TLS \
         handshake, before a single Ono frame crosses. It was not: the handshake completed, the \
         agent answered the Ono handshake, and the anonymous peer read back the provider \
         inventory §59.1 says it may not see — {reached:?}"
    );
}
