//! The identity this process proves it holds, and the one thing it must never say out loud
//! (v0.4.1 spec §7.2; issue #32).
//!
//! v0.4.1 §7.2 generalises the host-only identity abstraction into a transport-neutral peer
//! identity holding "algorithm, certificate/public material, private key, fingerprint, storage
//! location and creation metadata where available", and then fixes what may leave the object:
//!
//! > The public contract is the fingerprint. The private key MUST never be serialized into
//! > ordinary structured pipeline output, logs, diagnostics or crash messages.
//!
//! A `Debug` rendering is all three of those at once — it is what a log line, a `dbg!` and a
//! panic message all reach for — so this suite routes one identity through every rendering and
//! every error the type can produce and looks for the private key in the output.
//!
//! Everything is generated by the test into a scratch directory, so nothing here needs a
//! network, a certificate authority or a key that matters.
#![allow(
    clippy::expect_used,
    clippy::unwrap_used,
    clippy::panic,
    reason = "a test states its preconditions directly (AGENTS.md section 16)"
)]

use std::path::PathBuf;

use ono_remote::PeerIdentity;

/// A directory this test owns, removed when the test ends.
struct Scratch(PathBuf);

impl Scratch {
    fn new(name: &str) -> Self {
        let path = std::env::temp_dir().join(format!("ono-{name}-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&path);
        std::fs::create_dir_all(&path).expect("a scratch directory is created");
        Self(path)
    }

    fn join(&self, name: &str) -> PathBuf {
        self.0.join(name)
    }
}

impl Drop for Scratch {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

/// The private key inside `pem`, as the DER bytes rustls holds in memory.
fn private_key_der(pem: &str) -> Vec<u8> {
    let mut reader = std::io::BufReader::new(pem.as_bytes());
    let key = rustls_pemfile::private_key(&mut reader)
        .expect("the identity file parses")
        .expect("the identity file has a private key");
    key.secret_der().to_vec()
}

/// Every way a byte string can be written into a diagnostic by accident.
fn spellings(bytes: &[u8]) -> Vec<String> {
    let mut hex = String::new();
    for byte in bytes {
        hex.push_str(&format!("{byte:02x}"));
    }
    let debug = format!("{bytes:?}");
    vec![hex, debug]
}

#[test]
fn should_never_render_private_key_material_in_any_rendering_or_diagnostic() {
    let scratch = Scratch::new("peer-identity");
    let path = scratch.join("link_identity.pem");
    let identity = PeerIdentity::open_or_create(&path).expect("an identity is generated");
    let pem = std::fs::read_to_string(&path).expect("the identity file is readable");
    let secret = private_key_der(&pem);

    // Every rendering and every diagnostic the object can produce, in one place.
    let mut rendered = vec![
        format!("{identity:?}"),
        format!("{identity:#?}"),
        identity.fingerprint().to_string(),
        format!("{:?}", identity.fingerprint()),
        format!("{:?}", identity.peer_key()),
    ];

    // The error paths: a file that is not an identity, and a path nothing can be written to.
    let corrupt = scratch.join("corrupt.pem");
    std::fs::write(&corrupt, "not a pem file at all\n").expect("the corrupt file is written");
    let error = PeerIdentity::open_or_create(&corrupt).expect_err("a non-identity is refused");
    rendered.push(format!("{error:?}"));
    rendered.push(error.message().to_owned());
    rendered.push(error.help().unwrap_or_default().to_owned());

    // A file that holds a real private key and no certificate: the diagnostic has the secret in
    // its hand and must still not print it.
    let headless = scratch.join("headless.pem");
    let key_block = pem
        .find("-----BEGIN PRIVATE KEY-----")
        .map_or_else(String::new, |start| pem[start..].to_owned());
    std::fs::write(&headless, key_block).expect("the key-only file is written");
    if let Err(error) = PeerIdentity::open_or_create(&headless) {
        rendered.push(format!("{error:?}"));
        rendered.push(error.message().to_owned());
        rendered.push(error.help().unwrap_or_default().to_owned());
    }

    for spelling in spellings(&secret) {
        for output in &rendered {
            assert!(
                !output.contains(&spelling),
                "v0.4.1 §7.2: \"the private key MUST never be serialized into ordinary structured \
                 pipeline output, logs, diagnostics or crash messages\". The public contract is \
                 the fingerprint, and this rendering carried the key instead:\n{output}"
            );
        }
    }
}

#[test]
fn should_describe_itself_by_fingerprint_algorithm_and_storage_location() {
    let scratch = Scratch::new("peer-identity-described");
    let path = scratch.join("link_identity.pem");
    let identity = PeerIdentity::open_or_create(&path).expect("an identity is generated");

    let described = format!("{identity:?}");

    assert!(
        described.contains(&identity.fingerprint().to_string()),
        "the fingerprint is the public contract of v0.4.1 §7.2, so it is what an identity says \
         about itself, got {described}"
    );
    assert!(
        described.contains(identity.algorithm()),
        "§7.2 lists the algorithm among what a peer identity carries, got {described}"
    );
    assert!(
        described.contains(&path.display().to_string()),
        "§7.2 lists the storage location among what a peer identity carries, and a person \
         debugging two identities needs to know which file each came from, got {described}"
    );
}

#[test]
fn should_carry_the_public_material_and_the_storage_location_of_the_file_it_came_from() {
    let scratch = Scratch::new("peer-identity-fields");
    let path = scratch.join("link_identity.pem");
    let identity = PeerIdentity::open_or_create(&path).expect("an identity is generated");

    assert_eq!(
        identity.path(),
        Some(path.as_path()),
        "an identity read from a file knows which file (v0.4.1 §7.2 storage location)"
    );
    assert_eq!(
        identity.certificate(),
        identity.peer_key().material(),
        "the public material is what the peer will see this end prove it holds"
    );
    assert!(
        identity.created().is_some(),
        "§7.2 asks for creation metadata where available, and a file has a creation time"
    );

    let ephemeral = PeerIdentity::generate().expect("an in-process identity is generated");
    assert_eq!(
        ephemeral.path(),
        None,
        "an identity that lives only in this process is stored nowhere, and says so rather than \
         naming a file that does not exist"
    );
}

/// v0.4.1 §8.3: the identity file holds a private key, so anyone who can read it can be this
/// peer, and anyone who can write it can replace who this peer is. §59.6 makes the refusal an
/// acceptance scenario: "a world-readable `link_identity.pem` MUST be refused. The diagnostic
/// identifies the path and required permissions without printing key material."
#[test]
fn should_refuse_an_identity_file_that_anyone_else_can_read() {
    use std::os::unix::fs::PermissionsExt as _;

    let scratch = Scratch::new("peer-identity-readable");
    let path = scratch.join("link_identity.pem");
    let generated = PeerIdentity::open_or_create(&path).expect("an identity is generated");
    let fingerprint = generated.fingerprint().to_string();
    drop(generated);
    std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o644))
        .expect("the file is made world-readable");

    let refusal = PeerIdentity::open_or_create(&path)
        .expect_err("a private key everyone on the machine can read is not a private key");

    assert_eq!(
        refusal.code(),
        ono_core::ErrorCode::RemoteIdentityPermissions,
        "v0.4.1 §8.3: \"if it is group/world readable, Ono MUST refuse by default because the \
         private key is exposed\" — and the refusal needs a stable code a script can branch on"
    );
    assert!(
        refusal.retryable() != Some(true),
        "retrying will not change the mode; the refusal must say so"
    );
    let said = format!(
        "{} {}",
        refusal.message(),
        refusal.help().unwrap_or_default()
    );
    assert!(
        said.contains(&path.display().to_string()),
        "§59.6: the diagnostic identifies the path, got {said}"
    );
    assert!(
        said.contains("600"),
        "§59.6: the diagnostic identifies the required permissions, got {said}"
    );
    assert!(
        !said.contains(&fingerprint) && !said.contains("PRIVATE KEY"),
        "§59.6: without printing key material, got {said}"
    );
}

#[test]
fn should_refuse_an_identity_file_that_anyone_else_can_write() {
    use std::os::unix::fs::PermissionsExt as _;

    let scratch = Scratch::new("peer-identity-writable");
    let path = scratch.join("link_identity.pem");
    PeerIdentity::open_or_create(&path).expect("an identity is generated");
    std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o622))
        .expect("the file is made world-writable");

    let refusal = PeerIdentity::open_or_create(&path)
        .expect_err("an identity anyone can replace is an identity nobody proves");

    assert_eq!(
        refusal.code(),
        ono_core::ErrorCode::RemoteIdentityPermissions,
        "v0.4.1 §8.3: \"if an existing identity file is group/world writable, Ono MUST refuse to \
         use it and report a security error\""
    );
}

#[test]
fn should_use_an_identity_file_only_its_owner_can_reach() {
    let scratch = Scratch::new("peer-identity-owner-only");
    let path = scratch.join("link_identity.pem");
    let first = PeerIdentity::open_or_create(&path).expect("an identity is generated 0600");

    let again = PeerIdentity::open_or_create(&path).expect("an owner-only identity is accepted");

    assert_eq!(
        first.fingerprint(),
        again.fingerprint(),
        "the refusal of §8.3 is about exposure, and an owner-only file is not exposed"
    );
}
