//! The transport that certifies its peer to this process (spec §21.5, ADR-0274, ADR-0353).
//!
//! `tests/trust.rs` proves the trust decision over a transport that was *told* what an outer
//! layer authenticated. These suites prove the same refusals over a transport that authenticated
//! the peer itself: a TLS 1.3 handshake this process performed, whose `CertificateVerify` is the
//! peer proving it holds the key it presented. That is the difference between a trust store that
//! is exercised in a test and one that protects a link.
//!
//! Everything runs on the loopback interface with keys generated by the test, so no suite needs a
//! network, a certificate authority or a fixture host.
#![allow(
    clippy::expect_used,
    clippy::unwrap_used,
    clippy::panic,
    reason = "a test states its preconditions directly (AGENTS.md section 16)"
)]

mod common;

use std::sync::Arc;

use common::fixture::{FixtureObserved, fixture_registry, fixture_schemas};
use common::within;
use ono_core::ErrorCode;
use ono_protocol::{ClientConfig, Identity, Transport, TrustPolicy, TrustStore};
use ono_provider_api::Query;
use ono_remote::{AgentConfig, PeerIdentity, RemoteLink, TlsListener, serve_registry, tls_connect};

/// An agent listening on a loopback port the system chooses, serving the fixture registry.
async fn listening(identity: PeerIdentity) -> String {
    let listener = TlsListener::bind("127.0.0.1:0", &identity)
        .await
        .expect("a loopback listener binds");
    let address = listener
        .local_addr()
        .expect("the system reports the port it chose")
        .to_string();
    tokio::spawn(async move {
        while let Ok(transport) = listener.accept().await {
            let registry = fixture_registry(Arc::new(FixtureObserved::default()));
            let config = AgentConfig::new(registry).with_identity(Identity::new("remote-user"));
            tokio::spawn(async move {
                let _ = serve_registry(transport, config).await;
            });
        }
    });
    address
}

/// The identity a connecting client presents (v0.4.1 §7.1). Every suite here dials with one,
/// because there is no way to dial without one.
fn client_identity() -> PeerIdentity {
    PeerIdentity::generate().expect("a client identity is generated")
}

fn config(store: TrustStore, policy: TrustPolicy) -> ClientConfig {
    ClientConfig::new("testbox")
        .with_schemas(fixture_schemas())
        .with_trust_store(store)
        .with_trust_policy(policy)
        .with_identity(Identity::new("tester"))
}

#[tokio::test]
async fn should_report_the_key_the_peer_proved_it_holds() {
    let identity = PeerIdentity::generate().expect("a host identity is generated");
    let expected = identity.peer_key();
    let address = listening(identity).await;

    let transport = within(tls_connect(&address, &client_identity()))
        .await
        .expect("the loopback listener answers");

    assert_eq!(
        transport.peer_key(),
        Some(&expected),
        "spec §21.5: the transport reports what it verified, and here it verified a TLS 1.3 \
         signature made with the key inside the certificate the peer sent"
    );
}

#[tokio::test]
async fn should_pin_a_host_on_first_contact_and_then_refuse_a_changed_key() {
    let first = PeerIdentity::generate().expect("a host identity is generated");
    let pinned = first.fingerprint();
    let address = listening(first).await;
    let store = TrustStore::in_memory();

    let transport = within(tls_connect(&address, &client_identity()))
        .await
        .expect("the host answers");
    let link = within(RemoteLink::connect(
        transport,
        config(store.clone(), TrustPolicy::Required),
    ))
    .await
    .expect("a host nothing is recorded for is recorded on first contact");
    link.hangup();
    assert_eq!(
        store.fingerprint("testbox"),
        Some(pinned),
        "the key the peer proved it holds is what got recorded"
    );

    // The same host name, a different machine answering for it: the case E0603 exists for.
    let impostor = PeerIdentity::generate().expect("a second identity is generated");
    let elsewhere = listening(impostor).await;
    let transport = within(tls_connect(&elsewhere, &client_identity()))
        .await
        .expect("the impostor answers");
    let refusal = within(RemoteLink::connect(
        transport,
        config(store, TrustPolicy::Required),
    ))
    .await
    .expect_err("a peer presenting another key than the pinned one cannot be linked to");

    assert_eq!(
        refusal.code(),
        ErrorCode::RemoteHostKeyChanged,
        "ADR-0015 T6: a changed key is E0603, on a production transport and not only in a fixture"
    );
    assert!(
        refusal.retryable() != Some(true),
        "retrying would not make the key match; the refusal must say so"
    );
}

#[tokio::test]
async fn should_refuse_an_unknown_host_when_only_pinned_hosts_are_accepted() {
    let identity = PeerIdentity::generate().expect("a host identity is generated");
    let address = listening(identity).await;

    let transport = within(tls_connect(&address, &client_identity()))
        .await
        .expect("the host answers");
    let refusal = within(RemoteLink::connect(
        transport,
        config(TrustStore::in_memory(), TrustPolicy::Pinned),
    ))
    .await
    .expect_err("nothing is pinned for this host");

    assert_eq!(
        refusal.code(),
        ErrorCode::SafetyPolicyDenied,
        "ADR-0015 T5: an unknown key is refused, not recorded and not prompted past"
    );
    assert!(
        refusal.message().contains("sha256:")
            || refusal.help().unwrap_or_default().contains("sha256:"),
        "a refusal a person has to act on shows the fingerprint they would have to check, got {refusal:?}"
    );
}

#[tokio::test]
async fn should_carry_the_link_protocol_over_the_authenticated_transport() {
    let identity = PeerIdentity::generate().expect("a host identity is generated");
    let key = identity.peer_key();
    let address = listening(identity).await;

    let store = TrustStore::in_memory();
    store
        .pin("testbox", &key)
        .expect("the key is pinned by hand");
    let transport = within(tls_connect(&address, &client_identity()))
        .await
        .expect("the host answers");
    let link = within(RemoteLink::connect(
        transport,
        config(store, TrustPolicy::Pinned),
    ))
    .await
    .expect("a pinned host is linked to");

    let mut registry = ono_provider_api::ProviderRegistry::new();
    link.register_into(&mut registry);
    let mut stream = registry
        .snapshot(&Query::target("process"))
        .expect("the mounted provider answers `process`");
    let mut values = Vec::new();
    while let Some(event) = within(stream.recv()).await {
        if let ono_pipeline::StreamEvent::Value(value) = event {
            values.push(value);
        }
    }

    assert!(
        !values.is_empty(),
        "the whole link — handshake, negotiation, streams — runs over the authenticated transport"
    );
}

#[tokio::test]
async fn should_keep_one_identity_across_restarts() {
    let directory = std::env::temp_dir().join(format!("ono-tls-{}", std::process::id()));
    let path = directory.join("host_key.pem");
    let _ = std::fs::remove_dir_all(&directory);

    let first = PeerIdentity::open_or_create(&path).expect("an identity is generated and written");
    let again = PeerIdentity::open_or_create(&path).expect("the written identity is read back");

    assert_eq!(
        first.fingerprint(),
        again.fingerprint(),
        "a host that restarts is the same host: an identity that changed on every start would \
         make every pinned peer refuse it (spec §21.5)"
    );
    let mode = std::os::unix::fs::MetadataExt::mode(
        &std::fs::metadata(&path).expect("the identity file exists"),
    );
    assert_eq!(
        mode & 0o777,
        0o600,
        "the file holds the private key that is this host's identity to everyone who pinned it"
    );
    let _ = std::fs::remove_dir_all(&directory);
}
