//! Generated repository metrics (v0.4.1 §50).
//!
//! §50.1 names five counts — crates, unit and integration tests, acceptance cases, ADRs, generated
//! command contracts — and forbids duplicating them across README and docs "without automated
//! verification". §50.2 asks `xtask` to compute them. §50.3 lets the README keep the numbers,
//! "because they are useful evidence", and requires the gate to fail when they disagree.
//!
//! So the README carries a block between two markers, `cargo xtask metrics --write` regenerates
//! it, and `cargo xtask spec-check` compares. The narrative around the block stays human-owned,
//! which is §50.3's other half.
//!
//! **§50.4 is the one that changes what the numbers are named.** *"Generated test counts MUST
//! distinguish executed tests from skips … A README statement such as 'N tests pass' MUST not
//! count skipped cases as proof of execution."* A static reading of the tree cannot know what a
//! run executed, so it does not claim to: `tests` counts test functions **declared**, and two
//! figures beside it say how many of them can announce a skip and how many the canonical CI
//! environment expects to. A reader who wants "how many passed" has `cargo test`'s own summary,
//! and this block never offers a substitute for it.

use std::fmt::Write as _;
use std::path::Path;

use crate::scan::{ExpectedSkips, Problem, rust_sources, skip_sites};

/// The marker the generated block opens with, in the README.
pub const OPEN: &str = "<!-- generated by `cargo xtask metrics`. -->";

/// The marker it closes with.
pub const CLOSE: &str = "<!-- end generated -->";

/// The counts §50.1 names, measured from the tree.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Metrics {
    /// Library crates under `crates/`.
    pub crates: usize,
    /// Cargo workspace members, which is `crates/` plus `xtask` and `fuzz`.
    pub workspace_members: usize,
    /// Test functions declared in the workspace's Rust sources.
    pub tests: usize,
    /// How many of them can announce a skip, per `docs/spec/hardening/expected_test_skips.yaml`.
    pub tests_that_can_skip: usize,
    /// How many skips the canonical CI environment expects. §38.2 prefers this small.
    pub expected_ci_skips: usize,
    /// Cases under `docker/acceptance/cases/`.
    pub acceptance_cases: usize,
    /// Records under `docs/decisions/`.
    pub adrs: usize,
    /// Command contract files under `docs/spec/commands/`.
    pub command_contract_files: usize,
    /// Commands those files declare.
    pub commands: usize,
}

impl Metrics {
    /// §50.2's `key=value` form, one per line, in a fixed order.
    #[must_use]
    pub fn render(&self) -> String {
        let mut text = String::new();
        for (key, value) in self.pairs() {
            let _ = writeln!(text, "{key}={value}");
        }
        text
    }

    /// The block as the README carries it, markers included.
    #[must_use]
    pub fn block(&self) -> String {
        format!("{OPEN}\n\n```text\n{}```\n\n{CLOSE}", self.render())
    }

    fn pairs(&self) -> [(&'static str, usize); 9] {
        [
            ("crates", self.crates),
            ("workspace_members", self.workspace_members),
            ("tests", self.tests),
            ("tests_that_can_skip", self.tests_that_can_skip),
            ("expected_ci_skips", self.expected_ci_skips),
            ("acceptance_cases", self.acceptance_cases),
            ("adrs", self.adrs),
            ("command_contract_files", self.command_contract_files),
            ("commands", self.commands),
        ]
    }
}

/// Measures the repository at `root`.
#[must_use]
pub fn measure(root: &Path) -> Metrics {
    let expected = ExpectedSkips::read(root).unwrap_or_default();
    Metrics {
        crates: directories(&root.join("crates")),
        workspace_members: directories(&root.join("crates")) + 2,
        tests: count_tests(root),
        tests_that_can_skip: skip_sites(root).len(),
        expected_ci_skips: expected.canonical_ci.len(),
        acceptance_cases: files_with_extension(
            &root.join("docker").join("acceptance").join("cases"),
            "case",
        ),
        adrs: named_files(&root.join("docs").join("decisions"), "ADR-", "md"),
        command_contract_files: files_with_extension(
            &root.join("docs").join("spec").join("commands"),
            "yaml",
        ),
        commands: declared_commands(root),
    }
}

/// Reports a README whose generated block disagrees with the tree (§50.3).
#[must_use]
pub fn check_readme(root: &Path) -> Vec<Problem> {
    let Ok(text) = std::fs::read_to_string(root.join("README.md")) else {
        return Vec::new();
    };
    let measured = measure(root);
    match block_in(&text) {
        None => vec![Problem::new(
            "README.md",
            format!(
                "carries no generated metrics block. v0.4.1 §50.3 lets the README keep the \
                 numbers because they are useful evidence, and §50.1 forbids keeping them without \
                 automated verification — so they live between `{OPEN}` and `{CLOSE}`, and \
                 `cargo xtask metrics --write` puts them there."
            ),
        )],
        Some(found) if found.trim() == measured.render().trim() => Vec::new(),
        Some(found) => vec![Problem::new(
            "README.md",
            format!(
                "states repository metrics the tree does not agree with (v0.4.1 §50.3). Run \
                 `cargo xtask metrics --write`.\n    README says:\n{}\n    the tree says:\n{}",
                indent(found.trim()),
                indent(measured.render().trim()),
            ),
        )],
    }
}

/// The text between the two markers, if the document carries both.
fn block_in(text: &str) -> Option<&str> {
    let start = text.find(OPEN)? + OPEN.len();
    let end = text[start..].find(CLOSE)? + start;
    let inner = &text[start..end];
    // The block is a fenced code block between the markers; the fences are presentation.
    let opened = inner.find("```text")? + "```text".len();
    let closed = inner[opened..].find("```")? + opened;
    Some(&inner[opened..closed])
}

/// Rewrites the README's block, returning whether anything changed.
///
/// # Errors
///
/// Returns a message when the README cannot be read or written, or carries no block.
pub fn write_readme(root: &Path) -> Result<bool, String> {
    let path = root.join("README.md");
    let text = std::fs::read_to_string(&path).map_err(|error| format!("README.md: {error}"))?;
    let start = text
        .find(OPEN)
        .ok_or_else(|| format!("README.md carries no `{OPEN}` marker"))?;
    let end = text
        .find(CLOSE)
        .ok_or_else(|| format!("README.md carries no `{CLOSE}` marker"))?
        + CLOSE.len();
    let replaced = format!(
        "{}{}{}",
        &text[..start],
        measure(root).block(),
        &text[end..]
    );
    if replaced == text {
        return Ok(false);
    }
    std::fs::write(&path, replaced).map_err(|error| format!("README.md: {error}"))?;
    Ok(true)
}

/// Indents a block for a multi-line problem detail.
fn indent(text: &str) -> String {
    text.lines()
        .map(|line| format!("      {line}"))
        .collect::<Vec<_>>()
        .join("\n")
}

/// How many directories `path` holds.
fn directories(path: &Path) -> usize {
    std::fs::read_dir(path)
        .into_iter()
        .flatten()
        .flatten()
        .filter(|entry| entry.path().is_dir())
        .count()
}

/// How many files under `path` carry `extension`.
fn files_with_extension(path: &Path, extension: &str) -> usize {
    std::fs::read_dir(path)
        .into_iter()
        .flatten()
        .flatten()
        .filter(|entry| {
            entry
                .path()
                .extension()
                .is_some_and(|found| found == extension)
        })
        .count()
}

/// How many files under `path` are named `<prefix>…​.<extension>`.
fn named_files(path: &Path, prefix: &str, extension: &str) -> usize {
    std::fs::read_dir(path)
        .into_iter()
        .flatten()
        .flatten()
        .filter(|entry| {
            let path = entry.path();
            path.extension().is_some_and(|found| found == extension)
                && path
                    .file_name()
                    .is_some_and(|name| name.to_string_lossy().starts_with(prefix))
        })
        .count()
}

/// How many commands the contract registry declares.
fn declared_commands(root: &Path) -> usize {
    let directory = root.join("docs").join("spec").join("commands");
    let Ok(entries) = std::fs::read_dir(&directory) else {
        return 0;
    };
    entries
        .flatten()
        .map(|entry| entry.path())
        .filter(|path| {
            path.extension()
                .is_some_and(|extension| extension == "yaml")
        })
        .filter_map(|path| std::fs::read_to_string(path).ok())
        .filter_map(|text| serde_yaml_ng::from_str::<serde_yaml_ng::Value>(&text).ok())
        .filter_map(|document| {
            document
                .get("commands")
                .and_then(serde_yaml_ng::Value::as_sequence)
                .map(Vec::len)
        })
        .sum()
}

/// How many test functions the workspace declares.
///
/// Counted from the same tree the scanners walk, with string literals removed first. Without
/// that, `xtask/tests/scan.rs` — whose fixtures are Rust source written at the left margin inside
/// raw strings — contributes about fifteen tests that do not exist, and a count nobody can
/// reproduce with `grep` is a count nobody believes.
fn count_tests(root: &Path) -> usize {
    let mut total = 0;
    for file in rust_sources(root) {
        let Ok(text) = std::fs::read_to_string(&file) else {
            continue;
        };
        total += without_string_literals(&text)
            .lines()
            .filter(|line| {
                let trimmed = line.trim();
                trimmed == "#[test]"
                    || (trimmed.starts_with("#[") && trimmed.contains("test]"))
                    || trimmed.starts_with("#[tokio::test")
            })
            .count();
    }
    total
}

/// `text` with the contents of every string literal blanked out, newlines preserved.
///
/// Handles `"…"` with backslash escapes and `r#"…"#` with any number of hashes, which is every
/// form this repository writes a fixture in. Char literals are left alone: `'"'` would otherwise
/// open a string that never closes, so the scan skips a quote preceded by an apostrophe.
fn without_string_literals(text: &str) -> String {
    let bytes = text.as_bytes();
    let mut kept = String::with_capacity(text.len());
    let mut index = 0;
    while index < bytes.len() {
        let byte = bytes[index];
        // A raw string: `r`, some hashes, a quote. It ends at a quote followed by as many hashes.
        if byte == b'r' {
            let mut hashes = index + 1;
            while hashes < bytes.len() && bytes[hashes] == b'#' {
                hashes += 1;
            }
            if hashes < bytes.len() && bytes[hashes] == b'"' {
                let closing = format!("\"{}", "#".repeat(hashes - index - 1));
                let rest = &text[hashes + 1..];
                let end = rest.find(&closing).map_or(text.len(), |at| hashes + 1 + at);
                blank(&mut kept, &text[index..end]);
                index = (end + closing.len()).min(bytes.len());
                continue;
            }
        }
        if byte == b'"' && !(index > 0 && bytes[index - 1] == b'\'') {
            let mut end = index + 1;
            while end < bytes.len() {
                match bytes[end] {
                    b'\\' => end += 2,
                    b'"' => break,
                    _ => end += 1,
                }
            }
            let end = end.min(bytes.len());
            blank(&mut kept, &text[index..end]);
            index = (end + 1).min(bytes.len());
            continue;
        }
        kept.push(byte as char);
        index += 1;
    }
    kept
}

/// Appends `span` with everything but its newlines removed, so line numbers are unchanged.
fn blank(into: &mut String, span: &str) {
    for character in span.chars() {
        if character == '\n' {
            into.push('\n');
        }
    }
}
