//! The release input manifest of Appendix H (spec §43.2, §57 H10).
//!
//! A release can say what it is. Until now it could not say what it was made of: which action
//! ran, which image the binary was compiled in, which `cargo-deb` laid out the `.deb`, which
//! dependency graph the lockfile resolved to. Appendix H asks that question in one sentence —
//! *what exactly did we trust to produce these bytes?* — and this module answers it in a file the
//! build writes and the release publishes.
//!
//! Two properties matter more than the format:
//!
//! * **it is read from the same files the gate checks.** The action commits and the image digests
//!   come out of `supply_chain::action_references` and `supply_chain::image_references`, the same
//!   two functions the pin scanners use, so the manifest cannot claim a pin the gate never
//!   approved (spec §62.5, and the exit condition of #103);
//! * **unknown is null.** A manifest generated on a developer machine has no workflow run and no
//!   tag, and says so rather than inventing one (spec §35.3).

use std::path::{Path, PathBuf};
use std::process::Command;

use serde_json::{Map, Value, json};

use crate::scan::Problem;
use crate::supply_chain::{action_references, image_references, tool_versions};

/// Where the manifest is written when nothing says otherwise.
pub const MANIFEST_PATH: &str = "dist/build-inputs.json";

/// The identity of the format, so a consumer can tell what it is reading.
///
/// H11 builds provenance and signatures on top of this file. The promise attached to the name is
/// in ADR-0451: these field names, `null` for unknown, and one manifest per release run.
const SCHEMA: &str = "ono.build-inputs.v1";

/// The file `scripts/package-check.sh` validates packages in, as opposed to builds them with.
const PACKAGE_TEST_SOURCE: &str = "scripts/package-check.sh";

/// Assembles the release input manifest for the repository at `root`.
///
/// Every value is read from the working tree, from git, or from the environment of the run. No
/// value is computed twice and none is typed in: the file is a projection of the repository at
/// one commit, so two runs of the same commit in the same run produce the same bytes.
#[must_use]
pub fn build_inputs(root: &Path) -> Value {
    let (build_images, package_test_images): (Vec<_>, Vec<_>) = image_references(root)
        .into_iter()
        .partition(|image| image.file != PACKAGE_TEST_SOURCE);

    json!({
        "schema": SCHEMA,
        "source": {
            "commit": commit(root),
            "tag": tag(root),
            "version": workspace_version(root),
        },
        "toolchain": toolchain(root),
        "lockfile": {
            "path": "Cargo.lock",
            "sha256": lockfile_checksum(root),
        },
        "containers": {
            "build": build_images
                .iter()
                .map(|image| json!({ "file": image.file, "reference": image.value }))
                .collect::<Vec<_>>(),
            "package_test": package_test_images
                .iter()
                .map(|image| json!({ "file": image.file, "reference": image.value }))
                .collect::<Vec<_>>(),
        },
        "actions": action_references(root)
            .iter()
            .map(|action| json!({
                "file": action.file,
                "uses": action.value,
                "version": action.comment,
            }))
            .collect::<Vec<_>>(),
        "tools": tool_versions(root)
            .into_iter()
            .map(|(tool, version)| (tool, Value::String(version)))
            .collect::<Map<_, _>>(),
        "source_date_epoch": source_date_epoch(root),
        "run": run_identity(),
    })
}

/// Writes the manifest, creating the directory it goes in.
///
/// # Errors
///
/// Returns the reason the file could not be written.
pub fn write(root: &Path, output: Option<&Path>) -> Result<PathBuf, String> {
    let path = output.map_or_else(|| root.join(MANIFEST_PATH), Path::to_path_buf);
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|error| format!("cannot create {}: {error}", parent.display()))?;
    }
    let mut text = serde_json::to_string_pretty(&build_inputs(root))
        .map_err(|error| format!("cannot serialise the manifest: {error}"))?;
    text.push('\n');
    std::fs::write(&path, text)
        .map_err(|error| format!("cannot write {}: {error}", path.display()))?;
    Ok(path)
}

/// Checks that the release workflow emits the manifest rather than leaving it to a person.
///
/// Spec §43.2 wants critical release logic in repository-owned scripts with the workflow
/// orchestrating them, and Appendix H wants the manifest generated by the release. A manifest a
/// maintainer writes by hand after the fact is a description of what they believe happened.
#[must_use]
pub fn check_manifest_is_emitted(root: &Path) -> Vec<Problem> {
    let release = root.join(".github").join("workflows").join("release.yml");
    let Ok(text) = std::fs::read_to_string(&release) else {
        return Vec::new();
    };
    if text.contains("build-manifest") {
        return Vec::new();
    }
    vec![Problem {
        location: ".github/workflows/release.yml".to_owned(),
        detail: format!(
            "runs no `xtask build-manifest`, so the release publishes artifacts without saying \
             what produced them. Appendix H asks for the inputs — action commits, image digests, \
             tool versions, toolchain, lockfile hash, `SOURCE_DATE_EPOCH`, run identity — written \
             to `{MANIFEST_PATH}` by the run that builds them (spec §43.2, Appendix H)"
        ),
    }]
}

/// The commit the working tree is at.
fn commit(root: &Path) -> Value {
    git(root, &["rev-parse", "HEAD"])
        .or_else(|| environment("GITHUB_SHA"))
        .map_or(Value::Null, Value::String)
}

/// The tag being released, when there is one.
///
/// The run's own ref wins over `git describe`: a tag push is what a release *is*, and a checkout
/// that happens to sit on an older tag is not one.
fn tag(root: &Path) -> Value {
    if let Some(reference) = environment("GITHUB_REF")
        && let Some(tag) = reference.strip_prefix("refs/tags/")
    {
        return Value::String(tag.to_owned());
    }
    git(root, &["describe", "--tags", "--exact-match"]).map_or(Value::Null, Value::String)
}

/// The version in `[workspace.package]`.
fn workspace_version(root: &Path) -> Value {
    manifest_value(root, &["workspace", "package", "version"])
}

/// What `rust-toolchain.toml` pins (spec §44.3).
fn toolchain(root: &Path) -> Value {
    let text = std::fs::read_to_string(root.join("rust-toolchain.toml")).unwrap_or_default();
    let parsed = toml::from_str::<toml::Value>(&text).ok();
    let field = |name: &str| -> Value {
        parsed
            .as_ref()
            .and_then(|parsed| parsed.get("toolchain"))
            .and_then(|toolchain| toolchain.get(name))
            .map_or(Value::Null, from_toml)
    };
    json!({
        "file": "rust-toolchain.toml",
        "channel": field("channel"),
        "components": field("components"),
        "profile": field("profile"),
    })
}

/// The checksum of the committed lockfile (spec §44.4).
///
/// `sha256sum` rather than a hashing crate, for the reason ADR-0003 gives: the checksum of a file
/// this repository ships should be reproducible with the coreutils command a reader would type.
fn lockfile_checksum(root: &Path) -> Value {
    let output = Command::new("sha256sum")
        .arg("Cargo.lock")
        .current_dir(root)
        .output()
        .ok()
        .filter(|output| output.status.success());
    output
        .and_then(|output| {
            String::from_utf8_lossy(&output.stdout)
                .split_whitespace()
                .next()
                .map(str::to_owned)
        })
        .map_or(Value::Null, Value::String)
}

/// The timestamp every artifact is clamped to (spec §46.2).
///
/// The same derivation `scripts/package.sh` uses, in the same order: the environment when the
/// release sets it, the commit's own time otherwise. A wall clock is never a source.
fn source_date_epoch(root: &Path) -> Value {
    environment("SOURCE_DATE_EPOCH")
        .or_else(|| git(root, &["log", "-1", "--format=%ct"]))
        .map_or(Value::Null, Value::String)
}

/// Which workflow run produced this, when a workflow run did.
fn run_identity() -> Value {
    json!({
        "workflow": environment("GITHUB_WORKFLOW").map_or(Value::Null, Value::String),
        "repository": environment("GITHUB_REPOSITORY").map_or(Value::Null, Value::String),
        "id": environment("GITHUB_RUN_ID").map_or(Value::Null, Value::String),
        "attempt": environment("GITHUB_RUN_ATTEMPT").map_or(Value::Null, Value::String),
        "ref": environment("GITHUB_REF").map_or(Value::Null, Value::String),
        "runner": json!({
            "os": environment("RUNNER_OS").map_or(Value::Null, Value::String),
            "arch": environment("RUNNER_ARCH").map_or(Value::Null, Value::String),
        }),
    })
}

/// A non-empty environment variable, or nothing.
fn environment(name: &str) -> Option<String> {
    std::env::var(name)
        .ok()
        .map(|value| value.trim().to_owned())
        .filter(|value| !value.is_empty())
}

/// The trimmed standard output of a successful git command.
fn git(root: &Path, args: &[&str]) -> Option<String> {
    let output = Command::new("git")
        .args(args)
        .current_dir(root)
        .output()
        .ok()?;
    if !output.status.success() {
        return None;
    }
    let text = String::from_utf8_lossy(&output.stdout).trim().to_owned();
    (!text.is_empty()).then_some(text)
}

/// A value nested in the workspace manifest.
fn manifest_value(root: &Path, path: &[&str]) -> Value {
    let Ok(text) = std::fs::read_to_string(root.join("Cargo.toml")) else {
        return Value::Null;
    };
    let Ok(manifest) = toml::from_str::<toml::Value>(&text) else {
        return Value::Null;
    };
    let mut current = &manifest;
    for key in path {
        match current.get(key) {
            Some(next) => current = next,
            None => return Value::Null,
        }
    }
    from_toml(current)
}

/// The JSON equivalent of a TOML value.
fn from_toml(value: &toml::Value) -> Value {
    match value {
        toml::Value::String(text) => Value::String(text.clone()),
        toml::Value::Integer(number) => Value::from(*number),
        toml::Value::Boolean(flag) => Value::Bool(*flag),
        toml::Value::Array(items) => Value::Array(items.iter().map(from_toml).collect()),
        other => Value::String(other.to_string()),
    }
}

// --- the checksum manifest (spec §47.1, §47.2, ADR-0528) ----------------------------------------

/// The name every release publishes its digests under.
pub const CHECKSUM_MANIFEST: &str = "SHA256SUMS";

/// The assets a release publishes that are *about* the artifacts rather than artifacts.
///
/// The manifest cannot list itself, and it cannot list a signature over itself or a provenance
/// document that quotes its digests without becoming circular. Everything else in the directory
/// is something a reader can download, so everything else is listed (spec §47.2).
const NOT_AN_ARTIFACT: [&str; 6] = [
    CHECKSUM_MANIFEST,
    "SHA256SUMS.sig",
    "SHA256SUMS.pem",
    "SHA256SUMS.sigstore.json",
    PROVENANCE,
    "build-provenance.json.sigstore.json",
];

/// The name the signed build provenance is published under (spec §47.1).
pub const PROVENANCE: &str = "build-provenance.json";

/// Every downloadable artifact in `directory`, in the order the manifest lists them.
///
/// Byte order of the file name, which is what `LC_ALL=C sort` produces and what makes the
/// manifest a deterministic function of the artifacts alone (spec §46.1).
///
/// # Errors
///
/// Returns the reason the directory could not be read.
pub fn downloadable(directory: &Path) -> Result<Vec<(String, Vec<u8>)>, String> {
    let entries = std::fs::read_dir(directory)
        .map_err(|error| format!("cannot read {}: {error}", directory.display()))?;
    let mut found = Vec::new();
    for entry in entries {
        let entry =
            entry.map_err(|error| format!("cannot read {}: {error}", directory.display()))?;
        let path = entry.path();
        let name = entry.file_name().to_string_lossy().into_owned();
        if !path.is_file() || NOT_AN_ARTIFACT.contains(&name.as_str()) {
            continue;
        }
        let bytes = std::fs::read(&path)
            .map_err(|error| format!("cannot read {}: {error}", path.display()))?;
        found.push((name, bytes));
    }
    found.sort_by(|left, right| left.0.cmp(&right.0));
    Ok(found)
}

/// The text of the checksum manifest for `directory`.
///
/// The format is `sha256sum`'s own — digest, two spaces, name — so the command spec §67.7
/// documents for a user is the command that checks it.
///
/// # Errors
///
/// Returns the reason the directory could not be read.
pub fn checksum_manifest(directory: &Path) -> Result<String, String> {
    Ok(downloadable(directory)?
        .iter()
        .map(|(name, bytes)| format!("{}  {name}\n", crate::reproducibility::digest(bytes)))
        .collect())
}

/// Writes `SHA256SUMS` into `directory`.
///
/// # Errors
///
/// Returns the reason the manifest could not be written.
pub fn write_checksums(directory: &Path) -> Result<PathBuf, String> {
    let text = checksum_manifest(directory)?;
    if text.is_empty() {
        return Err(format!(
            "{} holds no downloadable artifact, so a manifest over it would attest to nothing \
             (spec §47.2)",
            directory.display()
        ));
    }
    let path = directory.join(CHECKSUM_MANIFEST);
    std::fs::write(&path, text)
        .map_err(|error| format!("cannot write {}: {error}", path.display()))?;
    Ok(path)
}

/// Checks `SHA256SUMS` against the artifacts beside it, in both directions.
///
/// One direction is `sha256sum -c`: every listed artifact is present and hashes to what the
/// manifest says. The other is the one §47.2 actually asks for and `sha256sum` cannot answer —
/// every artifact *present* is listed. An asset that reached the release after the manifest was
/// written is published unattested, and nothing but this direction notices.
#[must_use]
pub fn check_checksums(directory: &Path) -> Vec<Problem> {
    let location = directory.join(CHECKSUM_MANIFEST).display().to_string();
    let Ok(text) = std::fs::read_to_string(directory.join(CHECKSUM_MANIFEST)) else {
        return vec![Problem {
            location,
            detail: "is missing. Every release publishes the SHA-256 of every downloadable \
                     artifact beside the artifacts (spec §47.1, §47.2)"
                .to_owned(),
        }];
    };
    let listed: Vec<(String, String)> = text
        .lines()
        .filter(|line| !line.trim().is_empty())
        .filter_map(|line| {
            let mut fields = line.split_whitespace();
            Some((fields.next()?.to_owned(), fields.next()?.to_owned()))
        })
        .collect();

    let present = match downloadable(directory) {
        Ok(present) => present,
        Err(error) => {
            return vec![Problem {
                location,
                detail: error,
            }];
        }
    };

    let mut problems = Vec::new();
    for (name, bytes) in &present {
        match listed.iter().find(|(_, listed)| listed == name) {
            None => problems.push(Problem {
                location: location.clone(),
                detail: format!(
                    "does not list `{name}`, which the release publishes. An asset nobody hashed \
                     is an asset nobody can check (spec §47.2, §48.2)"
                ),
            }),
            Some((digest, _)) if *digest != crate::reproducibility::digest(bytes) => {
                problems.push(Problem {
                    location: location.clone(),
                    detail: format!(
                        "records {digest} for `{name}` and the file hashes to {}. The bytes \
                         changed after the manifest was written (spec §47.2, §48.4)",
                        crate::reproducibility::digest(bytes)
                    ),
                });
            }
            Some(_) => {}
        }
    }
    for (_, name) in &listed {
        if !present.iter().any(|(present, _)| present == name) {
            problems.push(Problem {
                location: location.clone(),
                detail: format!(
                    "lists `{name}`, which is not beside it. The release is incomplete, or the \
                     manifest describes a different one (spec §47.2)"
                ),
            });
        }
    }
    problems
}

// --- build provenance (spec §47.4, §62.5, ADR-0530) ---------------------------------------------

/// The statement type, so a consumer can tell what it is reading.
const PROVENANCE_TYPE: &str = "https://in-toto.io/Statement/v1";

/// This project's predicate, versioned the way ADR-0451 versions the input manifest: the name
/// changes when a field's meaning changes.
const PREDICATE_TYPE: &str = "https://github.com/godspeed-you/ono-sendai/provenance/v1";

/// The seven fields §47.4 binds, by the JSON pointer that carries each.
///
/// Six of them are properties of the build. The seventh — the artifact digest — is the `subject`
/// list, and is checked separately because there is one of it per artifact.
const REQUIRED_FIELDS: [(&str, &str); 7] = [
    ("/predicate/repository", "repository"),
    ("/predicate/source_commit", "source_commit"),
    ("/predicate/release_tag", "release_tag"),
    ("/predicate/workflow/name", "workflow.name"),
    ("/predicate/workflow/run_id", "workflow.run_id"),
    ("/predicate/builder/toolchain", "builder.toolchain"),
    ("/predicate/build_timestamp", "build_timestamp"),
];

/// Assembles the build provenance for a release directory.
///
/// Every field comes from the release input manifest of Appendix H (ADR-0451) or from the
/// environment of the run that is generating it — never from the artifacts. §47.4 requires the
/// provenance to be produced by the trusted release workflow rather than supplied by the build,
/// so the run's own environment wins wherever it says anything: a workflow can be trusted about
/// its own identity, and a file that travelled with the build cannot.
///
/// # Errors
///
/// Returns the reason the directory or the input manifest could not be read.
pub fn build_provenance(directory: &Path, inputs: Option<&Path>) -> Result<Value, String> {
    let manifest = inputs.map_or_else(|| directory.join("build-inputs.json"), Path::to_path_buf);
    let recorded: Value = std::fs::read_to_string(&manifest)
        .map_err(|error| {
            format!(
                "cannot read {}: {error}. Provenance is written from the release input manifest \
                 of Appendix H, so the manifest has to be beside the artifacts (ADR-0451)",
                manifest.display()
            )
        })
        .and_then(|text| {
            serde_json::from_str(&text)
                .map_err(|error| format!("{} is not JSON: {error}", manifest.display()))
        })?;

    let recorded_at = |pointer: &str| -> Value {
        recorded
            .pointer(pointer)
            .filter(|value| !value.is_null())
            .cloned()
            .unwrap_or(Value::Null)
    };
    let from_run = |name: &str, pointer: &str| -> Value {
        environment(name).map_or_else(|| recorded_at(pointer), Value::String)
    };

    let repository = from_run("GITHUB_REPOSITORY", "/run/repository");
    let reference = from_run("GITHUB_REF", "/run/ref");
    let tag = reference
        .as_str()
        .and_then(|reference| reference.strip_prefix("refs/tags/"))
        .map_or_else(
            || recorded_at("/source/tag"),
            |tag| Value::String(tag.to_owned()),
        );

    let mut subjects = Vec::new();
    for (name, bytes) in downloadable(directory)? {
        subjects.push(json!({
            "name": name,
            "digest": { "sha256": crate::reproducibility::digest(&bytes) },
        }));
    }
    // The checksum manifest is a subject in its own right: it is the file the signature covers,
    // and a provenance that did not bind it would leave the one file a reader trusts unattested.
    let manifest_path = directory.join(CHECKSUM_MANIFEST);
    if let Ok(bytes) = std::fs::read(&manifest_path) {
        subjects.push(json!({
            "name": CHECKSUM_MANIFEST,
            "digest": { "sha256": crate::reproducibility::digest(&bytes) },
        }));
    }
    subjects.sort_by(|left, right| left["name"].as_str().cmp(&right["name"].as_str()));

    Ok(json!({
        "_type": PROVENANCE_TYPE,
        "predicateType": PREDICATE_TYPE,
        "subject": subjects,
        "predicate": {
            "schema": "ono.build-provenance.v1",
            "repository": repository.clone(),
            "source_commit": from_run("GITHUB_SHA", "/source/commit"),
            "release_tag": tag,
            "workflow": {
                "name": from_run("GITHUB_WORKFLOW", "/run/workflow"),
                "run_id": from_run("GITHUB_RUN_ID", "/run/id"),
                "run_attempt": from_run("GITHUB_RUN_ATTEMPT", "/run/attempt"),
                "ref": reference,
                "runner": recorded_at("/run/runner"),
            },
            "builder": {
                "id": builder_identity(&repository),
                "toolchain": recorded_at("/toolchain/channel"),
                "tools": recorded_at("/tools"),
            },
            "build_timestamp": build_timestamp(&recorded_at("/source_date_epoch")),
            "inputs": {
                "manifest": manifest
                    .file_name()
                    .map_or(Value::Null, |name| Value::String(name.to_string_lossy().into_owned())),
                "lockfile_sha256": recorded_at("/lockfile/sha256"),
                "containers": recorded_at("/containers"),
            },
        },
    }))
}

/// The workflow that is allowed to produce provenance, spelled the way a verifier pins it.
///
/// The same identity `scripts/verify-release.sh` demands of the signature, so "who signed this"
/// and "who says it was built here" are one answer rather than two (ADR-0529).
fn builder_identity(repository: &Value) -> Value {
    repository.as_str().map_or(Value::Null, |repository| {
        Value::String(format!(
            "https://github.com/{repository}/.github/workflows/release.yml"
        ))
    })
}

/// `SOURCE_DATE_EPOCH` as an RFC 3339 instant in UTC.
///
/// §46.2 forbids a wall-clock build time where a reproducible equivalent exists, and one does:
/// the epoch every artifact in the release is already stamped with. A provenance dated by the
/// moment it was written would disagree with the packages it describes.
fn build_timestamp(epoch: &Value) -> Value {
    let Some(seconds) = epoch.as_str().and_then(|text| text.parse::<i64>().ok()) else {
        return Value::Null;
    };
    let (days, rest) = (seconds.div_euclid(86_400), seconds.rem_euclid(86_400));
    let (hour, minute, second) = (rest / 3600, (rest % 3600) / 60, rest % 60);

    // Days since 1970-01-01 to a civil date, by Howard Hinnant's algorithm.
    let z = days + 719_468;
    let era = z.div_euclid(146_097);
    let day_of_era = z.rem_euclid(146_097);
    let year_of_era =
        (day_of_era - day_of_era / 1460 + day_of_era / 36_524 - day_of_era / 146_096) / 365;
    let day_of_year = day_of_era - (365 * year_of_era + year_of_era / 4 - year_of_era / 100);
    let shifted_month = (5 * day_of_year + 2) / 153;
    let day = day_of_year - (153 * shifted_month + 2) / 5 + 1;
    let month = if shifted_month < 10 {
        shifted_month + 3
    } else {
        shifted_month - 9
    };
    let year = era * 400 + year_of_era + i64::from(month <= 2);

    Value::String(format!(
        "{year:04}-{month:02}-{day:02}T{hour:02}:{minute:02}:{second:02}Z"
    ))
}

/// Writes `build-provenance.json` into a release directory.
///
/// # Errors
///
/// Returns the reason the document could not be assembled or written.
pub fn write_provenance(directory: &Path, inputs: Option<&Path>) -> Result<PathBuf, String> {
    let document = build_provenance(directory, inputs)?;
    let mut text = serde_json::to_string_pretty(&document)
        .map_err(|error| format!("cannot serialise the provenance: {error}"))?;
    text.push('\n');
    let path = directory.join(PROVENANCE);
    std::fs::write(&path, text)
        .map_err(|error| format!("cannot write {}: {error}", path.display()))?;
    Ok(path)
}

/// Checks the provenance against the artifacts and the checksum manifest beside it (spec §62.5).
///
/// Three questions, all of which have to hold before publication: is every one of §47.4's fields
/// bound; is every published artifact a subject at the digest it actually has; and does the
/// checksum manifest agree with the provenance about every one of them.
#[must_use]
pub fn check_provenance(directory: &Path) -> Vec<Problem> {
    let path = directory.join(PROVENANCE);
    let location = path.display().to_string();
    let document: Value = match std::fs::read_to_string(&path)
        .map_err(|error| error.to_string())
        .and_then(|text| serde_json::from_str(&text).map_err(|error| error.to_string()))
    {
        Ok(document) => document,
        Err(error) => {
            return vec![Problem {
                location,
                detail: format!(
                    "cannot be read: {error}. A release publishes provenance beside the packages, \
                     bound to every artifact digest (spec §47.1, §47.4)"
                ),
            }];
        }
    };

    let mut problems = Vec::new();
    for (pointer, field) in REQUIRED_FIELDS {
        let bound = document
            .pointer(pointer)
            .is_some_and(|value| value.as_str().is_some_and(|text| !text.is_empty()));
        if !bound {
            problems.push(Problem {
                location: location.clone(),
                detail: format!(
                    "does not bind `{field}`. §47.4 names seven things provenance binds, and an \
                     unbound one is a question this document was written to answer"
                ),
            });
        }
    }

    let subjects: Vec<(String, String)> = document["subject"]
        .as_array()
        .map(|subjects| {
            subjects
                .iter()
                .filter_map(|subject| {
                    Some((
                        subject["name"].as_str()?.to_owned(),
                        subject["digest"]["sha256"].as_str()?.to_owned(),
                    ))
                })
                .collect()
        })
        .unwrap_or_default();

    let published = match downloadable(directory) {
        Ok(published) => published,
        Err(error) => {
            return vec![Problem {
                location,
                detail: error,
            }];
        }
    };
    let manifest = std::fs::read(directory.join(CHECKSUM_MANIFEST)).ok();
    let listed: Vec<(String, String)> = manifest
        .as_ref()
        .map(|bytes| String::from_utf8_lossy(bytes).into_owned())
        .unwrap_or_default()
        .lines()
        .filter_map(|line| {
            let mut fields = line.split_whitespace();
            Some((fields.next()?.to_owned(), fields.next()?.to_owned()))
        })
        .collect();

    // §66.7: all published artifacts, and the manifest that lists them.
    let mut expected: Vec<(String, String)> = published
        .iter()
        .map(|(name, bytes)| (name.clone(), crate::reproducibility::digest(bytes)))
        .collect();
    if let Some(bytes) = &manifest {
        expected.push((
            CHECKSUM_MANIFEST.to_owned(),
            crate::reproducibility::digest(bytes),
        ));
    }

    for (name, digest) in &expected {
        match subjects.iter().find(|(subject, _)| subject == name) {
            None => problems.push(Problem {
                location: location.clone(),
                detail: format!(
                    "does not name `{name}`, which the release publishes. §66.7 asks provenance \
                     to bind all published artifacts, not the binary while the packages go \
                     unattested"
                ),
            }),
            Some((_, bound)) if bound != digest => problems.push(Problem {
                location: location.clone(),
                detail: format!(
                    "binds {bound} to `{name}`, and the file beside it hashes to {digest}. The \
                     artifact is not the one this provenance describes (spec §62.5, §48.4)"
                ),
            }),
            Some(_) => {}
        }
        if name == CHECKSUM_MANIFEST {
            continue;
        }
        match listed.iter().find(|(_, listed)| listed == name) {
            None => {}
            Some((checksum, _)) if checksum != digest => problems.push(Problem {
                location: location.clone(),
                detail: format!(
                    "and `{CHECKSUM_MANIFEST}` disagree about `{name}`: {digest} against \
                     {checksum} (spec §62.5)"
                ),
            }),
            Some(_) => {}
        }
    }

    for (name, _) in &subjects {
        if !expected.iter().any(|(published, _)| published == name) {
            problems.push(Problem {
                location: location.clone(),
                detail: format!(
                    "names `{name}`, which is not in the release. The provenance describes a \
                     different set of bytes (spec §62.5)"
                ),
            });
        }
    }
    problems
}
