//! The release input manifest of Appendix H (spec §43.2, §57 H10).
//!
//! A release can say what it is. Until now it could not say what it was made of: which action
//! ran, which image the binary was compiled in, which `cargo-deb` laid out the `.deb`, which
//! dependency graph the lockfile resolved to. Appendix H asks that question in one sentence —
//! *what exactly did we trust to produce these bytes?* — and this module answers it in a file the
//! build writes and the release publishes.
//!
//! Two properties matter more than the format:
//!
//! * **it is read from the same files the gate checks.** The action commits and the image digests
//!   come out of `supply_chain::action_references` and `supply_chain::image_references`, the same
//!   two functions the pin scanners use, so the manifest cannot claim a pin the gate never
//!   approved (spec §62.5, and the exit condition of #103);
//! * **unknown is null.** A manifest generated on a developer machine has no workflow run and no
//!   tag, and says so rather than inventing one (spec §35.3).

use std::path::{Path, PathBuf};
use std::process::Command;

use serde_json::{Map, Value, json};

use crate::scan::Problem;
use crate::supply_chain::{action_references, image_references, tool_versions};

/// Where the manifest is written when nothing says otherwise.
pub const MANIFEST_PATH: &str = "dist/build-inputs.json";

/// The identity of the format, so a consumer can tell what it is reading.
///
/// H11 builds provenance and signatures on top of this file. The promise attached to the name is
/// in ADR-0451: these field names, `null` for unknown, and one manifest per release run.
const SCHEMA: &str = "ono.build-inputs.v1";

/// The file `scripts/package-check.sh` validates packages in, as opposed to builds them with.
const PACKAGE_TEST_SOURCE: &str = "scripts/package-check.sh";

/// Assembles the release input manifest for the repository at `root`.
///
/// Every value is read from the working tree, from git, or from the environment of the run. No
/// value is computed twice and none is typed in: the file is a projection of the repository at
/// one commit, so two runs of the same commit in the same run produce the same bytes.
#[must_use]
pub fn build_inputs(root: &Path) -> Value {
    let (build_images, package_test_images): (Vec<_>, Vec<_>) = image_references(root)
        .into_iter()
        .partition(|image| image.file != PACKAGE_TEST_SOURCE);

    json!({
        "schema": SCHEMA,
        "source": {
            "commit": commit(root),
            "tag": tag(root),
            "version": workspace_version(root),
        },
        "toolchain": toolchain(root),
        "lockfile": {
            "path": "Cargo.lock",
            "sha256": lockfile_checksum(root),
        },
        "containers": {
            "build": build_images
                .iter()
                .map(|image| json!({ "file": image.file, "reference": image.value }))
                .collect::<Vec<_>>(),
            "package_test": package_test_images
                .iter()
                .map(|image| json!({ "file": image.file, "reference": image.value }))
                .collect::<Vec<_>>(),
        },
        "actions": action_references(root)
            .iter()
            .map(|action| json!({
                "file": action.file,
                "uses": action.value,
                "version": action.comment,
            }))
            .collect::<Vec<_>>(),
        "tools": tool_versions(root)
            .into_iter()
            .map(|(tool, version)| (tool, Value::String(version)))
            .collect::<Map<_, _>>(),
        "source_date_epoch": source_date_epoch(root),
        "run": run_identity(),
    })
}

/// Writes the manifest, creating the directory it goes in.
///
/// # Errors
///
/// Returns the reason the file could not be written.
pub fn write(root: &Path, output: Option<&Path>) -> Result<PathBuf, String> {
    let path = output.map_or_else(|| root.join(MANIFEST_PATH), Path::to_path_buf);
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|error| format!("cannot create {}: {error}", parent.display()))?;
    }
    let mut text = serde_json::to_string_pretty(&build_inputs(root))
        .map_err(|error| format!("cannot serialise the manifest: {error}"))?;
    text.push('\n');
    std::fs::write(&path, text)
        .map_err(|error| format!("cannot write {}: {error}", path.display()))?;
    Ok(path)
}

/// Checks that the release workflow emits the manifest rather than leaving it to a person.
///
/// Spec §43.2 wants critical release logic in repository-owned scripts with the workflow
/// orchestrating them, and Appendix H wants the manifest generated by the release. A manifest a
/// maintainer writes by hand after the fact is a description of what they believe happened.
#[must_use]
pub fn check_manifest_is_emitted(root: &Path) -> Vec<Problem> {
    let release = root.join(".github").join("workflows").join("release.yml");
    let Ok(text) = std::fs::read_to_string(&release) else {
        return Vec::new();
    };
    if text.contains("build-manifest") {
        return Vec::new();
    }
    vec![Problem {
        location: ".github/workflows/release.yml".to_owned(),
        detail: format!(
            "runs no `xtask build-manifest`, so the release publishes artifacts without saying \
             what produced them. Appendix H asks for the inputs — action commits, image digests, \
             tool versions, toolchain, lockfile hash, `SOURCE_DATE_EPOCH`, run identity — written \
             to `{MANIFEST_PATH}` by the run that builds them (spec §43.2, Appendix H)"
        ),
    }]
}

/// The commit the working tree is at.
fn commit(root: &Path) -> Value {
    git(root, &["rev-parse", "HEAD"])
        .or_else(|| environment("GITHUB_SHA"))
        .map_or(Value::Null, Value::String)
}

/// The tag being released, when there is one.
///
/// The run's own ref wins over `git describe`: a tag push is what a release *is*, and a checkout
/// that happens to sit on an older tag is not one.
fn tag(root: &Path) -> Value {
    if let Some(reference) = environment("GITHUB_REF")
        && let Some(tag) = reference.strip_prefix("refs/tags/")
    {
        return Value::String(tag.to_owned());
    }
    git(root, &["describe", "--tags", "--exact-match"]).map_or(Value::Null, Value::String)
}

/// The version in `[workspace.package]`.
fn workspace_version(root: &Path) -> Value {
    manifest_value(root, &["workspace", "package", "version"])
}

/// What `rust-toolchain.toml` pins (spec §44.3).
fn toolchain(root: &Path) -> Value {
    let text = std::fs::read_to_string(root.join("rust-toolchain.toml")).unwrap_or_default();
    let parsed = toml::from_str::<toml::Value>(&text).ok();
    let field = |name: &str| -> Value {
        parsed
            .as_ref()
            .and_then(|parsed| parsed.get("toolchain"))
            .and_then(|toolchain| toolchain.get(name))
            .map_or(Value::Null, from_toml)
    };
    json!({
        "file": "rust-toolchain.toml",
        "channel": field("channel"),
        "components": field("components"),
        "profile": field("profile"),
    })
}

/// The checksum of the committed lockfile (spec §44.4).
///
/// `sha256sum` rather than a hashing crate, for the reason ADR-0003 gives: the checksum of a file
/// this repository ships should be reproducible with the coreutils command a reader would type.
fn lockfile_checksum(root: &Path) -> Value {
    let output = Command::new("sha256sum")
        .arg("Cargo.lock")
        .current_dir(root)
        .output()
        .ok()
        .filter(|output| output.status.success());
    output
        .and_then(|output| {
            String::from_utf8_lossy(&output.stdout)
                .split_whitespace()
                .next()
                .map(str::to_owned)
        })
        .map_or(Value::Null, Value::String)
}

/// The timestamp every artifact is clamped to (spec §46.2).
///
/// The same derivation `scripts/package.sh` uses, in the same order: the environment when the
/// release sets it, the commit's own time otherwise. A wall clock is never a source.
fn source_date_epoch(root: &Path) -> Value {
    environment("SOURCE_DATE_EPOCH")
        .or_else(|| git(root, &["log", "-1", "--format=%ct"]))
        .map_or(Value::Null, Value::String)
}

/// Which workflow run produced this, when a workflow run did.
fn run_identity() -> Value {
    json!({
        "workflow": environment("GITHUB_WORKFLOW").map_or(Value::Null, Value::String),
        "repository": environment("GITHUB_REPOSITORY").map_or(Value::Null, Value::String),
        "id": environment("GITHUB_RUN_ID").map_or(Value::Null, Value::String),
        "attempt": environment("GITHUB_RUN_ATTEMPT").map_or(Value::Null, Value::String),
        "ref": environment("GITHUB_REF").map_or(Value::Null, Value::String),
        "runner": json!({
            "os": environment("RUNNER_OS").map_or(Value::Null, Value::String),
            "arch": environment("RUNNER_ARCH").map_or(Value::Null, Value::String),
        }),
    })
}

/// A non-empty environment variable, or nothing.
fn environment(name: &str) -> Option<String> {
    std::env::var(name)
        .ok()
        .map(|value| value.trim().to_owned())
        .filter(|value| !value.is_empty())
}

/// The trimmed standard output of a successful git command.
fn git(root: &Path, args: &[&str]) -> Option<String> {
    let output = Command::new("git")
        .args(args)
        .current_dir(root)
        .output()
        .ok()?;
    if !output.status.success() {
        return None;
    }
    let text = String::from_utf8_lossy(&output.stdout).trim().to_owned();
    (!text.is_empty()).then_some(text)
}

/// A value nested in the workspace manifest.
fn manifest_value(root: &Path, path: &[&str]) -> Value {
    let Ok(text) = std::fs::read_to_string(root.join("Cargo.toml")) else {
        return Value::Null;
    };
    let Ok(manifest) = toml::from_str::<toml::Value>(&text) else {
        return Value::Null;
    };
    let mut current = &manifest;
    for key in path {
        match current.get(key) {
            Some(next) => current = next,
            None => return Value::Null,
        }
    }
    from_toml(current)
}

/// The JSON equivalent of a TOML value.
fn from_toml(value: &toml::Value) -> Value {
    match value {
        toml::Value::String(text) => Value::String(text.clone()),
        toml::Value::Integer(number) => Value::from(*number),
        toml::Value::Boolean(flag) => Value::Bool(*flag),
        toml::Value::Array(items) => Value::Array(items.iter().map(from_toml).collect()),
        other => Value::String(other.to_string()),
    }
}
