//! Generating `docs/reference/` from the registries (spec §36.2).
//!
//! Spec §36 is explicit that the machine-readable registries "become executable contracts" and
//! that documentation is derived from them. Deriving it is only half the job: the gate also
//! compares what is committed against what the generator produces, because a generator nobody
//! checks against the tree is a generator whose output has quietly diverged
//! (`docs/ACCEPTANCE.md` §4.5).

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use serde_yaml_ng::Value as Yaml;

pub use crate::scan::Problem;

/// The banner every generated page carries.
const BANNER: &str = "<!-- generated by `cargo xtask docs` from docs/spec/. Do not edit by hand: \
your changes will be overwritten and the gate will fail (AGENTS.md section 2). -->";

/// One generated page.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Page {
    /// Where the page belongs, relative to the repository root.
    pub path: String,
    /// The page's complete contents.
    pub contents: String,
}

/// Why generation could not run.
#[derive(Debug)]
pub struct GenerateError {
    /// What went wrong, phrased for the reader.
    pub detail: String,
}

impl std::fmt::Display for GenerateError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.detail)
    }
}

impl std::error::Error for GenerateError {}

/// Generates every reference page from the registries under `root/docs/spec`.
///
/// # Errors
///
/// Returns a [`GenerateError`] if `docs/spec/` is missing or a registry is not valid YAML.
pub fn generate(root: &Path) -> Result<Vec<Page>, GenerateError> {
    let spec = root.join("docs").join("spec");
    if !spec.is_dir() {
        return Err(GenerateError {
            detail: format!("{} does not exist", spec.display()),
        });
    }

    let verbs = load(&spec.join("verbs.yaml"))?;
    let targets = load(&spec.join("targets.yaml"))?;
    let errors = load(&spec.join("errors.yaml"))?;
    let capabilities = load(&spec.join("capabilities.yaml"))?;
    let schemas = load_directory(&spec.join("schemas"))?;
    let commands = load_directory(&spec.join("commands"))?;

    let pages = vec![
        Page {
            path: "docs/reference/README.md".to_owned(),
            contents: index_page(),
        },
        Page {
            path: "docs/reference/commands.md".to_owned(),
            contents: commands_page(&commands),
        },
        Page {
            path: "docs/reference/verbs.md".to_owned(),
            contents: verbs_page(verbs.as_ref()),
        },
        Page {
            path: "docs/reference/targets.md".to_owned(),
            contents: targets_page(targets.as_ref()),
        },
        Page {
            path: "docs/reference/schemas.md".to_owned(),
            contents: schemas_page(&schemas),
        },
        Page {
            path: "docs/reference/errors.md".to_owned(),
            contents: errors_page(errors.as_ref()),
        },
        Page {
            path: "docs/reference/capabilities.md".to_owned(),
            contents: capabilities_page(capabilities.as_ref()),
        },
    ];
    Ok(pages)
}

/// Compares the committed reference docs with what the registries would produce.
#[must_use]
pub fn check_committed(root: &Path) -> Vec<Problem> {
    let generated = match generate(root) {
        Ok(pages) => pages,
        Err(_) => return Vec::new(),
    };

    let mut problems = Vec::new();
    for page in generated {
        let path = root.join(&page.path);
        match std::fs::read_to_string(&path) {
            Ok(committed) if committed == page.contents => {}
            Ok(_) => problems.push(Problem {
                location: page.path.clone(),
                detail: "does not match what the registries produce; run `cargo xtask docs` \
                         (spec §36.2). If the difference is deliberate, the registry is where it \
                         belongs, not the page"
                    .to_owned(),
            }),
            Err(_) => problems.push(Problem {
                location: page.path.clone(),
                detail: "is missing; run `cargo xtask docs`".to_owned(),
            }),
        }
    }
    problems
}

/// Writes every generated page to disk.
///
/// # Errors
///
/// Returns a [`GenerateError`] if generation fails or a page cannot be written.
pub fn write(root: &Path) -> Result<Vec<String>, GenerateError> {
    let mut written = Vec::new();
    for page in generate(root)? {
        let path = root.join(&page.path);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).map_err(|error| GenerateError {
                detail: format!("cannot create {}: {error}", parent.display()),
            })?;
        }
        std::fs::write(&path, &page.contents).map_err(|error| GenerateError {
            detail: format!("cannot write {}: {error}", path.display()),
        })?;
        written.push(page.path);
    }
    Ok(written)
}

// --- pages -----------------------------------------------------------------------------------

fn header(title: &str, blurb: &str) -> String {
    format!("{BANNER}\n\n# {title}\n\n{blurb}\n")
}

fn index_page() -> String {
    let mut page = header(
        "Ono-Sendai reference",
        "Derived from the machine-readable contracts in `docs/spec/`, which are the public \
         contract of the product (spec section 27). The narrative specification explains intent; \
         these pages state what the shell promises.",
    );
    page.push_str(
        "\n| Page | Contract |\n\
         |---|---|\n\
         | [Commands](commands.md) | `docs/spec/commands/*.yaml` — every command, its schemas, \
         selectors, options and examples |\n\
         | [Verbs](verbs.md) | `docs/spec/verbs.yaml` — the controlled vocabulary of spec §7 |\n\
         | [Targets](targets.md) | `docs/spec/targets.yaml` — the nouns of spec §8 |\n\
         | [Schemas](schemas.md) | `docs/spec/schemas/*.v1.yaml` — the object contracts of spec §28 |\n\
         | [Errors](errors.md) | `docs/spec/errors.yaml` — the stable taxonomy of spec §43 |\n\
         | [Capabilities](capabilities.md) | `docs/spec/capabilities.yaml` — provider and KUANG/11 \
         capabilities |\n\
         \nA command marked **planned** has a contract and no implementation: spec §52 asks that \
         its usefulness be validated rather than implemented for symmetry, and the registry \
         records the design surface without promising the command.\n",
    );
    page
}

fn commands_page(families: &BTreeMap<String, Yaml>) -> String {
    let mut page = header(
        "Command reference",
        "Every command Ono defines, grouped by family. `stability` says whether the contract is a \
         promise; `phase` says which phase of spec §37 delivers it.",
    );

    for (file, document) in families {
        let family = string_at(document, "family").unwrap_or_else(|| file.clone());
        let _ = write!(page, "\n## {family}\n");

        for command in sequence(document, "commands") {
            let id = string_at(command, "id").unwrap_or_default();
            let verb = string_at(command, "verb").unwrap_or_default();
            let target = string_at(command, "target").unwrap_or_default();
            let invocation = if target.is_empty() || target == "null" {
                verb.clone()
            } else {
                format!("{verb} {target}")
            };

            let _ = write!(page, "\n### `{invocation}`\n\n");
            let _ = writeln!(
                page,
                "{}\n",
                string_at(command, "summary").unwrap_or_default()
            );
            let _ = writeln!(page, "| | |\n|---|---|");
            let _ = writeln!(page, "| id | `{id}` |");
            let _ = writeln!(
                page,
                "| stability | {} |",
                string_at(command, "stability").unwrap_or_else(|| "unspecified".to_owned())
            );
            let _ = writeln!(
                page,
                "| phase | {} |",
                string_at(command, "phase").unwrap_or_else(|| "unspecified".to_owned())
            );
            let _ = writeln!(
                page,
                "| input | `{}` |",
                string_at(command, "input").unwrap_or_else(|| "null".to_owned())
            );
            let _ = writeln!(
                page,
                "| output | `{}` |",
                string_at(command, "output").unwrap_or_else(|| "null".to_owned())
            );
            if let Some(capability) = string_at(command, "provider_capability") {
                let _ = writeln!(page, "| provider capability | `{capability}` |");
            }
            let _ = writeln!(
                page,
                "| privilege | {} |",
                string_at(command, "privilege").unwrap_or_else(|| "none".to_owned())
            );
            let _ = writeln!(
                page,
                "| arguments | parsed in {} mode (ADR-0009) |",
                string_at(command, "argument_mode").unwrap_or_else(|| "words".to_owned())
            );

            let selectors = sequence(command, "selectors");
            if !selectors.is_empty() {
                let _ = write!(
                    page,
                    "\n**Selectors**\n\n| name | type | meaning |\n|---|---|---|\n"
                );
                for selector in selectors {
                    let _ = writeln!(
                        page,
                        "| `{}` | `{}` | {} |",
                        string_at(selector, "name").unwrap_or_default(),
                        string_at(selector, "type").unwrap_or_default(),
                        string_at(selector, "doc").unwrap_or_default()
                    );
                }
            }

            let options = sequence(command, "options");
            if !options.is_empty() {
                let _ = write!(
                    page,
                    "\n**Options**\n\n| name | type | meaning |\n|---|---|---|\n"
                );
                for option in options {
                    let _ = writeln!(
                        page,
                        "| `--{}` | `{}` | {} |",
                        string_at(option, "name").unwrap_or_default(),
                        string_at(option, "type").unwrap_or_default(),
                        string_at(option, "doc").unwrap_or_default()
                    );
                }
            }

            let examples = string_sequence(command, "examples");
            if !examples.is_empty() {
                page.push_str("\n**Examples**\n\n```text\n");
                for example in examples {
                    let _ = writeln!(page, "{example}");
                }
                page.push_str("```\n");
            }
        }
    }
    page
}

fn verbs_page(document: Option<&Yaml>) -> String {
    let mut page = header(
        "Verbs",
        "The controlled vocabulary of spec §7. The registry is deliberately small: a module reuses \
         an existing verb whenever the semantics match, and spec §40.1 requires a review before a \
         new one is added.",
    );
    page.push_str(
        "\n| verb | meaning | typical targets | pipeline role | mutates |\n|---|---|---|---|---|\n",
    );
    for verb in document.map(|d| sequence(d, "verbs")).unwrap_or_default() {
        let _ = writeln!(
            page,
            "| `{}` | {} | {} | {} | {} |",
            string_at(verb, "verb").unwrap_or_default(),
            string_at(verb, "semantics").unwrap_or_default(),
            string_sequence(verb, "typical_targets").join(", "),
            string_at(verb, "pipeline_role").unwrap_or_default(),
            if verb.get("mutating").and_then(Yaml::as_bool) == Some(true) {
                "yes"
            } else {
                "no"
            }
        );
    }
    page
}

fn targets_page(document: Option<&Yaml>) -> String {
    let mut page = header(
        "Targets",
        "The nouns of spec §8 — the resources a verb acts on. `schema` names the object contract a \
         target's commands produce.",
    );
    page.push_str("\n| target | category | schema | phase | meaning |\n|---|---|---|---|---|\n");
    for target in document.map(|d| sequence(d, "targets")).unwrap_or_default() {
        let schema = string_at(target, "schema").unwrap_or_else(|| "—".to_owned());
        let _ = writeln!(
            page,
            "| `{}` | {} | `{schema}` | {} | {} |",
            string_at(target, "name").unwrap_or_default(),
            string_at(target, "category").unwrap_or_default(),
            string_at(target, "phase").unwrap_or_else(|| "—".to_owned()),
            string_at(target, "summary").unwrap_or_default()
        );
    }
    page
}

fn schemas_page(files: &BTreeMap<String, Yaml>) -> String {
    let mut page = header(
        "Object schemas",
        "The object contracts of spec §28. A **nullable** field may be `null`, which means the \
         value is unknown — never that it is zero or empty (spec §10.5). `identity` is what makes \
         two observations of the same object the same object.",
    );

    for (file, document) in files {
        if file.ends_with("deferred.yaml") {
            continue;
        }
        let id = string_at(document, "id").unwrap_or_default();
        let name = string_at(document, "name").unwrap_or_default();
        let _ = write!(page, "\n## {name} — `{id}`\n\n");
        let _ = writeln!(
            page,
            "{}\n",
            string_at(document, "summary").unwrap_or_default()
        );
        let _ = writeln!(
            page,
            "Identity: {}",
            string_sequence(document, "identity")
                .iter()
                .map(|field| format!("`{field}`"))
                .collect::<Vec<_>>()
                .join(", ")
        );
        let columns = document
            .get("default_view")
            .map(|view| string_sequence(view, "columns"))
            .unwrap_or_default();
        if !columns.is_empty() {
            let _ = writeln!(
                page,
                "\nDefault view: {}",
                columns
                    .iter()
                    .map(|column| format!("`{column}`"))
                    .collect::<Vec<_>>()
                    .join(", ")
            );
        }

        page.push_str("\n| field | type | unit | presence | meaning |\n|---|---|---|---|---|\n");
        for (field, definition) in mapping_entries(document, "fields") {
            let presence = if definition.get("required").and_then(Yaml::as_bool) == Some(true) {
                "required"
            } else if definition.get("nullable").and_then(Yaml::as_bool) == Some(true) {
                "nullable"
            } else {
                "optional"
            };
            let _ = writeln!(
                page,
                "| `{field}` | `{}` | {} | {presence} | {} |",
                string_at(definition, "type").unwrap_or_default(),
                string_at(definition, "unit").unwrap_or_else(|| "—".to_owned()),
                string_at(definition, "doc").unwrap_or_default()
            );
        }
    }
    page
}

fn errors_page(document: Option<&Yaml>) -> String {
    let mut page = header(
        "Errors",
        "The stable taxonomy of spec §43. Codes never change meaning, so a script may match on \
         them; the `name` is the selector `try`/`catch` and predicates over error values use.",
    );
    page.push_str("\n| code | selector | kind | meaning | what to do |\n|---|---|---|---|---|\n");
    for error in document.map(|d| sequence(d, "errors")).unwrap_or_default() {
        let _ = writeln!(
            page,
            "| `{}` | `{}` | {} | {} | {} |",
            string_at(error, "code").unwrap_or_default(),
            string_at(error, "name").unwrap_or_default(),
            string_at(error, "kind").unwrap_or_default(),
            string_at(error, "summary").unwrap_or_default(),
            string_at(error, "help").unwrap_or_default()
        );
    }
    page
}

fn capabilities_page(document: Option<&Yaml>) -> String {
    let mut page = header(
        "Capabilities",
        "Two vocabularies that are not the same thing. A **provider capability** is what a \
         provider must be able to do for a command to work. A **KUANG/11 capability** is what an \
         extension may ask Ono to do, and is a security boundary: granted, scoped, audited and \
         revocable (spec §31.16).",
    );

    for (key, title) in [
        ("provider_capabilities", "Provider capabilities"),
        ("kuang_capabilities", "KUANG/11 capabilities"),
    ] {
        let _ = write!(
            page,
            "\n## {title}\n\n| id | risk | elevation | meaning |\n|---|---|---|---|\n"
        );
        for capability in document.map(|d| sequence(d, key)).unwrap_or_default() {
            let _ = writeln!(
                page,
                "| `{}` | {} | {} | {} |",
                string_at(capability, "id").unwrap_or_default(),
                string_at(capability, "risk").unwrap_or_default(),
                string_at(capability, "elevation").unwrap_or_else(|| "none".to_owned()),
                string_at(capability, "summary").unwrap_or_default()
            );
        }
    }
    page
}

// --- reading ---------------------------------------------------------------------------------

fn load(path: &Path) -> Result<Option<Yaml>, GenerateError> {
    match std::fs::read_to_string(path) {
        Ok(text) => serde_yaml_ng::from_str(&text)
            .map(Some)
            .map_err(|error| GenerateError {
                detail: format!("{} is not valid YAML: {error}", path.display()),
            }),
        Err(_) => Ok(None),
    }
}

fn load_directory(directory: &Path) -> Result<BTreeMap<String, Yaml>, GenerateError> {
    let mut documents = BTreeMap::new();
    let Ok(entries) = std::fs::read_dir(directory) else {
        return Ok(documents);
    };
    let mut paths: Vec<PathBuf> = entries
        .flatten()
        .map(|entry| entry.path())
        .filter(|path| {
            path.extension()
                .is_some_and(|extension| extension == "yaml")
        })
        .collect();
    paths.sort();

    for path in paths {
        if let Some(document) = load(&path)? {
            let name = path
                .file_name()
                .map(|name| name.to_string_lossy().into_owned())
                .unwrap_or_default();
            documents.insert(name, document);
        }
    }
    Ok(documents)
}

fn sequence<'a>(document: &'a Yaml, key: &str) -> Vec<&'a Yaml> {
    document
        .get(key)
        .and_then(Yaml::as_sequence)
        .map(|items| items.iter().collect())
        .unwrap_or_default()
}

fn string_at(document: &Yaml, key: &str) -> Option<String> {
    document.get(key).and_then(Yaml::as_str).map(str::to_owned)
}

fn string_sequence(document: &Yaml, key: &str) -> Vec<String> {
    sequence(document, key)
        .into_iter()
        .filter_map(|item| item.as_str().map(str::to_owned))
        .collect()
}

fn mapping_entries<'a>(document: &'a Yaml, key: &str) -> Vec<(String, &'a Yaml)> {
    document
        .get(key)
        .and_then(Yaml::as_mapping)
        .map(|mapping| {
            mapping
                .iter()
                .filter_map(|(name, value)| Some((name.as_str()?.to_owned(), value)))
                .collect()
        })
        .unwrap_or_default()
}
