//! Generating `docs/reference/` from the registries (spec §36.2).
//!
//! Spec §36 is explicit that the machine-readable registries "become executable contracts" and
//! that documentation is derived from them. Deriving it is only half the job: the gate also
//! compares what is committed against what the generator produces, because a generator nobody
//! checks against the tree is a generator whose output has quietly diverged
//! (`docs/ACCEPTANCE.md` §4.5).

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use serde_yaml_ng::Value as Yaml;

pub use crate::scan::Problem;

/// The banner every generated page carries.
const BANNER: &str = "<!-- generated by `cargo xtask docs` from docs/spec/. Do not edit by hand: \
your changes will be overwritten and the gate will fail (AGENTS.md section 2). -->";

/// One generated page.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Page {
    /// Where the page belongs, relative to the repository root.
    pub path: String,
    /// The page's complete contents.
    pub contents: String,
}

/// Why generation could not run.
#[derive(Debug)]
pub struct GenerateError {
    /// What went wrong, phrased for the reader.
    pub detail: String,
}

impl std::fmt::Display for GenerateError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.detail)
    }
}

impl std::error::Error for GenerateError {}

/// Generates every reference page from the registries under `root/docs/spec`.
///
/// # Errors
///
/// Returns a [`GenerateError`] if `docs/spec/` is missing or a registry is not valid YAML.
pub fn generate(root: &Path) -> Result<Vec<Page>, GenerateError> {
    let spec = root.join("docs").join("spec");
    if !spec.is_dir() {
        return Err(GenerateError {
            detail: format!("{} does not exist", spec.display()),
        });
    }

    let verbs = load(&spec.join("verbs.yaml"))?;
    let targets = load(&spec.join("targets.yaml"))?;
    let errors = load(&spec.join("errors.yaml"))?;
    let capabilities = load(&spec.join("capabilities.yaml"))?;
    let schemas = load_directory(&spec.join("schemas"))?;
    let commands = load_directory(&spec.join("commands"))?;
    let packs = load_packs(&spec.join("adapters").join("first-party"))?;
    let streaming = load(&spec.join("hardening").join("streaming_classification.yaml"))?;

    let mut pages = vec![
        Page {
            path: "docs/reference/README.md".to_owned(),
            contents: index_page(),
        },
        Page {
            path: "docs/reference/commands.md".to_owned(),
            contents: commands_page(&commands),
        },
        Page {
            path: "docs/reference/verbs.md".to_owned(),
            contents: verbs_page(verbs.as_ref()),
        },
        Page {
            path: "docs/reference/targets.md".to_owned(),
            contents: targets_page(targets.as_ref()),
        },
        Page {
            path: "docs/reference/schemas.md".to_owned(),
            contents: schemas_page(&schemas),
        },
        Page {
            path: "docs/reference/errors.md".to_owned(),
            contents: errors_page(errors.as_ref()),
        },
        Page {
            path: "docs/reference/capabilities.md".to_owned(),
            contents: capabilities_page(capabilities.as_ref()),
        },
        Page {
            path: "docs/reference/streaming.md".to_owned(),
            contents: streaming_page(streaming.as_ref()),
        },
        Page {
            path: "docs/reference/terminology.md".to_owned(),
            contents: terminology_page(),
        },
        Page {
            path: "docs/reference/remote-trust.md".to_owned(),
            contents: remote_trust_page(),
        },
        Page {
            path: "docs/reference/release-verification.md".to_owned(),
            contents: release_verification_page(),
        },
    ];
    if !packs.is_empty() {
        pages.push(Page {
            path: "docs/reference/adapters/README.md".to_owned(),
            contents: adapters_matrix_page(&packs),
        });
        for pack in &packs {
            pages.push(Page {
                path: format!("docs/reference/adapters/{}.md", pack.id()),
                contents: adapter_pack_page(pack),
            });
        }
    }
    Ok(pages)
}

/// Compares the committed reference docs with what the registries would produce.
#[must_use]
pub fn check_committed(root: &Path) -> Vec<Problem> {
    let generated = match generate(root) {
        Ok(pages) => pages,
        Err(_) => return Vec::new(),
    };

    let mut problems = Vec::new();
    for page in generated {
        let path = root.join(&page.path);
        match std::fs::read_to_string(&path) {
            Ok(committed) if committed == page.contents => {}
            Ok(_) => problems.push(Problem {
                location: page.path.clone(),
                detail: "does not match what the registries produce; run `cargo xtask docs` \
                         (spec §36.2). If the difference is deliberate, the registry is where it \
                         belongs, not the page"
                    .to_owned(),
            }),
            Err(_) => problems.push(Problem {
                location: page.path.clone(),
                detail: "is missing; run `cargo xtask docs`".to_owned(),
            }),
        }
    }
    problems
}

/// Writes every generated page to disk.
///
/// # Errors
///
/// Returns a [`GenerateError`] if generation fails or a page cannot be written.
pub fn write(root: &Path) -> Result<Vec<String>, GenerateError> {
    let mut written = Vec::new();
    for page in generate(root)? {
        let path = root.join(&page.path);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).map_err(|error| GenerateError {
                detail: format!("cannot create {}: {error}", parent.display()),
            })?;
        }
        std::fs::write(&path, &page.contents).map_err(|error| GenerateError {
            detail: format!("cannot write {}: {error}", path.display()),
        })?;
        written.push(page.path);
    }
    Ok(written)
}

// --- pages -----------------------------------------------------------------------------------

fn header(title: &str, blurb: &str) -> String {
    format!("{BANNER}\n\n# {title}\n\n{blurb}\n")
}

fn index_page() -> String {
    let mut page = header(
        "Ono-Sendai reference",
        "Derived from the machine-readable contracts in `docs/spec/`, which are the public \
         contract of the product (spec section 27). The narrative specification explains intent; \
         these pages state what the shell promises.",
    );
    page.push_str(
        "\n| Page | Contract |\n\
         |---|---|\n\
         | [Commands](commands.md) | `docs/spec/commands/*.yaml` — every command, its schemas, \
         selectors, options and examples |\n\
         | [Verbs](verbs.md) | `docs/spec/verbs.yaml` — the controlled vocabulary of spec §7 |\n\
         | [Targets](targets.md) | `docs/spec/targets.yaml` — the nouns of spec §8 |\n\
         | [Schemas](schemas.md) | `docs/spec/schemas/*.v1.yaml` — the object contracts of spec §28 |\n\
         | [Adapters](adapters/README.md) | `docs/spec/adapters/first-party/*.yaml` — what each \
         external tool adapts, at which versions, through which invocations (spec v0.3 §1.66) |\n\
         | [Streaming](streaming.md) | `docs/spec/hardening/streaming_classification.yaml` — what \
         each pipeline operation may do to a stream, and what the order of events means (v0.4.1 \
         Appendix E, §27) |\n\
         | [Terminology](terminology.md) | `docs/spec/hardening/terminology.yaml` — the eight \
         security terms of v0.4.1 §19.1 and what each one promises |\n\
         | [Remote trust](remote-trust.md) | `docs/spec/hardening/remote_trust.yaml` — the six \
         things a remote link keeps apart, and what each one does not establish (v0.4.1 §51.3) |\n\
         | [Release verification](release-verification.md) | \
         `docs/spec/hardening/release_verification.yaml` — how to check a release's checksums, \
         signature and provenance before installing it (v0.4.1 §47.5, §67.7) |\n\
         | [Errors](errors.md) | `docs/spec/errors.yaml` — the stable taxonomy of spec §43 |\n\
         | [Capabilities](capabilities.md) | `docs/spec/capabilities.yaml` — provider and KUANG/11 \
         capabilities |\n\
         \nA command marked **planned** has a contract and no implementation: spec §52 asks that \
         its usefulness be validated rather than implemented for symmetry, and the registry \
         records the design surface without promising the command.\n",
    );
    page
}

fn commands_page(families: &BTreeMap<String, Yaml>) -> String {
    let mut page = header(
        "Command reference",
        "Every command Ono defines, grouped by family. `stability` says whether the contract is a \
         promise; `phase` says which phase of spec §37 delivers it.",
    );

    for (file, document) in families {
        let family = string_at(document, "family").unwrap_or_else(|| file.clone());
        let _ = write!(page, "\n## {family}\n");

        for command in sequence(document, "commands") {
            let id = string_at(command, "id").unwrap_or_default();
            let verb = string_at(command, "verb").unwrap_or_default();
            let target = string_at(command, "target").unwrap_or_default();
            let invocation = if target.is_empty() || target == "null" {
                verb.clone()
            } else {
                format!("{verb} {target}")
            };

            let _ = write!(page, "\n### `{invocation}`\n\n");
            let _ = writeln!(
                page,
                "{}\n",
                string_at(command, "summary").unwrap_or_default()
            );
            let _ = writeln!(page, "| | |\n|---|---|");
            let _ = writeln!(page, "| id | `{id}` |");
            let _ = writeln!(
                page,
                "| stability | {} |",
                string_at(command, "stability").unwrap_or_else(|| "unspecified".to_owned())
            );
            let _ = writeln!(
                page,
                "| phase | {} |",
                string_at(command, "phase").unwrap_or_else(|| "unspecified".to_owned())
            );
            let _ = writeln!(
                page,
                "| input | `{}` |",
                string_at(command, "input").unwrap_or_else(|| "null".to_owned())
            );
            let _ = writeln!(
                page,
                "| output | `{}` |",
                string_at(command, "output").unwrap_or_else(|| "null".to_owned())
            );
            if let Some(capability) = string_at(command, "provider_capability") {
                let _ = writeln!(page, "| provider capability | `{capability}` |");
            }
            let _ = writeln!(
                page,
                "| privilege | {} |",
                string_at(command, "privilege").unwrap_or_else(|| "none".to_owned())
            );
            let _ = writeln!(
                page,
                "| arguments | parsed in {} mode (ADR-0009) |",
                string_at(command, "argument_mode").unwrap_or_else(|| "words".to_owned())
            );

            let selectors = sequence(command, "selectors");
            if !selectors.is_empty() {
                let _ = write!(
                    page,
                    "\n**Selectors**\n\n| name | type | meaning |\n|---|---|---|\n"
                );
                for selector in selectors {
                    let _ = writeln!(
                        page,
                        "| `{}` | `{}` | {} |",
                        string_at(selector, "name").unwrap_or_default(),
                        string_at(selector, "type").unwrap_or_default(),
                        string_at(selector, "doc").unwrap_or_default()
                    );
                }
            }

            let options = sequence(command, "options");
            if !options.is_empty() {
                let _ = write!(
                    page,
                    "\n**Options**\n\n| name | type | meaning |\n|---|---|---|\n"
                );
                for option in options {
                    let _ = writeln!(
                        page,
                        "| `--{}` | `{}` | {} |",
                        string_at(option, "name").unwrap_or_default(),
                        string_at(option, "type").unwrap_or_default(),
                        string_at(option, "doc").unwrap_or_default()
                    );
                }
            }

            let examples = string_sequence(command, "examples");
            if !examples.is_empty() {
                page.push_str("\n**Examples**\n\n```text\n");
                for example in examples {
                    let _ = writeln!(page, "{example}");
                }
                page.push_str("```\n");
            }
        }
    }
    page
}

fn verbs_page(document: Option<&Yaml>) -> String {
    let mut page = header(
        "Verbs",
        "The controlled vocabulary of spec §7. The registry is deliberately small: a module reuses \
         an existing verb whenever the semantics match, and spec §40.1 requires a review before a \
         new one is added.",
    );
    page.push_str(
        "\n| verb | meaning | typical targets | pipeline role | mutates |\n|---|---|---|---|---|\n",
    );
    for verb in document.map(|d| sequence(d, "verbs")).unwrap_or_default() {
        let _ = writeln!(
            page,
            "| `{}` | {} | {} | {} | {} |",
            string_at(verb, "verb").unwrap_or_default(),
            string_at(verb, "semantics").unwrap_or_default(),
            string_sequence(verb, "typical_targets").join(", "),
            string_at(verb, "pipeline_role").unwrap_or_default(),
            if verb.get("mutating").and_then(Yaml::as_bool) == Some(true) {
                "yes"
            } else {
                "no"
            }
        );
    }
    page
}

fn targets_page(document: Option<&Yaml>) -> String {
    let mut page = header(
        "Targets",
        "The nouns of spec §8 — the resources a verb acts on. `schema` names the object contract a \
         target's commands produce.",
    );
    page.push_str("\n| target | category | schema | phase | meaning |\n|---|---|---|---|---|\n");
    for target in document.map(|d| sequence(d, "targets")).unwrap_or_default() {
        let schema = string_at(target, "schema").unwrap_or_else(|| "—".to_owned());
        let _ = writeln!(
            page,
            "| `{}` | {} | `{schema}` | {} | {} |",
            string_at(target, "name").unwrap_or_default(),
            string_at(target, "category").unwrap_or_default(),
            string_at(target, "phase").unwrap_or_else(|| "—".to_owned()),
            string_at(target, "summary").unwrap_or_default()
        );
    }
    page
}

fn schemas_page(files: &BTreeMap<String, Yaml>) -> String {
    let mut page = header(
        "Object schemas",
        "The object contracts of spec §28. A **nullable** field may be `null`, which means the \
         value is unknown — never that it is zero or empty (spec §10.5). `identity` is what makes \
         two observations of the same object the same object.",
    );

    for (file, document) in files {
        if file.ends_with("deferred.yaml") {
            continue;
        }
        let id = string_at(document, "id").unwrap_or_default();
        let name = string_at(document, "name").unwrap_or_default();
        let _ = write!(page, "\n## {name} — `{id}`\n\n");
        let _ = writeln!(
            page,
            "{}\n",
            string_at(document, "summary").unwrap_or_default()
        );
        let _ = writeln!(
            page,
            "Identity: {}",
            string_sequence(document, "identity")
                .iter()
                .map(|field| format!("`{field}`"))
                .collect::<Vec<_>>()
                .join(", ")
        );
        let fallback = string_sequence(document, "identity_fallback");
        if !fallback.is_empty() {
            let _ = writeln!(
                page,
                "\nWhen that identity is incomplete, it is joined by: {}",
                fallback
                    .iter()
                    .map(|field| format!("`{field}`"))
                    .collect::<Vec<_>>()
                    .join(", ")
            );
        }
        let columns = document
            .get("default_view")
            .map(|view| string_sequence(view, "columns"))
            .unwrap_or_default();
        if !columns.is_empty() {
            let _ = writeln!(
                page,
                "\nDefault view: {}",
                columns
                    .iter()
                    .map(|column| format!("`{column}`"))
                    .collect::<Vec<_>>()
                    .join(", ")
            );
        }

        page.push_str("\n| field | type | unit | presence | meaning |\n|---|---|---|---|---|\n");
        for (field, definition) in mapping_entries(document, "fields") {
            let presence = if definition.get("required").and_then(Yaml::as_bool) == Some(true) {
                "required"
            } else if definition.get("nullable").and_then(Yaml::as_bool) == Some(true) {
                "nullable"
            } else {
                "optional"
            };
            let _ = writeln!(
                page,
                "| `{field}` | `{}` | {} | {presence} | {} |",
                string_at(definition, "type").unwrap_or_default(),
                string_at(definition, "unit").unwrap_or_else(|| "—".to_owned()),
                string_at(definition, "doc").unwrap_or_default()
            );
        }
    }
    page
}

fn streaming_page(document: Option<&Yaml>) -> String {
    let mut page = header(
        "Streaming and event ordering",
        "What each pipeline operation may do to a stream, and what a consumer may conclude from \
         the order it observed events in. The classes are v0.4.1 Appendix E; the ordering \
         contract is v0.4.1 §27. Both are rendered from \
         `docs/spec/hardening/streaming_classification.yaml`, which is also what `explain` reads \
         and what the gate compares the command contracts against.",
    );
    let Some(document) = document else {
        page.push_str("\nNo streaming classification is declared.\n");
        return page;
    };

    page.push_str("\n## Classes\n\n| Class | Appendix E | Requires finite input | May materialize |\n|---|---|---|---|\n");
    for class in sequence(document, "classes") {
        let flag = |key: &str| {
            if class.get(key).and_then(Yaml::as_bool).unwrap_or(false) {
                "yes"
            } else {
                "no"
            }
        };
        page.push_str(&format!(
            "| `{}` | {} | {} | {} |\n",
            string_at(class, "id").unwrap_or_default(),
            cell(&string_at(class, "appendix_e").unwrap_or_default()),
            flag("requires_finite_input"),
            flag("may_materialize"),
        ));
    }
    for class in sequence(document, "classes") {
        if let Some(doc) = string_at(class, "doc") {
            page.push_str(&format!(
                "\n**`{}`** — {}\n",
                string_at(class, "id").unwrap_or_default(),
                doc.trim()
            ));
        }
    }

    page.push_str("\n## Where each operation sits\n\n| Command | Class |\n|---|---|\n");
    for operation in sequence(document, "operations") {
        page.push_str(&format!(
            "| `{}` | `{}` |\n",
            string_at(operation, "command").unwrap_or_default(),
            string_at(operation, "class").unwrap_or_default(),
        ));
    }

    let Some(ordering) = document.get("ordering") else {
        return page;
    };
    page.push_str("\n## Event ordering\n");
    for (heading, key) in [
        ("Within one channel", "per_channel"),
        ("Between the two kinds", "cross_kind"),
        ("Causality", "causality"),
        ("When a total order is part of the answer", "total_order"),
    ] {
        if let Some(text) = string_at(ordering, key) {
            page.push_str(&format!("\n**{heading}.** {}\n", text.trim()));
        }
    }
    if !sequence(ordering, "channels").is_empty() {
        page.push_str("\n| Channel | Carries | Ordered within itself |\n|---|---|---|\n");
        for channel in sequence(ordering, "channels") {
            page.push_str(&format!(
                "| `{}` | {} | {} |\n",
                string_at(channel, "id").unwrap_or_default(),
                cell(&string_at(channel, "carries").unwrap_or_default()),
                if channel
                    .get("ordered_within_itself")
                    .and_then(Yaml::as_bool)
                    .unwrap_or(false)
                {
                    "yes"
                } else {
                    "no"
                },
            ));
        }
        for channel in sequence(ordering, "channels") {
            if let Some(doc) = string_at(channel, "doc") {
                page.push_str(&format!(
                    "\n**`{}`** — {}\n",
                    string_at(channel, "id").unwrap_or_default(),
                    doc.trim()
                ));
            }
        }
    }
    page
}

/// v0.4.1 §19.1's eight terms, rendered from the registry that also drives the gate.
///
/// §19.2: *"Where command contracts or capability tables already generate reference
/// documentation, the security terms SHOULD be generated from the same registries rather than
/// duplicated in prose."* So this page is the one place a reader is shown the definitions, and
/// `xtask::terminology` reads the same rows before it judges a document — a paraphrase cannot
/// drift from the rule because there is no paraphrase.
fn terminology_page() -> String {
    let mut page = header(
        "Security terminology",
        "Eight words with fixed meanings (v0.4.1 \u{a7}19.1). They mean this in the README, in the \
         Wiki, in `help`, on these pages and in the architecture documentation, and nowhere in \
         the product do they mean anything else. \u{a7}51.1 states the purpose: the goal is not to ban \
         these words, it is to ensure they refer to a defined contract \u{2014} so the contract is \
         `docs/spec/hardening/terminology.yaml`, this page is rendered from it, and \
         `cargo xtask spec-check` holds every document the repository can reach to the same rows.",
    );
    page.push_str("\n| Term | Meaning |\n|---|---|\n");
    for term in crate::terminology::terms() {
        page.push_str(&format!("| `{}` | {} |\n", term.term, cell(&term.meaning)));
    }
    for term in crate::terminology::terms() {
        page.push_str(&format!(
            "\n## `{}`\n\n> {}\n\n{}\n\nFixed by {}.\n",
            term.term,
            term.meaning,
            term.doc.trim(),
            term.spec
        ));
        if !term.overstates.is_empty() {
            page.push_str(
                "\nWordings the documentation gate refuses, because they claim a boundary this \
                 build does not enforce:\n\n",
            );
            for phrase in &term.overstates {
                page.push_str(&format!("- `{phrase}`\n"));
            }
            if term.qualified_by.is_empty() {
                page.push_str(
                    "\nNo qualifier makes these true; the remedy is to state the boundary that \
                     does exist.\n",
                );
            } else {
                page.push_str(
                    "\nThe wording to use instead, in the sentence itself \u{2014} a disclaimer \
                     elsewhere in the same document does not make the claim above true \
                     (\u{a7}17.3 asks for a qualifier that is *immediate*):\n\n",
                );
                for phrase in &term.qualified_by {
                    page.push_str(&format!("- {phrase}\n"));
                }
            }
        }
    }
    page
}

/// v0.4.1 §51.3's six remote trust concepts, rendered from the registry.
///
/// §51.3 requires remote-link documentation to distinguish them, and the reason each one is on
/// the list is that it is easy to mistake for one of the others. So the page is a table of what
/// each establishes beside what it does not, which is the shape a conflation cannot survive.
fn remote_trust_page() -> String {
    let mut page = header(
        "Remote trust",
        "Six things a remote link keeps apart (v0.4.1 \u{a7}51.3). Each says what a reader may \
         conclude when it is in place and \u{2014} the column that does the work \u{2014} what a reader may \
         not. \u{a7}7.3 is why: the transport identity and the runtime identity are different fields, \
         one is a cryptographic credential and the other is a self-report, and \u{a7}65.1 and \u{a7}65.2 \
         are the two ways confusing them goes wrong. Rendered from \
         `docs/spec/hardening/remote_trust.yaml`, which the documentation gate reads as well.",
    );
    let Some(concepts) = crate::terminology::remote_trust() else {
        page.push_str("\nNo remote trust model is declared.\n");
        return page;
    };

    page.push_str("\n| Concept | Establishes | Does not establish |\n|---|---|---|\n");
    for concept in &concepts {
        page.push_str(&format!(
            "| **{}** | {} | {} |\n",
            cell(&concept.name),
            cell(concept.establishes.trim()),
            cell(concept.does_not.trim()),
        ));
    }
    for concept in &concepts {
        page.push_str(&format!(
            "\n## {}\n\n{}\n\n**It does not establish.** {}\n",
            concept.name,
            concept.establishes.trim(),
            concept.does_not.trim(),
        ));
        if !concept.commands.is_empty() {
            page.push_str(&format!(
                "\nOperated by {}.\n",
                concept
                    .commands
                    .iter()
                    .map(|command| format!("`{command}`"))
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
        }
        page.push_str(&format!(
            "\nBoundary: {}. Fixed by {}.\n",
            concept.boundary.as_deref().map_or_else(
                || "none \u{2014} this is metadata, not a boundary".to_owned(),
                |id| format!("`{id}`")
            ),
            concept.spec
        ));
    }
    page
}

/// The release verification sequence of v0.4.1 §47.5, rendered from the registry.
///
/// §47.5 wants the sequence in the installation documentation and short enough to paste. This is
/// the copy the gate compares the README and the Wiki against, so three documents cannot drift
/// into three different sets of commands.
fn release_verification_page() -> String {
    let mut page = header(
        "Verifying a release",
        "Every release publishes the digest of every artifact, a signature over that manifest and \
         signed build provenance (v0.4.1 \u{a7}47.1). This is how to check them before installing \
         anything. Rendered from `docs/spec/hardening/release_verification.yaml`, which the README \
         and the Wiki's Install page carry the same commands from.",
    );
    let Some(sequence) = crate::verification::sequence() else {
        page.push_str("\nNo verification sequence is declared.\n");
        return page;
    };

    page.push_str("\n## What a release publishes\n\n| File | Contents |\n|---|---|\n");
    for file in &sequence.files {
        page.push_str(&format!(
            "| `{}` | {} ({}) |\n",
            file.name,
            cell(file.contents.trim()),
            file.spec
        ));
    }

    page.push_str(&format!(
        "\n## The sequence\n\n**The order is the security property.** The signature over the \
         manifest is verified first and the artifacts are checked against the manifest second. \
         Reversed, the sequence proves only that the download was not corrupted in transit: a \
         manifest an attacker wrote agrees perfectly with the artifacts that attacker also wrote. \
         A signature is expected to name `{}`, the workflow `{}` and the issuer `{}`, and one \
         that verifies against anything else is a valid signature by somebody else.\n",
        sequence.repository, sequence.workflow, sequence.issuer
    ));

    for (index, step) in sequence.steps.iter().enumerate() {
        page.push_str(&format!(
            "\n### {}. `{}`\n\n```bash\n{}\n```\n\n**Proves.** {}\n\n**If it fails.** {}\n",
            index + 1,
            step.id,
            step.command.trim_end(),
            step.proves.trim(),
            step.on_failure.trim(),
        ));
        if !step.requires.is_empty() {
            page.push_str(&format!(
                "\nNeeds {}.\n",
                step.requires
                    .iter()
                    .map(|tool| format!("`{tool}`"))
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
        }
        if !step.executable {
            page.push_str(&format!(
                "\n*Not run by this repository's own tests: {}.*\n",
                step.executable_because.trim()
            ));
        }
    }
    page
}

fn errors_page(document: Option<&Yaml>) -> String {
    let mut page = header(
        "Errors",
        "The stable taxonomy of spec §43. Codes never change meaning, so a script may match on \
         them; the `name` is the selector `try`/`catch` and predicates over error values use.",
    );
    page.push_str("\n| code | selector | kind | meaning | what to do |\n|---|---|---|---|---|\n");
    for error in document.map(|d| sequence(d, "errors")).unwrap_or_default() {
        let _ = writeln!(
            page,
            "| `{}` | `{}` | {} | {} | {} |",
            string_at(error, "code").unwrap_or_default(),
            string_at(error, "name").unwrap_or_default(),
            string_at(error, "kind").unwrap_or_default(),
            string_at(error, "summary").unwrap_or_default(),
            string_at(error, "help").unwrap_or_default()
        );
    }
    page
}

fn capabilities_page(document: Option<&Yaml>) -> String {
    let mut page = header(
        "Capabilities",
        "Two vocabularies that are not the same thing. A **provider capability** is what a \
         provider must be able to do for a command to work. A **KUANG/11 capability** is what an \
         extension may ask Ono to do, and is a security boundary: granted, scoped, audited and \
         revocable (spec §31.16).",
    );

    for (key, title) in [
        ("provider_capabilities", "Provider capabilities"),
        ("kuang_capabilities", "KUANG/11 capabilities"),
    ] {
        let _ = write!(
            page,
            "\n## {title}\n\n| id | risk | elevation | meaning |\n|---|---|---|---|\n"
        );
        for capability in document.map(|d| sequence(d, key)).unwrap_or_default() {
            let _ = writeln!(
                page,
                "| `{}` | {} | {} | {} |",
                string_at(capability, "id").unwrap_or_default(),
                string_at(capability, "risk").unwrap_or_default(),
                string_at(capability, "elevation").unwrap_or_else(|| "none".to_owned()),
                string_at(capability, "summary").unwrap_or_default()
            );
        }
    }
    page
}

// --- reading ---------------------------------------------------------------------------------

/// Loads every adapter pack contract, in path order, so pages come out in one order.
fn load_packs(directory: &Path) -> Result<Vec<ono_adapter::AdapterPack>, GenerateError> {
    let mut packs = Vec::new();
    for (file, _) in load_directory(directory)? {
        let path = directory.join(&file);
        let text = std::fs::read_to_string(&path).map_err(|error| GenerateError {
            detail: format!("cannot read {}: {error}", path.display()),
        })?;
        packs.push(
            ono_adapter::AdapterPack::parse(&text).map_err(|error| GenerateError {
                detail: format!("{} is not a valid adapter pack: {error}", path.display()),
            })?,
        );
    }
    packs.sort_by(|left, right| left.id().cmp(right.id()));
    Ok(packs)
}

/// Text inside a table cell: a `|` in an invocation summary would otherwise split the row.
fn cell(text: &str) -> String {
    text.replace('|', "\\|")
}

fn tier_name(tier: ono_adapter::StrategyTier) -> &'static str {
    match tier {
        ono_adapter::StrategyTier::A => "A — structured native output",
        ono_adapter::StrategyTier::B => "B — stable machine-readable format",
        ono_adapter::StrategyTier::C => "C — version-constrained parser",
    }
}

fn tier_letter(tier: ono_adapter::StrategyTier) -> &'static str {
    match tier {
        ono_adapter::StrategyTier::A => "A",
        ono_adapter::StrategyTier::B => "B",
        ono_adapter::StrategyTier::C => "C",
    }
}

fn demand_names(adapter: &ono_adapter::Adapter) -> String {
    adapter
        .output_demand()
        .iter()
        .map(|demand| match demand {
            ono_adapter::DemandKind::Structured => "structured",
            ono_adapter::DemandKind::Interactive => "interactive",
        })
        .collect::<Vec<_>>()
        .join(", ")
}

fn fallback_name(fallback: ono_adapter::Fallback) -> &'static str {
    match fallback {
        ono_adapter::Fallback::Raw => "raw",
        ono_adapter::Fallback::Error => "error",
    }
}

/// The compatibility matrix of spec v0.3 §1.66: one row per adapter, every claim a contract
/// line.
fn adapters_matrix_page(packs: &[ono_adapter::AdapterPack]) -> String {
    let mut page = header(
        "External command adapters",
        "The compatibility matrix of spec v0.3 §1.66, derived from `docs/spec/adapters/first-party/*.yaml`. \
         A tool not listed here runs raw, exactly as typed; a listed tool runs raw too whenever \
         the typed invocation is not one its adapter declares, or the installed version is outside \
         the declared range — `explain <command>` says which. `raw <command>` bypasses the layer \
         unconditionally (spec v0.3 §1.2).",
    );
    page.push_str(
        "\n| tool | adapter | versions | tier | invocations | schema | demand | fallback |\n\
         |---|---|---|---|---|---|---|---|\n",
    );
    for pack in packs {
        for adapter in pack.adapters() {
            let invocations = adapter
                .invocations()
                .iter()
                .map(|invocation| format!("`{}`", cell(invocation.summary())))
                .collect::<Vec<_>>()
                .join("<br>");
            let _ = writeln!(
                page,
                "| `{}` | [`{}`]({}.md#{}) | `{}` | {} | {} | `{}` | {} | {} |",
                adapter.executable().names().join("`, `"),
                adapter.full_id(),
                pack.id(),
                adapter.id(),
                adapter.executable().versions(),
                tier_letter(adapter.tier()),
                invocations,
                adapter.schema(),
                demand_names(adapter),
                fallback_name(adapter.fallback()),
            );
        }
    }
    page.push_str("\n## Packs\n\n| pack | version | tier | executables |\n|---|---|---|---|\n");
    for pack in packs {
        let _ = writeln!(
            page,
            "| [{}]({}.md) | `{}` | {} | `{}` |",
            pack.name(),
            pack.id(),
            pack.version(),
            match pack.tier() {
                ono_adapter::Tier::FirstParty => "first-party",
                ono_adapter::Tier::Recommended => "recommended",
                ono_adapter::Tier::Community => "community",
                ono_adapter::Tier::Experimental => "experimental",
            },
            pack.executables().join("`, `"),
        );
    }
    page
}

/// One pack's page: every adapter with its invocations, its field map, its limits — what is
/// supported and, just as visibly, what is not (spec v0.3 §1.68 item 14).
fn adapter_pack_page(pack: &ono_adapter::AdapterPack) -> String {
    let mut page = header(
        &format!("{} — `{}`", pack.name(), pack.id()),
        &format!(
            "Version `{}`; process.exec executables: `{}`. Everything below is the pack's \
             contract; an invocation not listed under an adapter runs raw, and the limits state \
             what the adapted form does not carry.",
            pack.version(),
            pack.executables().join("`, `")
        ),
    );
    for adapter in pack.adapters() {
        let _ = write!(
            page,
            "\n## {} — `{}`\n\n{}\n\n",
            adapter.id(),
            adapter.full_id(),
            adapter.summary()
        );
        let _ = writeln!(
            page,
            "| | |\n|---|---|\n| executable | `{}` |\n| versions | `{}` |\n| tier | {} |\n\
             | schema | `{}` |\n| decoder | `{}` |\n| demand | {} |\n| fallback | {} |\n| fixtures | `{}` |",
            adapter.executable().names().join("`, `"),
            adapter.executable().versions(),
            tier_name(adapter.tier()),
            adapter.schema(),
            adapter
                .decoder()
                .id()
                .unwrap_or(match adapter.decoder().kind() {
                    ono_adapter::DecoderKind::Json => "json",
                    ono_adapter::DecoderKind::Jsonl => "jsonl",
                    ono_adapter::DecoderKind::Lines => "lines",
                    ono_adapter::DecoderKind::Properties => "properties",
                    ono_adapter::DecoderKind::Builtin => "builtin",
                }),
            demand_names(adapter),
            fallback_name(adapter.fallback()),
            adapter.fixtures(),
        );
        page.push_str("\n### Supported invocations\n\n| invocation | runs as | flags allowed | flags required |\n|---|---|---|---|\n");
        for invocation in adapter.invocations() {
            let matcher = invocation.matcher();
            let mut allowed: Vec<String> = matcher.allowed_flags().to_vec();
            allowed.extend(
                matcher
                    .allowed_flags_with_value()
                    .iter()
                    .map(|flag| format!("{flag} <value>")),
            );
            let _ = writeln!(
                page,
                "| `{}` | `{}` | {} | {} |",
                cell(invocation.summary()),
                cell(&invocation.plan().argv().join(" ")),
                if allowed.is_empty() {
                    "—".to_owned()
                } else {
                    format!("`{}`", allowed.join("`, `"))
                },
                if matcher.required_flags().is_empty() {
                    "—".to_owned()
                } else {
                    format!("`{}`", matcher.required_flags().join("`, `"))
                },
            );
        }
        page.push_str("\n### Fields\n\n| field | from |\n|---|---|\n");
        for (name, map) in adapter.fields() {
            let mut from = format!("`{}`", map.from());
            if let Some(unit) = map.unit() {
                let _ = write!(from, ", unit {unit:?}");
            }
            if let Some(template) = map.template() {
                let _ = write!(from, ", template `{template}`");
            }
            let _ = writeln!(page, "| `{name}` | {from} |");
        }
        page.push_str("\n### Limits\n\n");
        if adapter.limits().is_empty() {
            page.push_str("None declared.\n");
        }
        for limit in adapter.limits() {
            let _ = writeln!(page, "- {limit}");
        }
    }
    page
}

fn load(path: &Path) -> Result<Option<Yaml>, GenerateError> {
    match std::fs::read_to_string(path) {
        Ok(text) => serde_yaml_ng::from_str(&text)
            .map(Some)
            .map_err(|error| GenerateError {
                detail: format!("{} is not valid YAML: {error}", path.display()),
            }),
        Err(_) => Ok(None),
    }
}

fn load_directory(directory: &Path) -> Result<BTreeMap<String, Yaml>, GenerateError> {
    let mut documents = BTreeMap::new();
    let Ok(entries) = std::fs::read_dir(directory) else {
        return Ok(documents);
    };
    let mut paths: Vec<PathBuf> = entries
        .flatten()
        .map(|entry| entry.path())
        .filter(|path| {
            path.extension()
                .is_some_and(|extension| extension == "yaml")
        })
        .collect();
    paths.sort();

    for path in paths {
        if let Some(document) = load(&path)? {
            let name = path
                .file_name()
                .map(|name| name.to_string_lossy().into_owned())
                .unwrap_or_default();
            documents.insert(name, document);
        }
    }
    Ok(documents)
}

fn sequence<'a>(document: &'a Yaml, key: &str) -> Vec<&'a Yaml> {
    document
        .get(key)
        .and_then(Yaml::as_sequence)
        .map(|items| items.iter().collect())
        .unwrap_or_default()
}

fn string_at(document: &Yaml, key: &str) -> Option<String> {
    document.get(key).and_then(Yaml::as_str).map(str::to_owned)
}

fn string_sequence(document: &Yaml, key: &str) -> Vec<String> {
    sequence(document, key)
        .into_iter()
        .filter_map(|item| item.as_str().map(str::to_owned))
        .collect()
}

fn mapping_entries<'a>(document: &'a Yaml, key: &str) -> Vec<(String, &'a Yaml)> {
    document
        .get(key)
        .and_then(Yaml::as_mapping)
        .map(|mapping| {
            mapping
                .iter()
                .filter_map(|(name, value)| Some((name.as_str()?.to_owned(), value)))
                .collect()
        })
        .unwrap_or_default()
}

// --- the checklist's own generation claims ------------------------------------------------------

/// Checks that every "generated from" claim in `docs/ACCEPTANCE.md` names something that is
/// actually generated.
///
/// `docs/ACCEPTANCE.md` is the definition of done, and a box that describes machinery nobody
/// built is worse than an open box: it is a claim the reader has no reason to doubt. Two of them
/// said "generated" of hand-written suites for a whole tranche. The rule that stops it recurring
/// is mechanical — a bullet that claims generation must name, before the claim, at least one path
/// `cargo xtask docs` writes.
///
/// `generated` is the set of pages the generator produces; `text` is the checklist.
#[must_use]
pub fn check_generation_claims(text: &str, generated: &[String]) -> Vec<Problem> {
    const CLAIM: &str = "generated from";
    let mut problems = Vec::new();

    for bullet in bullets(text) {
        let Some(at) = bullet.find(CLAIM) else {
            continue;
        };
        let claimed: Vec<&str> = backticked(&bullet[..at]);
        if claimed.iter().any(|path| is_generated(path, generated)) {
            continue;
        }
        let headline: String = bullet
            .split_whitespace()
            .take(12)
            .collect::<Vec<_>>()
            .join(" ");
        problems.push(Problem {
            location: "docs/ACCEPTANCE.md".to_owned(),
            detail: format!(
                "a box claims something is `{CLAIM} …` without naming anything `cargo xtask \
                 docs` generates: “{headline}…”. Either generate it, or say what the tree \
                 actually does — a checklist that describes machinery nobody built cannot be \
                 checked"
            ),
        });
    }

    problems
}

/// Whether `path` — as a checklist writes it, possibly a directory — is generated.
fn is_generated(path: &str, generated: &[String]) -> bool {
    let path = path.trim_end_matches('/');
    generated
        .iter()
        .any(|page| page == path || page.starts_with(&format!("{path}/")))
}

/// The checklist's boxes, one string each, from `- [` to the next box or heading.
fn bullets(text: &str) -> Vec<String> {
    let mut bullets = Vec::new();
    let mut current: Option<String> = None;
    for line in text.lines() {
        let trimmed = line.trim_start();
        if trimmed.starts_with("- [") {
            if let Some(bullet) = current.take() {
                bullets.push(bullet);
            }
            current = Some(trimmed.to_owned());
        } else if trimmed.starts_with('#') {
            if let Some(bullet) = current.take() {
                bullets.push(bullet);
            }
        } else if let Some(bullet) = current.as_mut() {
            bullet.push(' ');
            bullet.push_str(trimmed);
        }
    }
    if let Some(bullet) = current {
        bullets.push(bullet);
    }
    bullets
}

/// The backticked tokens of `passage` that look like a path.
fn backticked(passage: &str) -> Vec<&str> {
    passage
        .split('`')
        .skip(1)
        .step_by(2)
        .filter(|token| token.contains('/') && !token.contains(' '))
        .collect()
}

// --- v0.4.1 §63: the migration guide prints commands that exist (issue #116, ADR-0543) ----------

/// Where the migration guide lives.
pub const MIGRATION_GUIDE: &str = "docs/MIGRATION.md";

/// Resolves every command `docs/MIGRATION.md` prints against the contracts (v0.4.1 §63, §66.8).
///
/// §66.8 makes "remote client authorization migration is documented" a release criterion, and
/// §63.2 prints the sequence an operator runs. A migration guide is the one document nobody reads
/// until they are already stuck, which is exactly when a renamed flag or a retired capability id
/// is most expensive: the reader has an agent refusing connections and a command that does not
/// exist.
///
/// So every `ono` invocation in a fenced block is resolved. A command spelling has to be one the
/// registry answers to; a capability id named in a grant has to be one the registry declares; a
/// flag has to be one the binary's own usage text lists. Nothing here checks that the *sequence*
/// works — that is `crates/ono-cli/tests/client_keys.rs` and case `182`.
#[must_use]
pub fn check_migration_guide(root: &Path) -> Vec<Problem> {
    let Ok(text) = std::fs::read_to_string(root.join(MIGRATION_GUIDE)) else {
        return vec![Problem {
            location: MIGRATION_GUIDE.to_owned(),
            detail: "does not exist. v0.4.1 §63 has five migrations and §66.8 makes the remote \
                     client authorization one a release criterion."
                .to_owned(),
        }];
    };
    let Ok(registry) = ono_command::CommandRegistry::load() else {
        return vec![Problem {
            location: MIGRATION_GUIDE.to_owned(),
            detail: "cannot be resolved: the command registry does not load".to_owned(),
        }];
    };
    let usage = ono_cli::usage_text();

    let mut problems = Vec::new();
    let mut invocations = 0usize;
    for invocation in ono_invocations(&text) {
        invocations += 1;
        let problem = |detail: String| Problem {
            location: MIGRATION_GUIDE.to_owned(),
            detail,
        };
        match &invocation {
            Invocation::Flag(flag) => {
                if !usage.contains(flag.as_str()) {
                    problems.push(problem(format!(
                        "prints `ono {flag}`, and the binary's own usage text does not list that \
                         flag. A migration guide is read by somebody who is already stuck."
                    )));
                }
            }
            Invocation::Script(script) => {
                let parsed = ono_parser::parse(script);
                if parsed.has_errors() || !parsed.is_complete() {
                    problems.push(problem(format!(
                        "prints `ono -c '{script}'`, which does not parse"
                    )));
                    continue;
                }
                for (verb, target) in spellings(script) {
                    if registry.find(&verb, Some(&target)).is_none()
                        && registry.find(&verb, None).is_none()
                    {
                        problems.push(problem(format!(
                            "prints `{verb} {target}`, which the command registry does not answer \
                             to. Either the guide is stale or the command was renamed without it."
                        )));
                    }
                }
                for capability in granted_capabilities(script) {
                    if registry.capability(&capability).is_none() {
                        problems.push(problem(format!(
                            "grants `{capability}`, which `docs/spec/capabilities.yaml` does not \
                             declare. v0.4.1 §9.5: grants name exact capability ids, so a guide \
                             that prints a retired one teaches an operator a command that fails."
                        )));
                    }
                }
            }
        }
    }

    if invocations == 0 {
        problems.push(Problem {
            location: MIGRATION_GUIDE.to_owned(),
            detail: "prints no `ono` invocation at all. v0.4.1 §63.2 is a sequence of commands, \
                     and a migration described without them is one nobody can follow."
                .to_owned(),
        });
    }
    problems
}

/// One `ono` invocation a document prints.
enum Invocation {
    /// A command-line flag, as in `ono --print-peer-key`.
    Flag(String),
    /// The script `ono -c` was given.
    Script(String),
}

/// Every `ono` invocation inside a fenced block of `markdown`.
fn ono_invocations(markdown: &str) -> Vec<Invocation> {
    let mut invocations = Vec::new();
    let mut fenced = false;
    for line in markdown.lines() {
        if line.trim_start().starts_with("```") {
            fenced = !fenced;
            continue;
        }
        if !fenced {
            continue;
        }
        let Some(rest) = line.trim().strip_prefix("ono ") else {
            continue;
        };
        if let Some(script) = rest.strip_prefix("-c ") {
            let script = script.trim().trim_matches('\'').trim_matches('"');
            invocations.push(Invocation::Script(script.to_owned()));
            continue;
        }
        for word in rest.split_whitespace() {
            if word.starts_with("--") {
                invocations.push(Invocation::Flag(word.to_owned()));
            }
        }
    }
    invocations
}

/// The `verb target` spellings a script names, one per statement.
///
/// A textual reading of the first two words of each statement, which is how the registry is
/// addressed and how every example in this repository writes one. A word beginning with `-` or
/// `$` is an argument rather than a target, and a statement that has only a verb is resolved as
/// one.
fn spellings(script: &str) -> Vec<(String, String)> {
    script
        .split(['\n', ';'])
        .filter_map(|statement| {
            let mut words = statement.split_whitespace();
            let verb = words.next()?.to_owned();
            let target = words
                .next()
                .filter(|word| !word.starts_with('-') && !word.starts_with('$'))
                .unwrap_or_default()
                .to_owned();
            Some((verb, target))
        })
        .collect()
}

/// The capability ids a script grants with `--allow`.
fn granted_capabilities(script: &str) -> Vec<String> {
    let words: Vec<&str> = script.split_whitespace().collect();
    words
        .windows(2)
        .filter(|pair| pair[0] == "--allow")
        .map(|pair| pair[1].to_owned())
        .collect()
}
